### ISSUE TITLE
Link to generate repo broken

### ISSUE THREAD

**Issue by zacharyneveu** [fastai/nbdev#10]
Link to `https://github.com/fastai/nbdev_template/generate` in the readme returns a 404. Is it just supposed to go to the repo or is there a widget to customize the `settings.ini` info?

**Comment by kdorichev** [comment]
It has also appeared broken to me, when I used a mobile device. It works fine from the desktop. I don't know why. The link leads to a page that allows you to create a GitHub repo based on the repo template.

**Comment by sgugger** [comment]
It's not broken, you jsut need to be logged in to GitHub for it to work (see the answer on #9).
