### ISSUE TITLE
DOC: Broken link to svg in docs

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#1005]
On https://nbdev.fast.ai/API/release.html the link to the svg file is broken:

https://nbdev.fast.ai/API/images/release.svg

**Comment by michaelaye** [comment]
Another 404 on same page: https://nbdev.fast.ai/API/images/token.png

**Comment by seeM** [comment]
Thanks for reporting this! You caught us in the process of refactoring to use [Quarto's new sidebar autogeneration](https://quarto.org/docs/websites/website-navigation.html#auto-generation). Links should be working now
