### ISSUE TITLE
Deploy Action for notebooks with execute: enabled: true does not recognize the "hide" directive

### ISSUE THREAD

**Issue by tylere** [fastai/nbdev#1017]
## Test environment

Setup:
`conda create -n test-evaluate-code-2 -c conda-forge -c fastai python=3.10 gh jupyterlab jupyterlab-git ghapi ipywidgets`
`conda activate test-evaluate-code-2`
`pip install -U git+https://github.com/fastai/nbdev.git@08462b3da90c86a06cd62159babc69c346d21f88`
`cd test-evaluate-code-2`
`nbdev_install_quarto`
`nbdev_new`
`nbdev_install_hooks`

Library versions:
```
(test-evaluate-code-2) tylere-macbookpro5:test-evaluate-code-2 tylere$ pip list | grep nbdev
nbdev                         2.3.0
(test-evaluate-code-2) tylere-macbookpro5:test-evaluate-code-2 tylere$ quarto -v
1.1.189
```

## To replicate:

1. In `index.ipynb`, add a raw format cell as the first cell of the notebook with the following frontmatter content:
```
---
execute:
    enabled: true
---
```
2. Add two code cells to print the current time:
```
import datetime
```
```
print(f'time = {datetime.datetime.now()}')
```
3. Prepare the changes for a push to GitHub.
```
nbdev_prepare
```
4. Push the changes to GitHub.
5. Wait for the GitHub Actions to run.
6. Note the error indicating that the `hide` directive in the first code cell fails.

https://github.com/tylere/test-evaluate-code-2/runs/8242110591?check_suite_focus=true#step:2:387
> Executing 'index.ipynb'
>   Cell 1/5...
> 
> None of the known patterns match for hide
> Quarto is not installed. We will download and install it for you.
> Installing or upgrading quarto -- this requires root access.
> Error: Process completed with exit code 1.

A repository with this content is available at: https://github.com/tylere/test-evaluate-code-2

**Comment by jph00** [comment]
Since you're using prerelease nbdev from master for creating your project, you'll need to use that to deploy it too. Set `pre` to `1` in your workflow, as we do here:

https://github.com/fastai/nbdev/blob/master/.github/workflows/deploy.yaml
