### ISSUE TITLE
push to main branch removes custom domain from GitHub Pages settings

### ISSUE THREAD

**Issue by rossheat** [fastai/nbdev#1033]
When I push to my main branch, the custom domain that I have specified in the GitHub Pages settings is removed, causing the docs to be unreachable from that domain. 

I have the following in `settings.ini`: 
```
doc_host = <my-custom-domain>
doc_baseurl = /
host = github
```

I also have a `CNAME` file containing the domain at the root of my project.

nbdev 2.2.10
python 3.10.6

**Comment by jph00** [comment]
There's not enough info for me to help with your issue, unfortunately. nbdev and quarto both handle CNAME correctly, so there's something about your particular setup that's causing this problem. Perhaps your notebooks are in a subfolder of your repo and you have nbs_path in settings.ini, but don't have CNAME in that path?

**Comment by rossheat** [comment]
Adding CNAME to my nbs directory fixed the issue, thank you. Is that modification documented?

**Comment by jph00** [comment]
Great. The general rule is: your `nbs_path` is the path to your rendered website. So everything for your website needs to be in there.

On reflection, I'm not sure we've actually written that down anywhere!...

**Comment by jbwhit** [comment]
I came across this same problem. When I put my custom URL in the settings, GitHub put a CNAME for me at the top level of the repo. Putting another one in the `nbs` folder fixed this issue for me. I wrote a quick writeup here: https://jonathanwhitmore.com/posts/2024-07-11-cname-github-pages/
