### ISSUE TITLE
setting clear_all=True in settings.ini is not respected

### ISSUE THREAD

**Issue by mikedewar** [fastai/nbdev#1041]
First of all, thanks so much for nbdev! I'm very excited to use it to improve our jupyter notebook practice with git. And apologies if the following isn't a bug and is just me misunderstanding something!

When I set 

`clear_all=True`

in settings.ini I'm expecting all the output in my notebook to be removed upon saving the notebook. When I can get it working this is going to be incredibly useful as my  team and I work in a very regulated space, and this will be a fantastic safety net to help us avoid committing data we're not supposed to via notebook output. 

The hook in general is working, and my git diffs are doing great. 

The problem is that the output's still there. So for example, after saving I still have this in the json of one of my cells:

```
{
   "cell_type": "code",
   "execution_count": null,
   "id": "2134439f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 2 3\n"
     ]
    }
   ],
   "source": [
    "print(a,b,c)"
   ]
  },
```
 instead of `"outputs": []` as expected. 

Having a dig in I wondered maybe if something was missing from the 16th cell of the `clean` notebook where `_nbdev_clean` is defined? That at least seems to be where the other configs seem to be gathered from. 

Again, apologies if I'm missing something or messing something up. Any help would be appreciated!

**Comment by jph00** [comment]
cc @seeM

**Comment by jph00** [comment]
Should be fixed in master @mikedewar - we should be doing a release in the next few days if you'd rather avoid installing a prerelease.
