### ISSUE TITLE
Latest release breaks command `#hide_input` 

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#105]
Before `0.2.14` the comment `#hide_input` would hide input only

Now, with release `0.2.14` the comment `#hide_input` hides **BOTH** the input and the output.  

I believe this is a bug?  Or has this functionality been changed?  @sgugger 

Thank you!

**Comment by hamelsmu** [comment]
P.S. this looks like the breaking commit 49d87156bf0bc94051e52a60bbc17562dd290cd7

I would make a PR to fix, but I'm not 100% sure regarding the intended use cases that regex is supposed to cover.

**Comment by sgugger** [comment]
I know what the problem is, will fix once the kids give me a break ;)

**Comment by sgugger** [comment]
Should be fixed and I added a test. Can you confirm the problem is solved? Then I'll cut a new release.

**Comment by hamelsmu** [comment]
Yeah give me  a couple of hours, things are really crazy in my house 🙇

**Comment by hamelsmu** [comment]
@sgugger I have tested this and you can safely cut a new release now.  🙇  HOWEVER, I have noticed that the versions in pypi and this repo are not aligned.  

For example the [highest version in this repo is `0.2.15`](https://github.com/fastai/nbdev/commit/84e4cd3b32cc04c76fdb5281f1671cd4602a6e0a) however the [same release on pypi is on `0.2.14`](https://pypi.org/project/nbdev/#history), so version numbers may be mismatched?  

P.S. I'm happy to assist with automation around this with GitHub Actions and releases if this could be useful.

**Comment by sgugger** [comment]
Yes the version on GitHub is always one more than pypi: that's because master is the new version development.

**Comment by hamelsmu** [comment]
Ahhh makes sense

**Comment by sgugger** [comment]
Release done :)

**Comment by dsm-72** [comment]
Im still struggling with this on `v2` is this just `#| hide_input` (tried this), `#hide_input` (tried this first, failed to hide it), or `#|echo: false`? they all yield the input...
