### ISSUE TITLE
Inline images aren't being displayed on nbdev.fast.ai

### ISSUE THREAD

**Issue by danielpcox** [fastai/nbdev#106]
I notice that some images aren't being correctly displayed, at least on the front page of nbdev.fast.ai:

![image](https://user-images.githubusercontent.com/56411/77087502-96f9e280-69d9-11ea-9ef1-7fc6b9f61de7.png)

**Comment by sgugger** [comment]
I have no idea why it's now happening. @hamelsmu so you think there is anything we did for fastpages that could have changed how those {% include image.html ...} work?

**Comment by hamelsmu** [comment]
What page are we seeing this on?  

![image](https://user-images.githubusercontent.com/1483922/77203676-35577800-6aae-11ea-8dc6-abad51fd57ba.png)

Is this the sidebar?  That shows up for me ... is it something else that isn't rendering?

**Comment by sgugger** [comment]
No, not the sidebar, the block with {% include image.html ...} should be rendered as an image (and it used to work).

**Comment by hamelsmu** [comment]
Oh I see it now!  Yes this probably has something to do with escaping liquid with raw tags.  Taking a look

**Comment by hamelsmu** [comment]
I opened two separate PRs to fix this issue.  Thanks

**Comment by danielpcox** [comment]
Thanks guys!
