### ISSUE TITLE
Unable to generate correct source link in generated docs

### ISSUE THREAD

**Issue by Rahuketu86** [fastai/nbdev#1067]
I am using version 2.3.0 of nbdev and migrated a repository from nbdev1.  I am unable to get right link to source on github 

Please see below

<img width="960" alt="image" src="https://user-images.githubusercontent.com/786803/190317346-684c88cb-3d56-4c57-ba9d-5b7abe51c760.png">

Clicking on source takes you to following URL 

https://github.com/rahuketu86/aiking/tree/master/blob/master/aiking/core.py#L7

It would have worked if  instead of above it had generated URL as below 
https://github.com/rahuketu86/aiking/blob/master/aiking/core.py#L7

Am I missing something in migration? My config is listed in a prior issue. #998

**Comment by jph00** [comment]
Yes, update `git_url = https://github.com/%(user)s/%(lib_name)s/tree/%(branch)s/` to `git_url = https://github.com/%(user)s/%(lib_name)s/`, I think.
