### ISSUE TITLE
No such file or directory when building docs

### ISSUE THREAD

**Issue by jakebabbidge** [fastai/nbdev#1068]
Version: `nbdev==2.2.10`

When running `nbdev_docs` from the root of the nbdev project, everything seems to process smoothly, then there is an exception thrown from a rename operation. Most of the notebooks listed below have the `skip_showdoc: true` frontmatter as the first cell.

The only notebooks without `skip_showdoc: true` are `00_data.structures.misc` and `index.ipynb`.

Notebooks are placed in `<root>/nbs`.

Output log (modified for brevity):
```bash
pandoc -o README.md
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  output-file: index.html
  standalone: true
  default-image-extension: png

metadata
  skip_showdoc: true
  title: nbdevtest

Output created: _docs/README.md

[ 1/4] 00_utils.logging.ipynb
[ 2/4] 00_data.structures.misc.ipynb
[ 3/4] 00_data.structures.core.ipynb
[ 4/4] export_test.ipynb
[ 5/5] index.ipynb

ERROR: NotFound: No such file or directory (os error 2), rename '/opt/github/test_nbdev_v2/nbs/data.structures.core.html' -> '/opt/github/test_nbdev_v2/nbs/_docs/data.structures.core.html'
```

nbdev config:
```
...

### nbdev ###
nbs_path = nbs
doc_path = _docs
recursive = False
tst_flags = notest

...
```

nbdev v2 looks like a fantastic upgrade to v1 so we are keen to get it working. Any help would be appreciated.

Cheers

**Comment by jakebabbidge** [comment]
Updating to `nbdev==2.3.3` resolved this issue.

**Comment by michaelaye** [comment]
This is back with 2.3.12
