### ISSUE TITLE
Broken hyperlinks inside section summaries in fastpages _notebooks

### ISSUE THREAD

**Issue by travisdickey** [fastai/nbdev#107]
In fastpages, placing a hyperlink inside a section summary, that is, after a ">" breaks the link. The link works fine inside Jupyter Notebook, but when posted, the link address is changed.

I re-created the problem in the [Intro to fastpages](https://travisdickey.github.io/portfolio/fastpages/jupyter/2020/02/21/introducing-fastpages.html) notebook. In the first paragraph that begins, "We are pleased to announce . . .", converting that paragraph to a section summary breaks the [link to fastpages](https://travisdickey.github.io/portfolio/fastpages/jupyter/2020/02/21/%20//github.com/fastai/fastpages).

Initially I submitted this to fastpages, but per @hamelsmu, it's more an nbdev issue

cc 
@sgugger

**Comment by sgugger** [comment]
How does the address change exactly? Could you give us a reproducible example using nbdev only?

**Comment by hamelsmu** [comment]
@travisdickey a link to your notebook on GitHub would be helpful that causes this issue

**Comment by travisdickey** [comment]
In this example, the address changes from `https://github.com/fastai/fastpages` to `https://travisdickey.github.io/portfolio/fastpages/jupyter/2020/02/21/%20//github.com/fastai/fastpages`

Here is the link to [my repo](https://github.com/travisdickey/portfolio).

I'll see if I can reproduce the error in nbdev only. Thanks!

**Comment by hamelsmu** [comment]
I am looking at this and for some reason the URL after running notebook2html becomes this

`<a href="https: //github.com/fastai/fastpages">`. With a space between `https:` and `//` -> this causes Jekyll to think this is an image path.  

HTH narrowing down the error.  Somewhere in notebook2html there is something that does this.

**Comment by sgugger** [comment]
Oh I know what is doing this. Will push a fix this evening or during the weekend.

**Comment by sgugger** [comment]
Should be fixed now.
