### ISSUE TITLE
Export class to library but hide from documentation

### ISSUE THREAD

**Issue by gorkamunoz** [fastai/nbdev#1076]
Is it possible to use both hide and export directions such that my cell is exported to the libraries but is not shown in the documentation? 

My particular case: I am creating a class through multiple cells, e.g.:

Cell 1:
```
#| export 
class foo():
    def __init__():
        ''' Description of the class, which is shown in the docs.'''
```

Cell 2 (I want this one to be exported but hidden in the doc):
```
#| hide (?)
#| export (?)

class foo(foo):
    def func():
        ''' Description of the function, which I want to later show in the doc with show_doc(foo.func). '''
```

Combining both directives currently does not work, and in the library that cell shows again the class definition. I want to hide it and use later show_doc to show only the foo.func function I created. Is this possible? If not, is there a preferable way of defining classes over cells in nbdev?

**Comment by hamelsmu** [comment]
Would [exporti](https://nbdev.fast.ai/explanations/directives.html#exporti) work for you?
