### ISSUE TITLE
`nbdev_new` queries `branch` from GitHub

### ISSUE THREAD

**Issue by tylere** [fastai/nbdev#1080]
The default branch names used by GitHub and nbdev differ:

- GitHub [uses "main" as the default branch name for new repositories](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name)
- nbdev [uses "master" for the default branch name](https://github.com/fastai/nbdev/blob/master/nbdev/config.py#L41)
 
This causes nbdev commands to fail unless `settings.ini` is updated.

**Comment by hamelsmu** [comment]
we could do even better and query what the default branch is
