### ISSUE TITLE
GIF is not rendered correctly on HTML (nbdev==2.3.4)

### ISSUE THREAD

**Issue by hdocmsu** [fastai/nbdev#1088]
To display a test.gif on the notebook and on the rendered HTML I used  `display.HTML(<img src='./media/test.gif’>)`

with nbdev<2.3.4, nbdev_docs automatically creates the “media” directory (which contains test.gif) in the _docs folder and test.gif was rendered correctly on HTML.

However, when I upgraded to nbdev==2.3.4, nbdev_docs did not automatically create the “media” directory and test.gif is not shown in the HTML. (test.gif is displayed correctly on the notebook though). 

Is it possible to add the feature that automatically prepares the “media folder” as in nbdev<2.3.4?

**Comment by jph00** [comment]
Should be fixed in latest release.
