### ISSUE TITLE
Running `nbdev_migrate` while upgrading removes nbdev2 compatible directives

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/nbdev#1089]
While following the migration tutorial using the latest nbdev 2.3.5 release, running the `nbdev_migrate` command in the library root folder removed all directives which I had previously updated to be nbdev2 compatible. 

For example, existing `#|export` directives were completely removed and `#export` modified to `#|export`.

Expectation: properly formatted nbdev2 directives would be untouched and `nbdev_migrate` would only modify old style nbdev1 directives.

**Comment by hamelsmu** [comment]
Thanks, fixing this with #1096
