### ISSUE TITLE
`nbdev_new` pins on major+minor version of `nbdev-template`

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#1091]
Since every version of nbdev uses latest nbdev-template, we can't make any breaking changes in nbdev-template. I propose that `nbdev_new` pins the major+minor version of nbdev-template and that nbdev-template bumps minor version on breaking changes.

### Example

Implementing https://github.com/fastai/nbdev/issues/1083 would be simpler with this change.

Currently, we can implement it by updating the default in `_apply_defaults` and having `nbdev_new` move a known list of files (`*.ipynb`, `*.css`) to `cfg.nbs_path`.

We wouldn't have to keep that list in our code if we could move those files into a new sub-dir of `nbdev-template`, but that would break `nbdev_new` for prior versions of nbdev.

cc @hamelsmu @jph00

**Comment by hamelsmu** [comment]
Thanks, fixing this with #1096

**Comment by seeM** [comment]
Closing. https://github.com/fastai/nbdev/issues/1103 is a better solution to the underlying problem
