### ISSUE TITLE
nbdev_preview doesn't work with relative imports

### ISSUE THREAD

**Issue by gpucce** [fastai/nbdev#1098]
Hi, I really think I am missing something but I have been looking for a while and can't figure out a solution.

What is the correct way to export relative imports? However I do it if I try to call nbdev_preview it throws errors.

The situation is this:
```
my_folder/
├── 01_main.ipynb
├── 00_data_collection.ipynb
└── index.ipynb
```

in `00_core.ipynb`
I have the following cells:
```
- #| default_exp data_prepare
- #| export 
   class SomeClass():
       ...
```
and in `01_main.ipynb`
```
- #| default_exp __main__
- #| export
    from my_package.data_prepare import SomeClass
```

on calling `nbdev_preview` I get the error 
```
ModuleNotFoundError: No module named 'my_package'
```

**Comment by deven367** [comment]
Did you do a `pip install -e .` ?

**Comment by gpucce** [comment]
That was it thanks!
