### ISSUE TITLE
Escape LaTeX math with Liquid "raw" tags?

### ISSUE THREAD

**Issue by drscotthawley** [fastai/nbdev#110]
This is a Feature Request.

At the request of @hamelsmu in PR https://github.com/github/covid19-dashboard/pull/89, I'm opening this Issue to see if there could be automatic support for LaTeX equations in `nbdev` such that they don't generate conflicts with Liquid (for Fastpages) later.

Could you make it so that LaTeX equations (in text cells) such as 
```
$$ ... $$
```
gets automatically replaced with

```
{{% raw %}}
$$ ... $$
{{% endraw %}}
```
? 

Not sure if this would introduce problems elsewhere.  However, it would help with Fastpages supporting seeming 'innocuous' math equations (pun intended) such as in this covid-19 dashboard notebook https://github.com/github/covid19-dashboard/pull/89

Perhaps some command line switch like `--liquid` could be used to let `nbdev` know that its output is intended for use with Liquid.

**Comment by sgugger** [comment]
Added. Hope it will be enough to solve your issue.
