### ISSUE TITLE
Question: Captions for local image files just like urls ?

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#111]
With nbdev, you can include captions in images like this:

```
![](https://www.fast.ai/images/fastai_paper/show_batch.png "My Caption")
```

However, when the link is a local file, instead of a url this is not picked up by nbdev.  For example, 

`![](my_icons/fastai_logo.png "hello")`  

is not handled the same way - this results an in error when someone tries to do this.  @sgugger  I believe perhaps we should make an ammendment to the `_img2jkl` function:  

https://github.com/fastai/nbdev/blob/9f572b27314d27f2862fbfc0c0a8321c13a94315/nbdev/export2html.py#L125-L129

However, I am not completely sure that is as easy as changing this function.  We might have to also (1) copy the image (2) change the relative path to the copied location.  Please let me know your thoughts.

The related issue on fatpages: https://github.com/fastai/fastpages/issues/225 

cc:@noklam

**Comment by noklam** [comment]
Thx @hamelsmu I just saw the notification and saw you have already opened the issue.

**Comment by sgugger** [comment]
Should be fixed now. I made sure it works the same way as external images.

**Comment by hamelsmu** [comment]
Wow that was fast.  You close issues like magic on this repo.  I don’t know how you do it - starting to wonder if you are an artificial intelligence😝

**Comment by sgugger** [comment]
I am only every happy when the number of issues and PRs is 0 ;)
