### ISSUE TITLE
When notebooks are in the root, assets are not being copied over for site rendering

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#1114]
If someone has notebooks in the root, and there is a folder with images, this does not get copied into `_proc` which causes broken links on site rendering.  

This has been [demonstrated here](https://forums.fast.ai/t/nbdev-v2-launched/97821/140)

**Comment by jph00** [comment]
Looks like it should be solved by setting `recursive=False` in `settings.ini`

**Comment by thigm85** [comment]
When I set `recursive=True` as suggested, it seems that nbdev does something else besides including subfolders in notebook globs. For example, I think it runs cells that are explicitly marked not to be evaluated. My impression is that it ignores `#| eval: false` and 
```
skip_showdoc: true
skip_exec: true
```

**Comment by jph00** [comment]
@thigm85 if you can provide a reproducible case showing that, could you please open a new issue with the details? (We use those directives a lot in our libs and haven't seen that problem occur.)

**Comment by thigm85** [comment]
Yes, I will try to recreate the issue with a minimal example and open another issue if necessary.
