### ISSUE TITLE
Organize notebooks in subfolders

### ISSUE THREAD

**Issue by gorkamunoz** [fastai/nbdev#1118]
I am having troubles when organizing my nbdev repo with subfolders as it is done in the nbdev repo. To give an example, my aim is to have something like:

- nbs:
     - getting_started.ipynb
     -  _quarto.yml (customized)
     - nbdev.yml
     - library_nbs:
          - nb1.ipynb
          - nb2.ipynb
     - tutorial_nbs:
          -  tut1.ipynb
          - tut2.ipynb

I am having trouble with several things:

1.  If I set in settings.ini `source_nbs = nbs` , then when generating the library using `nbdev.export` from the notebooks in library_nbs,  nothing will be created. Moreover, if I try to create the documentations using `nbdev_preview`, only an html for the notebook in the folder nbs (i.e. `getting_started.ipynb`) is created. I cannot access the notebooks in the two subfolders, as nothing is created in the doc folder for these (no ipynb or htmls). Looking at how the nbdev repo is organized, it follows exactly this organization. Should I change some parameter so that the docs are created also for the subfolders?
2.  If I set in settings.ini `source_nbs = nbs/library_nbs` , then creating the library works fine, but for the documentation, nbdev bypasses the `_quarto.yml` file in nbs and creates a new one in `nbs/library_nbs` with default parameters.

How would you recommend me to proceed? I have gone through the nbdev repo and try to replicate as close as possible its organization and settings.ini with little success. Let me know if more info is needed!

**Comment by seeM** [comment]
Have you tried setting `recursive=True` in your settings file?

**Comment by gorkamunoz** [comment]
Thanks, this worked! Actually, reading the documentation I found about recursive, but the current description was not very helpful (mostly what notebook glow meant).

If I may, I have a related questions: is it possible to a access, for the documentation, a folder in the parent folder of _quarto.yml? For example, in the case above, having the tutorials in the parent folder and accessing then using ../tutorials_nbs/tut1.ipynb.

**Comment by seeM** [comment]
@gorkamunoz do you mean in the parent folder of `nbs_path` (in your settings)? I don't think it's possible, but you might want to double-check that with a quick test
