### ISSUE TITLE
nbdev + Azure: creating only markdown as docs

### ISSUE THREAD

**Issue by MJPansa** [fastai/nbdev#1131]
Hey everyone,
I have been looking into using nbdev on azure devops. For those unfamiliar with devops, AFAIK a feature like GH pages is not supported. There do exist the function to host a wiki inside the project that supports either custom markdown from an editor or reading markdown files from a repo. I know having a static html page would be way prettier and overall nicer but it doesnt seem possible without too many workarounds thus far. I've read a lot of the nbdev docs and was thinking simply switching from html to markdown as output should be fairly straight forward. I tried so far:

1. just normally use nbdev_docs and then use nbconvert on the _procs folder to convert to markdown
2. use nbdev_proc_nbs and then use quarto render --to markdown

First option generates docs fine, meaning show_doc results are properly formatted, but includes some extra unwanted cells:
![image](https://user-images.githubusercontent.com/51530201/192996767-a42021a0-049c-4f9a-959a-0c32db105872.png)

------------------------------------------------------------------------------------------------------------------------------------
second option creates a weird table at the top and also fails to create the correct table with function attributes:
![image](https://user-images.githubusercontent.com/51530201/192997470-acc09ebd-0938-41ad-a2a8-265b39ded9f9.png)

Is there any obvious way I am missing here or can someone give me any pointers? It might be also that using markdown restricts me further down the road in general functionality. I would really like to make this work and integrate it into my company workflows. So if theres no solution that would already work out of the box I would be happy about any pointers where you would see the best entrypoint for me to integrate this kind of functionality. It shouldn't just end up being a quick fix for me which might break later down the road. I imagine it might be useful as an addition to the library itself. Thank you already in advance. I am loving everything about this library so far :)

Also if there is a better place to ask this let me know. I've mostly been a user&lurker of open-source/communities than a contributor, but I am really excited about this project!

**Comment by hamelsmu** [comment]
Is your goal to host docs on Azure?  Instead of trying to host things on a wiki why don't you try this

1. Read this section about [deploying docs on other platforms](https://nbdev.fast.ai/explanations/docs.html#deploying-your-docs-on-other-platforms)
2. Host the resulting static site [on blob storage](https://nbdev.fast.ai/explanations/docs.html#deploying-your-docs-on-other-platforms) or another hosting solution
