### ISSUE TITLE
Glob pattern does not work with nbdev_clean under Windows

### ISSUE THREAD

**Issue by MarcosCobena** [fastai/nbdev#1138]
Steps:
1. within a PowerShell terminal (or a command prompt one), navigate to a folder which contains another folder with notebooks inside
2. `nbdev_clean --fname .\foo\*.ipynb --clear_all` (fname would turn foo/*.ipynb for the command prompt)

Expected: every notebook under foo to be cleaned.

Actually: nothing happens, nor any output is displayed.

Environment: Windows 11, Anaconda, nbdev 2.3.7

Thank you in advance!

**Comment by deven-gqc** [comment]
![image](https://user-images.githubusercontent.com/86305049/193319524-ba485742-cd0f-40c5-b6ad-35974e250035.png)

**Comment by hamelsmu** [comment]
Correct. You need to use this under WSL.   I'll close this issue for now
