### ISSUE TITLE
Images in index.ipynb causing deployments issues

### ISSUE THREAD

**Issue by KGrewal1** [fastai/nbdev#1140]
Images in the index seem to cause the error
 File exists: '/home/runner/work/hypersheets/hypersheets/index_files'

when running Deploy to GitHub Pages

**Comment by nueshym** [comment]
Maybe your issue is the same as mine fastai/nbdev#1106 if the error looks like:
```
FileExistsError: [Errno 17] File exists: '<abs_path_to_root>/index_files'
```
