### ISSUE TITLE
Inconsistency between `nbdev_preview` and `quarto preview`

### ISSUE THREAD

**Issue by fredguth** [fastai/nbdev#1141]
This problem took me a while to perceive that is `nbdev`-only and not happening in `quarto`.

Problem: `nbdev_preview` is inconsistent with what goes to production. In `nbdev_preview` margin images are full size, while in production they are in the margin width.  This problem does not happen in `quarto preview`.
- how it appears in `nbdev_preview`: https://share.getcloudapp.com/d5unNJWQ.  (image in the margin is full sized)
- how it appears in production: https://fredguth.github.io/ffc/blog/posts/dissertation/ai.html#fig-ars_magna_disc.  (image in the margin is margin-sized)
- nbdev project repo: https://github.com/fredguth/ffc

I initially thought it was a problem with my understanding of quarto. And tried to figure it out in that project: https://github.com/quarto-dev/quarto-cli/discussions/2673#discussioncomment-3778005

But I created a minimum working example `quarto project` and the problem does not happen there. Here is the repo of the mwe:
- https://github.com/fredguth/test_nbdev_quarto

In the `test_nbdev_quarto` repo, I reproduced the `ffc` _quarto.yml.  When you open intro.html in `quarto preview` the images are in the expected margin size.

**Comment by hamelsmu** [comment]
`nbdev_preview` is showing full-size image margins, here is what it looks like locally

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1483922/193518328-4ee7aef2-7fbf-4cab-b5a0-8880b82bbbcd.png">

Here is [what it looks like in production](https://incomparable-gumption-18bf23.netlify.app/blog/posts/dissertation/ai.html)

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/1483922/193518791-e79c7955-3757-4235-aa16-7ba28019e0e2.png">

The margin images look the same to me?

**Comment by hamelsmu** [comment]
Can you make sure you are using the latest version of nbdev from github and the latest pre-release of quarto?

- `pip install -U git+https://github.com/fastai/nbdev.git`
- https://quarto.org/docs/download/prerelease.html

**Comment by fredguth** [comment]
`pip install -U git+https://github.com/fastai/nbdev.git``
worked

My previously installed version was just `pip install nbdev`

Thanks
