### ISSUE TITLE
Issues migrating from nbdev1 to nbdev2

### ISSUE THREAD

**Issue by seanyboi** [fastai/nbdev#1142]
Hi,

I have gone through the tutorial of migrating from nbdev1 to nbdev2 (https://nbdev.fast.ai/migrating.html) however when I commit, no new `gh-pages` branch is created for my docs.

I am doing the migration on a feature branch before merging into main. Is there supposed to be a step after removing the docs file where we add it back that was missed in the documentation? We remove them in this step https://nbdev.fast.ai/migrating.html#add-and-remove-files but never run any command to create them again?

This was the GitHub action running: https://github.com/seanyboi/lockdowndates/actions/runs/3170247914
And this is the feature branch I am doing the migration on: https://github.com/seanyboi/lockdowndates/tree/8-migrate-to-nbdev-2

I'm at a bit of a loss so any help would really be appreciated!

Thanks :)

**Comment by hamelsmu** [comment]
You have to merge the commit for things to take effect, note the action is only triggered on either `main` or `master`

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1483922/193513292-eb8ac839-f19e-4e16-9f40-59e120b5bb41.png">
