### ISSUE TITLE
async functions not added to _all_

### ISSUE THREAD

**Issue by dragonflowerai** [fastai/nbdev#115]
Hi,

I am using a lot of async functions, and they do not get added to `__all__`

I think the regex you are using to find functions needs to be altered. I am not familiar with the code, so not doing a pull request on this one

**Comment by sgugger** [comment]
Should be fixed now.

**Comment by dragonflowerai** [comment]
Thanks!

Marco Cerutti | Co-Founder

 

Email:marcoc@dragonflower.ai


This message contains confidential information and is intended only for reply@reply.github.com. 
Please click here for the full email disclaimer, privacy statement and our financial services provider details.
