### ISSUE TITLE
code-fold doesn't work with export

### ISSUE THREAD

**Issue by johnowhitaker** [fastai/nbdev#1156]
Given a cell that defines a class and has the following directives:
```
#|code-fold: true
#|export
```
I'd expect to see the 'code >' widget with the option to show the code, and then the showdoc output if the notebook doesn't have `skip_showdoc: true` set. Instead, the code is completely hidden and only the doc is shown (or absolutely nothing when skip_showdoc is true).

It's not a big deal since I can use `#|exports` which shows the code all the time (just a bit messy) or showdoc which links to the source (just an extra click / page change) to get close to the desired behaviour, but it does seem like the current behaviour would be unexpected given the expectations for the code-fold directive.

**Comment by seeM** [comment]
Have you tried this combination?

```
#|code-fold: true
#|exports
```

Trying that locally with nbdev @ master and quarto 1.2.215 (pre-release) gives me this output, which seems like what you're after:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/559360/196344434-1845d886-4e79-4bd6-af16-cd19eae5b63b.png">

**Comment by johnowhitaker** [comment]
That works! I'd tried lots of other combos but missed that one. Thanks :) Marking as closed.
