### ISSUE TITLE
The description failed to render, when running "make pypi"

### ISSUE THREAD

**Issue by jonilaserson** [fastai/nbdev#116]
I followed the instructions and tried to use "make pypi" to turn my notebooks and library into a package. I get the following error:
```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

My setup.py has 
```
setuptools.setup(
    ...
    long_description = open('README.md').read(),
    long_description_content_type = 'text/markdown',
    ...
)
```
Where  could the problem be?

**Comment by theccalderon** [comment]
Do you mind sharing your repo so the contents of the `README.md` file can be checked?

**Comment by sgugger** [comment]
It means your `README.md` is not valid Markdown, from what I can see of the error message. You should inspect it and check it's all right. Please use the [forum](https://forums.fast.ai/c/fastai-users/nbdev/48) to debug as it's where the wider community is.

**Comment by jonilaserson** [comment]
My README.md was auto-generated.  I'll ask in the forum.

**Comment by jonilaserson** [comment]
I can't seem to be able to generate a new issue in the forum...  I get "You are not permitted to view the requested resource" as I'm trying to post a new topic.

I followed the instructions of nbdev and tried to use "make pypi" to turn my notebooks and library into a package. I get the following error:
    HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. 
    See https://pypi.org/help/#description-content-type for more information. for url: 
    https://upload.pypi.org/legacy/

My setup.py has

    setuptools.setup(
        ...
        long_description = open('README.md').read(),
        long_description_content_type = 'text/markdown',
        ...
    )

Anyway, you can see my repo in https://github.com/jonilaserson/curation_magic

**Comment by jonilaserson** [comment]
SOLVED
had to upgrade some packages:
```
pip install -U twine wheel setuptools
```
Explained here: https://github.com/pypa/warehouse/issues/5890#issuecomment-494868157
