### ISSUE TITLE
Allow user to specify `settings.ini` system location

### ISSUE THREAD

**Issue by dleen** [fastai/nbdev#1160]
nbdev searches up from the current directory for `settings.ini`. It also uses the `XDG_CONFIG_HOME` environment variable to locate "global" settings for a user. I have a use case where nbdev is installed in a Docker image and at runtime the user home directory is mounted to an external filesystem. This means that any settings in the home location are overwritten, so I need to use another location.

My proposal is to either add a system wide search location i.e. https://ipython.readthedocs.io/en/stable/config/intro.html#systemwide-configuration. This might be `/etc/nbdev` and `/usr/local/etc/nbdev`.

OR add an environment variable `NBDEVDIR` which points to the location where the global settings file can be found, similar to https://ipython.readthedocs.io/en/stable/config/intro.html#the-ipython-directory.

We could also solve #1125 at the same time.

Thoughts @seeM ?

**Comment by seeM** [comment]
We currently follow the [xdg specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which means that we try `/etc/xdg/nbdev/settings.ini` (`/etc/xdg` can be overridden by `XDG_CONFIG_DIRS`, which can also take a colon separated list) and then `~/.config/nbdev/settings.ini` (`~/.config` can be overridden by `XDG_CONFIG_HOME`). Would that solve your use-case?
