### ISSUE TITLE
Interesting breaking behavior when combining mermaid with fastprogress

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbdev#1171]
Nb is available here: https://gist.github.com/muellerzr/2b2384041115d941ca9ec3a9fcf0fd03

There's a very interesting bug with Quarto, fastprogress (I assume IPynb really?), and mermaid. If you have a notebook with these then the corresponding graph will actually just not exist, and when investigating the actual docs/html open I see:

```
Uncaught ReferenceError: mermaid is not defined
    <anonymous> http://localhost:3000/site_libs/quarto-diagram/mermaid-init.js:21
```

I have absolutely no idea why this is the case, but not good! cc @jph00 @seeM :) 

Full code for copy/paste purposes

In a markdown cell:
```
{mermaid}
flowchart TD
    A[Gather Data] --> B[Clean Data]
    B --> C[Build `DataLoaders`]
    C ==> D[Build a `Learner`]
    D ==> E[Train with modern best practices]
    E ==> F[Deploy]
    F --> A
    E ==> C
```

In a code cell (& execute it):
```python
from fastprogress.fastprogress import master_bar, progress_bar
mbar = master_bar(list(range(5)))

for i in mbar:
    mbar.write([f'Entry {i}', f'Value: {i+1}'], table=True)
```

**Comment by jjallaire** [comment]
Thanks for reporting this! It in indeed a Quarto issue and should be resolved with this commit: https://github.com/quarto-dev/quarto-cli/commit/216d2dd04ac5c879ce124863447d53c92ba744ef

This fix is available in v1.2.237 which you can download from: https://quarto.org/docs/download/prerelease.html

**Comment by muellerzr** [comment]
Thanks for the quick fix JJ! You're great!

**Comment by jph00** [comment]
Awesome @jjallaire ! :D
