### ISSUE TITLE
One-click Quarto blog starter

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#1173]
This isn't necessarily an nbdev issue e.g. it might involve creating its own repo. I'm tracking here for lack of a better place.

See [@muellerzr's full comment](https://forums.fast.ai/t/beginner-beginner-questions-that-dont-fit-elsewhere/96284/207) for more:

> One thing I loved with fastpages is I simply had to fork the repo, run one action, and then I could write a notebook separately and drag/drop into Github later whenever I wanted to post a new blog. If there’s a simple template repo that is setup for blogging where the user doesn’t need to type anything in and their blog just “works” that’d be wonderful.

**Comment by hamelsmu** [comment]
I think this is pretty straightforward https://quarto.org/docs/websites/website-blog.html
