### ISSUE TITLE
Documentation to upload to pypi seems to be incomplete

### ISSUE THREAD

**Issue by AdityaVarmaUddaraju** [fastai/nbdev#1181]
In the documentation of nbdev under the section Tutorials->End-to-End Walkthrough->Advanced functionality->Upload to Pypi

The line 
"To upload your project to pypi, just type nbdev_pypi in your project root directory. Once it’s complete, a link to" seems to be incomplete after "... a link to"

**Comment by seeM** [comment]
Fixed by #1196
