### ISSUE TITLE
`nbdev_install_quarto` may install and remove unrelated packages

### ISSUE THREAD

**Issue by sswam** [fastai/nbdev#1182]
I ran nbdev_install_quarto and was surprised to see dpkg installing several unrelated .deb packages, which happened to be in my cwd.

This code is responsible:
```
system(f'curl -LO {BASE_QUARTO_URL}quarto-linux-amd64.deb')
system('sudo dpkg -i *64.deb && rm *64.deb')
```

Fortuantely I pressed ctrl-C when I saw this happening, as the next command would have deleted those packages. It's not really cool for a helpful script to annihilate files with a broad glob from the user's current directory. In my case it would have been 3.1GB of Nvidia stuff.

Suggested fix:

`system('sudo dpkg -i quarto-linux-amd64.deb && rm quarto-linux-amd64.deb')`

**Comment by sswam** [comment]
Suggested fix:

> system('sudo dpkg -i quarto-linux-amd64.deb && rm quarto-linux-amd64.deb')

**Comment by sswam** [comment]
I searched for similar code, torchvision's `rm *` is not so dangerous:

`torchvision/ops/misc.py:        bias = b - rm * scale`

**Comment by seeM** [comment]
Wow, nice catch! Thanks for reporting this!
