### ISSUE TITLE
Integration with GitLab

### ISSUE THREAD

**Issue by tcapelle** [fastai/nbdev#120]
Hey @sgugger,
I am trying to integrate nbdev for using with gilab, and I am missing some minor details.
I would like to edit the `template.py` file to add support for GitLab.
Maybe it would be nice to have a variable for the config to setup if github or gitlab is used, so all links from the doc back to the git repo are not broken.
Maybe I am missing other things, could you give me more advice to make a PR?

**Comment by sgugger** [comment]
I'm not sure I can help without understanding that the actual problem is. For wrong links, does changing the git_url in settings.ini not enough?
I just need something more specific to be able to help.

**Comment by tcapelle** [comment]
I propose something like this:
- Add to the top of `settings.ini` a host flag. 
```
host: github
```
With this, you can know where you are deploying and take actions. 
Then the `template.py` can change the `topnav` to use `{host}{git_url}` instead of the hardcoded link to github.

**Comment by sgugger** [comment]
That seems reasonable. Do you mind making a PR with those changes?

**Comment by sgugger** [comment]
Fixed by #122
