### ISSUE TITLE
[BUG] nbdev_prepare on nbdev==2.3.8 using 'cat' on Windows.

### ISSUE THREAD

**Issue by yasirroni** [fastai/nbdev#1201]
Running `nbdev_prepare` on `nbdev==2.3.8` with Windows OS cause a long operation that cause the following warning / error:

```python
'cat' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by omlnaut** [comment]
nbdev does not run under windows, as stated in the readme file: 

> nbdev works on macOS, Linux, and most Unix-style operating systems. It works on Windows under WSL, but not under cmd or Powershell.

To use nbdev on windows, you have to set up WSL (version 1 or 2). I'm using nbdev like this, so I can assure you that this will work

**Comment by yasirroni** [comment]
Thanks for the clarification. But it was sad since the previous version can works in windows powershell.
