### ISSUE TITLE
export to a different module causes nbdev_build_docs to fail

### ISSUE THREAD

**Issue by pete88b** [fastai/nbdev#121]
Using nbdev 0.2.16, #export or #exports with module causes build docs to fail;
<pre>
$ nbdev_build_docs 
converting: /home/peter/github/decision_tree/10_data.ipynb
An error occurred while executing the following cell:
------------------
show_doc(export_from_data_to_core, default_cls_level=2)
------------------

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-1088855b24fe> in <module>
----> 1 show_doc(export_from_data_to_core, default_cls_level=2)

NameError: name 'export_from_data_to_core' is not defined
NameError: name 'export_from_data_to_core' is not defined

Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/decision_tree/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/home/peter/anaconda3/envs/decision_tree/lib/python3.7/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/home/peter/anaconda3/envs/decision_tree/lib/python3.7/site-packages/nbdev/cli.py", line 101, in nbdev_build_docs
    notebook2html(fname=fname, force_all=force_all, n_workers=n_workers)
  File "/home/peter/anaconda3/envs/decision_tree/lib/python3.7/site-packages/nbdev/export2html.py", line 450, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: Conversion failed on the following:
10_data.ipynb
</pre>

I've created a minimal project to demo: https://github.com/pete88b/decision_tree  (10_data.ipynb exports one function back to core)

**Comment by sgugger** [comment]
That is indeed a bug that will appear if you don't import those modules you export to in the notebook. Fix will require a bit of work, I hope to have some time to work on it this weekend.

**Comment by sgugger** [comment]
Ok, should be fixed now.
