### ISSUE TITLE
Hyperlinks in documentation don't work with ">" blocks

### ISSUE THREAD

**Issue by lgvaz** [fastai/nbdev#123]
Related with #107 , I updated to the latest version `0.2.17` and I'm getting the same error.

[Here](https://lgvaz.github.io/fastcook/) is an example.

This problem does not happen at the exported `README.md` file

---
**Note:**
Can I be running on a old version? I checked my version by doing:
```python
>>> import nbdev
>>> nbdev.__version__
'0.2.17'
```
But does this mean that this is the version used when I run `nbdev_build_docs`?
I think I'm running the right version, because I installed everything under the same conda virtual env, but I'm leaving this note because the problem was fixed in #107 and I'm still facing the issue, so I can be doing something wrong here xD

**Comment by sgugger** [comment]
No this is a different issues, it's not a block quote but the summary. I think this is a jekyll problem and not an nbdev problem.
If you find a way to have linked display in a jekyll summary, we can work of automatically converting them when reading those summaries and passing them along, but I have no idea what would be accepted (maybe something purely HTML?)

**Comment by lgvaz** [comment]
I found [this](https://forums.fast.ai/t/add-hyperlink-to-page-summary-nbdev/63206/4) issue on the forums, I followed your suggestions and used HTML syntax to make the hyperlink in my nb, it worked 😁

So what we can do is write a regex that captures any markdown style links in the summary and convert them to html links. We just need to be sure to use single quotes in the url instead of double quotes to not break everything 😅

**Comment by sgugger** [comment]
Let me know if you want to work on this one or if I should do it when I have time.

**Comment by lgvaz** [comment]
I want to give it a try, can you point me to the notebook I'll have to modify? I'm guessing is the `export2html`?

**Comment by sgugger** [comment]
Yes, it would be in that notebook. The summary is grabbed by `get_metadata`, so I guess it would be a natural place to add the conversion. I'd suggest doing the actual regex conversion in a private helper function that you would use there.
