### ISSUE TITLE
I started with a private repo -- doesn't seem I can deploy to github pages now

### ISSUE THREAD

**Issue by radekosmulski** [fastai/nbdev#1230]
[The docs](https://nbdev.fast.ai/tutorials/tutorial.html) mention that this is what I should be seeing under `settings/pages`

![image](https://user-images.githubusercontent.com/2444926/203278405-7e8e8ab0-23fb-4d20-b1c0-3cba012b3962.png)

But what I am seeing is the following:

![image](https://user-images.githubusercontent.com/2444926/203278731-323a6d17-30d3-48c2-a7ac-0d070a0355b8.png)

When I click on `configure` under `static HTML` this is what I see

![image](https://user-images.githubusercontent.com/2444926/203279022-5e3c236b-6836-41ed-965f-ab2b9c4a9e18.png)

Not sure if I am doing something wrong or maybe the interface has changed on github?

Thank you for your help!

**Comment by seeM** [comment]
Great to see you here Radek 😄 I think you might have to change the "Source -> GitHub Actions" to "Source -> Deploy from a branch"

**Comment by radekosmulski** [comment]
Thank you for a warm welcome, Wasim! 😄🙌 I have no clue what happened to my brain when trying to figure it out originally, but now that I followed your instructions obviously everything works!

Thank you, my friend! 🙏
