### ISSUE TITLE
nbdev_create_config doesnt add black_formatting option

### ISSUE THREAD

**Issue by saschahofmann** [fastai/nbdev#1231]
I am creating the config file via `nbdev_create_config --black_formatting True` but the option isn't added to the created _settings.ini_. I am a receiving a warning because I am using a private repo without having set the `GITHUB_TOKEN` but the same happens when I run the command in a completely empty repo.

On another note, it's not clear to me when the notebooks should be formatted? I hoped it would happen when saving the notebook but I couldnt trigger the black formatting after having added the setting manually?

**Comment by seeM** [comment]
The `black_formatting` option only applies to the exported Python files. The notebooks themselves don't get formatted.

**Comment by saschahofmann** [comment]
Ah gotcha! About the first part though: Am I wrong in assuming that this command `nbdev_create_config --black_formatting True` should generate a config file with the option set to true?

**Comment by hugetim** [comment]
Addressed by https://github.com/fastai/nbdev/commit/066a88ec1d8e6bf530692a4b754ac9bbf26ad2af
