### ISSUE TITLE
`nbdev_conda` can generate `meta.yaml` that `conda-build` can not parse

### ISSUE THREAD

**Issue by xl0** [fastai/nbdev#1232]
To be clear, I'm pretty sure the fault is on `conda-build`: https://github.com/conda/conda-build/issues/4654

Should `nbdev` should still do something about it?
I don't see an obvious solution to the problem, would someone more knowledgeable in `pyyaml` be able to step in?

**Comment by xl0** [comment]
I've got `pyyaml` to output block strings (| style), but conda still has a weird hiccup on the `[:` combo.

**Comment by xl0** [comment]
Heya.

I think a better way would be to switch `nbdev_conda` to use `grayskull`.

As it is, `nbdev_conda` generates recipes that are nowhere near passing the rather rigorous requirements of conda-forge. While `nbdev_conda` can generate packages for other conda channels, I feel that being able to generate packages for the conda-forge channel should be the target.

From bringing this up on Discord, I think @jph00 was open to moving `nbdev` to using `grayskull` to generate conda packages. @jph00, please confirm. @michaelaye , what do you think about it?

I've described the process of getting an nbdev package into conda-forge here: https://forums.fast.ai/t/getting-your-library-into-conda-forge/102860

**Comment by michaelaye** [comment]
Funnily enough, I designed my PR for `nbdev_conda` output to create the same requirements list as `grayskull` does, but there were indeed some other things different in `grayskull`'s meta.yaml.
If @jph00 was indeed agreeing to add another dependency like grayskull to nbdev, that's great, but I guess aligning the meta.yaml output to grayskull's output would also be possible.

**Comment by michaelaye** [comment]
switching to `grayskull` would solve #1233 as well.
