### ISSUE TITLE
doc strings for `@dataclass`

### ISSUE THREAD

**Issue by BirkhoffG** [fastai/nbdev#1234]
Documentations of arguments in `@dataclass` would be a great enhancement in my opinion. I don't think `nbdev` has fully support it yet.

For instance, 

```python
#| export
@dataclass
class Data:
    """My data"""
    X: np.ndarray # input
    y: np.ndarray # label
```

After `nbdev_preview`, it shows
![image](https://user-images.githubusercontent.com/26811230/204111152-95c70d1a-9832-48f1-8a9f-091be7c83811.png)

Unfortunately, it does not show Types and Details for `X` and `y` in a table, as it would for a normal python object.

Would it be possible to support this feature in `nbdev`? Is there a workaround for me to manually code this table?

**Comment by muellerzr** [comment]
You can try hacking the enum to get what you want, but there are very strong limits with this addressed in my article https://muellerzr.github.io/fastblog/2022/03/25/HackingTheEnum.html
