### ISSUE TITLE
Best practices question

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1251]
What is the best way to format an nbdev?

e.g. suppose I have a notebook `01_utils.ipynb`

Should I have a cell at the top like

```
import os, sys, json, numpy as np
import matplotlib.pyplot as plt
```

and then subsequent cells for the functions? one function per cell? or should I introduce the import statements just above the function that uses them?

**Comment by hamelsmu** [comment]
good question.  from the docs.  I would personally put all the imports in their own cell near the top, unless you have a really good reason to co-locate them with the function(s)

https://nbdev.fast.ai/explanations/docs.html#automatic-cell-execution

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1483922/211205662-4c9d2cdf-66b2-4081-b7d7-939957866af5.png">
