### ISSUE TITLE
Notebook has no `Title` in docs if sub-title was not specified

### ISSUE THREAD

**Issue by ddobrinskiy** [fastai/nbdev#127]
I'm running nbdev `0.2.17`

When building docs I noticed a  warning  `Warning: Some of your Notebooks use the same title`

After fiddling around, I assume that nbdev does not parse a notebook's title if it has no subtitle.

See first screenshot: notebooks have no subtitles, and they do not appear in the warning (Foo and Bar are just `Title`, use colors as guide) 

![no_subtitle](https://user-images.githubusercontent.com/29500178/78911375-e8543980-7a8e-11ea-950f-1309065a6faa.png)

Then add subsitles, and it all works like a charm.

![yes_subtitle](https://user-images.githubusercontent.com/29500178/78911383-e9856680-7a8e-11ea-9ab3-d2daf4b587a8.png)

So I suggest either making subtitles mandatory, or changing the warning text, or changing parsing rules.

p.s. sorry for reporting a bug instead of MR, `nbdev` is amazing and completely transforming how I work!

**Comment by sgugger** [comment]
Should be fixed now. Thanks for flagging!
