### ISSUE TITLE
[Extra End-To-End Walkthrough Info Needed] Workflows need read and write permissions for pages to work

### ISSUE THREAD

**Issue by gabrieli** [fastai/nbdev#1270]
The setting is under Settings >> Actions >> General >> Workflow permissions
Seems like the default is only Read permissions which leads to a "Permission denied to github-actions[bot]"

![Screenshot 2023-01-15 at 10 44 23](https://user-images.githubusercontent.com/2760516/212534506-3ff486c7-5eef-4512-ba77-2038d8b55712.png)

**Comment by tylere** [comment]
Relevant discussion: https://forums.fast.ai/t/unable-to-create-simple-gh-pages-output-with-nbdev-hello-world/103306

**Comment by hamelsmu** [comment]
Yeah I get a different error even after elevating permissions in the GitHub actions YAML file when it tries to enable your gh-pages branch 

So I think an additional step that's needed is to enable your gh-pages branch

**Comment by hamelsmu** [comment]
Closed via #1272
