### ISSUE TITLE
Illegal Space `0xa0` Causes nbdev_export to Fail

### ISSUE THREAD

**Issue by JiaxiangBU** [fastai/nbdev#1284]
I'm having an issue with the `nbdev_export` function failing due to an illegal space (`0xa0`) in
below.

To maximize the chances of my issue being fixed, I've created a minimal reproducible example in
contains the minimal amount of code needed to reproduce the error.

Here is the minimal reproducible example https://github.com/JiaxiangBU/nbdev-demo-230204

Here is the encoding error information using `nbdev_export`

```python
$ nbdev_export 
Traceback (most recent call last):
  File "d:\installed\miniconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\installed\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\installed\miniconda\Scripts\nbdev_export.exe\__main__.py", line 7, in <module>
  File "d:\installed\miniconda\lib\site-packages\fastcore\script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "d:\installed\miniconda\lib\site-packages\nbdev\doclinks.py", line 137, in nbdev_export
    for f in files: nb_export(f)
  File "d:\installed\miniconda\lib\site-packages\nbdev\export.py", line 59, in nb_export
    mm.make(cells, all_cells, lib_path=lib_path)
  File "d:\installed\miniconda\lib\site-packages\nbdev\maker.py", line 210, in make
    write_cells(cells[last_future:], self.hdr, f)
  File "d:\installed\miniconda\lib\site-packages\nbdev\config.py", line 252, in write_cells
    if cell.source.strip(): file.write(f'\n\n{hdr} {cell.idx_+offset}\n{cell.source}')
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 574: illegal multibyte sequence
```

**Comment by deven367** [comment]
@JiaxiangBU I just tried it myself. It worked without a problem.

**Comment by xl0** [comment]
@JiaxiangBU , please try my fix https://github.com/xl0/nbdev/tree/win-utf8

I don't have Windows, but pretty sure this is caused by utf-8 handling in Python on Windows.

`pip install git+https://github.com/xl0/nbdev@win-utf8`

**Comment by deven367** [comment]
@xl0 @JiaxiangBU This is from the documentation. `nbdev` works on Windows but inside WSL.
![image](https://user-images.githubusercontent.com/31466137/216978959-e6660aaf-0361-4249-8bf2-2e0cb62b8fbc.png)

**Comment by JiaxiangBU** [comment]
> @xl0 @JiaxiangBU This is from the documentation. `nbdev` works on Windows but inside WSL. ![image](https://user-images.githubusercontent.com/31466137/216978959-e6660aaf-0361-4249-8bf2-2e0cb62b8fbc.png)

Thanks for your suggestion, when I build the internal package in WSL, it works for me on Windows after pip installation.

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU , please try my fix https://github.com/xl0/nbdev/tree/win-utf8
> 
> I don't have Windows, but pretty sure this is caused by utf-8 handling in Python on Windows.
> 
> `pip install git+https://github.com/xl0/nbdev@win-utf8`
> 
> FIY, settings.ini from your example has some empty fields and is not valid.
.
.Thanks, <0xa0> is really irrelevant, the problem is encoding.
