### ISSUE TITLE
Local Jekyll rendering incorrectly

### ISSUE THREAD

**Issue by noklam** [fastai/nbdev#129]
#Bug
Local server rendering incorrectly.
It can be noted as the local server address have an extra `/`. I am not sure if I should call it a bug, since it renders correctly when I push to GitHub, but if I want to check from my local server, I have to remove the baseURL `/`.

# Solution
Remove the ending `/`

_config.yml
```
sidebars: [home_sidebar]
permalink: pretty
baseurl: /
```

to 
```
sidebars: [home_sidebar]
permalink: pretty
baseurl: 
```

# Local server before removing `/`
![image](https://user-images.githubusercontent.com/18221871/79039069-4577f880-7c11-11ea-9c10-8896004170f1.png)

![image](https://user-images.githubusercontent.com/18221871/79039073-4ad54300-7c11-11ea-93f6-eac5151f7fdc.png)

**Comment by sgugger** [comment]
Fixed by #130
