### ISSUE TITLE
nbdev.export.relative_import does not convert all possible import syntax

### ISSUE THREAD

**Issue by ddobrinskiy** [fastai/nbdev#13]
https://github.com/fastai/nbdev/blob/242331c4f05ce6e275dcbacaea7915545e29bbd5/nbdev/export.py#L182

Given this cell

```python
# export

import my_package.uploader

import my_package.utils as u

from my_package.test import *
```
**Expected behavior:** converts to  

```python
import .uploader

import .utils as u

from .test import *
```

**Observed behavior:** converts to 

```python
import my_package.uploader

import my_package.utils as u

from .test import *
```

**Comment by sgugger** [comment]
Good catch! Since we only use the last syntax, we didn't think to include the first. Should be fixed now.

**Comment by quocpeyrot** [comment]
I'm getting a syntax error with the form "import .utils as u"

from the documentation it seems this is indeed illegal:
https://docs.python.org/3/reference/import.html

`Absolute imports may use either the import <> or from <> import <> syntax, but relative imports may only use the second form;`

from that documentation, it seems relative import should only be used with the form `from [...] import [...]`

**Comment by sgugger** [comment]
It would be good to document this, if you want to suggest a PR in that direction.

**Comment by quocpeyrot** [comment]
I'm not sure I understand what you're asking.

From what I can tell from the documentation (and the fact that I'm getting an SyntaxError with Python 3.7), the request from this issue was bogus, and should be reverted?

It doesn't seem to work with Python 3.7, and the documentation from 3.8.1 linked above tells the same.

**Comment by sgugger** [comment]
The first one is still useful (a simple import lib_name.module should be changed to import .module). The second one doesn't work indeed, so it should be documented (in this case, since it doesn't work, we don't really care about the conversion or am I missing something?).

**Comment by quocpeyrot** [comment]
I'm confused, are you saying that `import .module` is valid?
It doesn't seem to be working for me either (and the documentation doesnt tell it either)

(and yes, I think those cases should just be ignored and not converted)

> % python
> Python 3.7.5 (default, Oct 25 2019, 10:52:18)
> [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import .foo
>   File "<stdin>", line 1
>     import .foo
>            ^
> SyntaxError: invalid syntax
> >>> import foo
> >>> foo.foo()
> 'foo'
> >>>
>

**Comment by sgugger** [comment]
Done in [this commit](https://github.com/fastai/nbdev/commit/051df1d0c61d36f42c814a85e3f91dbb81037911).

**Comment by quocpeyrot** [comment]
is the assert forbidding `import lib_name.module`? I haven't tested your commit, but the regexp seems to match for it? (sorry if I am misreading the commit)

`import lib_name.module` is valid as is (absolute import, using the full lib_name as a prefix), and should therefore be allowed, *but* it should not be replaced with `import .module` (which isn't valid)

**Comment by sgugger** [comment]
I see your point. Sorry it's taking me a while to understand what you mean since I never use those imports for submodules.
So yes, in that case we just need to remove the test entirely.

**Comment by ddobrinskiy** [comment]
Ahh, my bad. I used invalid syntax in issue body. Sorry for misleading.

All works for me now, thanks for the quick fix!
