### ISSUE TITLE
Missing release on github vs conda channel

### ISSUE THREAD

**Issue by thisiswhereitype** [fastai/nbdev#1316]
At the conda [channels listing for nbdev](https://anaconda.org/fastai/nbdev/files) 2.3.12 has been released. However [github's releases](https://github.com/fastai/nbdev/releases) do not list 2.3.12.

**Comment by hugetim** [comment]
Since 2.3.12 is no longer the latest version, I recommend closing this issue.

But for reference, I believe this shows the changes between 2.3.11 and 2.3.12: https://github.com/fastai/nbdev/compare/2.3.11...744a52daaee1792e840262917f57fc4767d3b347
