### ISSUE TITLE
nbdev does not export imports to modules.

### ISSUE THREAD

**Issue by LinuxIsCool** [fastai/nbdev#1324]
If this is my jupyter:

```python
#| export
import pandas as pd
```
```python
#| export
def df():
    return pd.DataFrame()
```

Then after running `nbdev_export`, my module looks like:
```python
def df():
    return pd.DataFrame()
```

And when I try to import and use the function somewhere else:
```python
from package.module import df
a = df()
```

Then I get the error `NameError: name 'pd' is not defined`

**Comment by deven367** [comment]
You don't see 
```py
import pandas as pd
```
in the module file?

**Comment by LinuxIsCool** [comment]
No it's not there.

**Comment by deven367** [comment]
Can you make sure your nb looks like this? Also, if possible, can you share a small reproducible example?
```
#| default_exp module
```
```
#| export
import pandas as pd
```
```
def df():
    return pd.DataFrame()
```

**Comment by LinuxIsCool** [comment]
My bad. I had #| hide instead of #| export.
