### ISSUE TITLE
Problem with Bokeh outputs in README.md 

### ISSUE THREAD

**Issue by dbikard** [fastai/nbdev#1330]
Hi,
I'm developing a package that outputs Bokeh figures which cannot be rendered as markdown in the README.md 

See the repo here:
https://github.com/dbikard/genomenotebook

Is there a way to ensure that cells output from index.ipynb are not exported to the README.md but are still used to generate the docs?

Thanks!

**Comment by deven367** [comment]
You can use the directive `#| output: false` to hide the output of a particular cell. You can read more about other directives &rarr; [here ](https://nbdev.fast.ai/explanations/directives.html)

**Comment by dbikard** [comment]
Thanks for the tip. This works but is also then hides the output from the online documentation which is not what I want. Is there a way to hide the output in the README.md file but not on the website?

**Comment by dbikard** [comment]
As a work around I've removed these Bokeh plots from the index page and moved them to another notebook / page. It would still be nice if in future would control differentialy what happens in the README.md and in the homepage of the online docs.

**Comment by dbikard** [comment]
It is actually possible to use the Quarto conditional content to have sections of index.ipynb that will not be shown in the README.md file. See: https://quarto.org/docs/authoring/conditional.html

::: {.content-visible unless-format="markdown"}
This content will be shown in the documentation but not in the README.md file.
:::
