### ISSUE TITLE
How to add a GitHub rep in the dependency

### ISSUE THREAD

**Issue by btrspg** [fastai/nbdev#134]
Hi there, 

I have some packages on the GitHub, rather than in pypi. How could I add the dependences in settings.ini?

**Comment by sgugger** [comment]
I added a `dep_links` key in the settings.ini file (directly on [nbdev template](https://github.com/fastai/nbdev_template) so you should copy the settings and setup file from there). Just put all your links separated by space or new lines (with indentation).

**Comment by btrspg** [comment]
Thanks, but I found no difference between your link nbdev template and my folked one. But now I thought how could I solve it.
