### ISSUE TITLE
No sidebar on Safari with `nbdev_new` of a blank project

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1349]
# Provide a minimally reproducible example
- [repo](https://github.com/dsm-72/nbdev-new-no-sidebar)
- [docs](https://dsm-72.github.io/nbdev-new-no-sidebar/)

```shell
# git clone empty repo
$ cd empty-repo
$ nbdev_new

# update workflows to use python 3.10

$ git add .
$ git commit -m 'add everything and then update workflows for python 3.10'

$ cp nb/00_core.ipynb nb/01_another.ipynb
# update another to be a different module

$ nbdev_prepare
$ git add .; git commit -m 'add another module'; git push origin main

# update GitHub repo to allow actions to write
# update GitHub repo to use pages
```

**Comment by dsm-72** [comment]
additionally it would be nice to know the following:

- how to specify an alternative template for `nbdev_new` 
- how to specify arguments for `nbdev_conda` like `--build_args '-c conda-forge'` in a `nbdev_config` file

**Comment by deven-gqc** [comment]
Can you run `nbdev_prepare` and the push all the files as well? I see that the `sidebar.yml` file is missing.

**Comment by deven-gqc** [comment]
Ah, I see. Either you should run `nbdev_sidebar` or `nbdev_preview` which generates the `sidebar.yml` file for you,

**Comment by dsm-72** [comment]
@deven-gq 

```she'll
$ nbdev_sidebar
$ git add .; git commit -m 'add sidebar'; git push'
# wait on github actions
```

no sidebar

```shell
$ nbdev_preview
# opens up safari and I see two sidebars and a header
# ctrl-c
$ git status
# no changes to commit
```

no sidebar


```shell
$ nbdev_prepare
$ git status
# no changes to commit
```

no sidebar

**Comment by deven-gqc** [comment]
Works for me! https://deven-gqc.github.io/nbdev-new-no-sidebar/
Can you go in settings and make sure you are deploying from a branch?
![image](https://github.com/fastai/nbdev/assets/86305049/a834f1c5-52c6-4388-9075-2853fbd56837)

**Comment by deven-gqc** [comment]
Can you please check your settings insides `Pages` tab in the sidebar?

**Comment by dsm-72** [comment]
@deven-gqc  I see where I misclicked >.<

**Comment by deven-gqc** [comment]
No worries!
