### ISSUE TITLE
Does it matter that _all_ can't have line breaks?

### ISSUE THREAD

**Issue by pete88b** [fastai/nbdev#137]
If we use line breaks between the elements in _all_, they don't get added to __all__
See: https://github.com/pete88b/decision_tree/blob/master/60_all_test.ipynb
If this is intentional, I can update the docs - if not, I'd be happy to change the regex and test etc

while we're in that area: should _add2add be called _add2all?

**Comment by sgugger** [comment]
Yes `_add2add` should definitely be named `add2all` if you want to make that PR. 
As for the line break, tt's not intentional, it just never came up. If it's not too complicated to add, happy to support it, otherwise let's document it and encourage people to do separate `_all_` on separate cells.

**Comment by pete88b** [comment]
Nice one Sylvain; Please see https://github.com/fastai/nbdev/pull/140

I've left _all_ without multi-line support as this fits better with an idea i've had for an %nbdev_add2__all__ magic flag ...

**Comment by sgugger** [comment]
Ok, Closing this then and let's see what your idea is :)
