### ISSUE TITLE
[Question] Can I install nbdev in a virtual env with only ipykernel instead of jupyter?

### ISSUE THREAD

**Issue by Martin15135215** [fastai/nbdev#1371]
https://github.com/fastai/nbdev/blob/4af4d479c78880f4a18af4254b119f8af8b3a8a4/README.md?plain=1#L65-L66

I have installed Jupyter lab system-wide

for my project I do

```
pipenv install ipykernel
pipenv install nbdev
pipenv run ipykernel install --user --name=<KERNEL_NAME>
```

Or do I need to install for all my projects a local Jupyter lab instance?

```
pipenv install jupyterlab
pipenv install nbdev
```

**Comment by hugetim** [comment]
The first option should work fine.

**Comment by Martin15135215** [comment]
I didn't test it yet, however I will close this issue meanwhile. If I have further questions, I will reopen this issue or create a new issue.
