### ISSUE TITLE
UnboundLocalError: cannot access local variable '_TEMPLATE' where it is not associated with a value

### ISSUE THREAD

**Issue by stepetal** [fastai/nbdev#1412]
## Command to reproduce the error

Error occured at the moment of execution 'nbdev_new' command (https://nbdev.fast.ai/tutorials/tutorial.html#initialise-your-repo-with-nbdev) inside python venv with installed nbdev library.

## Detail description

Full error message looks like
`
Traceback (most recent call last):
  File "/home/alex/PythonProjects/nbdev_env/bin/nbdev_new", line 8, in <module>
    sys.exit(nbdev_new())
             ^^^^^^^^^^^
  File "/home/alex/PythonProjects/nbdev_env/lib/python3.12/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/PythonProjects/nbdev_env/lib/python3.12/site-packages/nbdev/cli.py", line 91, in nbdev_new
    _TEMPLATE = f'{_ORG_OR_USR}/{_TEMPLATE}'
                                 ^^^^^^^^^
UnboundLocalError: cannot access local variable '_TEMPLATE' where it is not associated with a value
`

![error_displayed_in_cmd](https://github.com/fastai/nbdev/assets/21188548/df9bb0ca-c0e7-4689-8c5d-6b549eb79fd0)

## OS and Python versions

OS: Ubuntu 24.04 LTS 
Python version: Python 3.12.3
nbdev version: nbdev 2.3.19

nbdev library was installed with help of pip:
pip 24.0 from /home/alex/PythonProjects/nbdev_env/lib/python3.12/site-packages/pip (python 3.12)

## Possible reason of the error

It is possible that the source of error is the incorrect argument to f - string.
https://github.com/fastai/nbdev/blob/master/nbs/api/13_cli.ipynb, function _nbdev_new_.

`
    _TEMPLATE = f'{_ORG_OR_USR}/{_TEMPLATE}'
`
In this statement variable _TEMPLATE is used before assignment

Probably this is misprint and '_REPOSITORY' should be used instead of '_TEMPLATE'

### How to fix locally

nbdev_new - initial command when creating project with nbdev, so it is not possible to use functionality of the library without it.
Steps to fix locally:

1. Create python venv and activate it.
2. Install nbdev and jupyter lab according to the tutorial mentioned above.
3. Get the source https://github.com/fastai/nbdev.git and go to created directory.
4. Replace '_TEMPLATE' with '_REPOSITORY' inside f'{_ORG_OR_USR}/{_TEMPLATE}' in the function _nbdev_new_ 
5. Execute command 'nbdev_export' to update exported py - files
6. Uninstall old nbdev library ( `pip uninstall nbdev`)
7. Install new nbdev library: `pip install .`
8. Go to project directory and execute `nbdev_new`

![nbdev_new_function](https://github.com/fastai/nbdev/assets/21188548/125bfbbf-d446-40be-85bc-2b964dd52c83)
![install_new_nbdev](https://github.com/fastai/nbdev/assets/21188548/81a862c1-2ac3-4d20-8a5f-8a869f1291be)
![results_of_local_fixing](https://github.com/fastai/nbdev/assets/21188548/3ce86579-7813-41a5-851f-68e567f46236)

**Comment by deven367** [comment]
Hi @stepetal, would you like to create a PR for this?

**Comment by stepetal** [comment]
Hi!
Thanks. Yes, I would. I will include changes mentioned in issue
