### ISSUE TITLE
[Question] If I use clicks package, can I still use console_scripts in settings.ini?

### ISSUE THREAD

**Issue by ajing** [fastai/nbdev#145]
I am more familiar with click and I have something like:

```python
@click.group()
def cli():
    pass


@cli.command()
@click.argument('config', type=click.File('r'))
def run(config):
    pass
```

Can I still do `console_scripts=mycli:mypackage.cli:run` ?

**Comment by sgugger** [comment]
The console scripts are directly passed to the setup so there is no reason this shouldn't work. Please re-open if it does not.

(Also note we use the issues for bugs only and the [forum](https://forums.fast.ai/c/fastai-users/nbdev) to ask questions.)
