### ISSUE TITLE
[Question] GitLab template is missing (404). New location?

### ISSUE THREAD

**Issue by deepettas** [fastai/nbdev#146]
[The GitLab project template](https://gitlab.com/thomas.capelle/nbdev_template/generate) 404s. Is it hosted somewhere else?

**Comment by sgugger** [comment]
I don't use GitLab, so I can't check. You should ping @tcapelle  on the [forum](https://forums.fast.ai/), that's the most efficient way to solve your issue since he implemented that feature :)

**Comment by tcapelle** [comment]
https://gitlab.com/thomas.capelle/nbdev_template/
