### ISSUE TITLE
settings.ini changes in github actions causing build failures

### ISSUE THREAD

**Issue by evan-burke** [fastai/nbdev#147]
Hi,

I'm seeing Actions failures on the `Check if all notebooks are cleaned` step, though github desktop and github don't report any repo differences.

This appears to be due to changes to the `settings.ini` file that occur within github actions, which results in `git status` detecting the file as modified. Here's what I'm seeing:
- Comments and blank lines have been stripped
- Dynamically constructed values like `doc_baseurl = /%(lib_name)s/` have values replaced
- `host = github` has been added at the end

These changes happen on the `nbdev_read_nbs` step; the settings.ini file matches my local copy prior to that. Strange - at first glance, I don't see anything in nbdev_read_nbs that should be doing that. Maybe something happening on import?

Actions is using the latest 0.2.18.

**Comment by sgugger** [comment]
No, that test does not look at the settings.ini file, it fails if you have committed notebooks with extra metadata.
Normally `nbdev_clean_nbs` and committing will fix that problem for you.

**Comment by evan-burke** [comment]
Doesn't https://github.com/fastai/nbdev_template/blob/master/.github/workflows/main.yml#L22 look at the entire repo?

**Comment by sgugger** [comment]
Yes it checks you have a clean git status, it's nothing to do with the cleaning.

Maybe just update your settings.ini to the version updated by `nbdev_read_nbs`? There are new keys now required by nbdev but for backward compatibility, they are added when needed. So calling `nbdev_read_nbs` with the latest version of nbdev on your local repo should give you the proper settings.ini file to commit.

**Comment by evan-burke** [comment]
Ah, sounds good, I'll try that - thanks.

**Comment by evan-burke** [comment]
So running `nbdev_read_nbs` locally resolves the build error - thank you -  but I don't quite like that it removes comments from the local settings.ini. I'd prefer to have things like this retained for reference:
`# From 1-7: Planning Pre-Alpha Alpha Beta Production Mature Inactive`

It's not a big deal, but it affects the developer experience a little.

**Comment by sgugger** [comment]
Ah yes, saving the config would do that. I'll look at how we can avoid that.

**Comment by evan-burke** [comment]
Thanks, I appreciate it.
