### ISSUE TITLE
way to remove the autogenerated line at the top

### ISSUE THREAD

**Issue by prajjwal1** [fastai/nbdev#148]
Hi,

I wanted to know if there's any way to remove the first `#AUTOGENERATED! DO NOT EDIT` line at the top of all files with nbdev itself.

**Comment by sgugger** [comment]
No there is no option for that. I don't understand what you are saying in "with nbdev itself" could you clarify?

**Comment by prajjwal1** [comment]
I meant to say that I can write a script that removes auto-generated comments which nbdev by default writes. But that would be a bit of trouble, so that'd why I asked if there was some provision to turn it off from config or argument in nbdev.

**Comment by sgugger** [comment]
Like I said, there is none. Note that it will stop working with commands like `nbdev_update_lib`.

**Comment by prajjwal1** [comment]
I get it. I was trying to explain the motivation for why I asked as you asked to clarify. Thanks for the info.
