### ISSUE TITLE
settings.ini modified in github actions

### ISSUE THREAD

**Issue by bepuca** [fastai/nbdev#149]
I am working on a project using nbdev. It worked flawlessy so far but now the following problem is happening:

## Observed behavior
- When pushing a certain branch, github actions are triggered properly but breaks on `Check if all notebooks are cleaned` with the error message `git status is not clean`. Now, I added some more logging to try and see what exactly is not clean.
- It seems that the file `settings.ini` is modified when installing the library, leading to non-clean git status.
- Here are the logs on what exactly is changed:
```
diff --git a/settings.ini b/settings.ini
index
--- a/settings.ini
+++ b/settings.ini
@@ -1,5 +1,4 @@
 [DEFAULT]
-# All sections below are required unless otherwise specified
 lib_name = my_lib_name
 user = fastai
 description = my_description
@@ -12,42 +11,16 @@ version = 0.0.1
 min_python = 3.6
 audience = Developers
 language = English
-# Set to True if you want to create a more fancy sidebar.json than the default
 custom_sidebar = False
-# Add licenses and see current list in `setup.py`
 license = apache2
-# From 1-7: Planning Pre-Alpha Alpha Beta Production Mature Inactive
 status = 2
-
-# Optional. Same format as setuptools requirements
 requirements = numpy pandas matplotlib requests tqdm pyarrow joblib fastai torch xlrd hyperopt scikit-optimize
-# Optional. Same format as setuptools console_scripts
-# console_scripts = 
-
-###
-# You probably won't need to change anything under here,
-#   unless you have some special requirements
-###
-
-# Change to, e.g. "nbs", to put your notebooks in nbs dir instead of repo root
 nbs_path = nbs
 doc_path = docs
+doc_host = https://fastai.github.io
+doc_baseurl = /my_lib_name/
+git_url = https://github.com/fastai/my_lib_name/tree/master/
+lib_path = my_lib_name
+title = my_lib_name
+host = github
 
-# Anything shown as '%(...)s' is substituted with that setting automatically
-doc_host =  https://%(user)s.github.io
-doc_baseurl = /%(lib_name)s/
-git_url = https://github.com/%(user)s/%(lib_name)s/tree/%(branch)s/
-lib_path = %(lib_name)s
-title = %(lib_name)s
-
-#Optional advanced parameters
-#Monospace docstings: adds <pre> tags around the doc strings, preserving newlines/indentation.
-#monospace_docstrings = False
-#Test flags: introduce here the test flags you want to use separated by |
-#tst_flags = 
-#Custom sidebar: customize sidebar.json yourself for advanced sidebars (False/True)
-#custom_sidebar = 
-#Cell spacing: if you want cell blocks in code separated by more than one new line
-#cell_spacing = 
-#Custom jekyll styles: if you want more jekyll styles than tip/important/warning, set them here
-#jekyll_styles = note,warning,tip,important
```

## Expected behavior
- No error in this step.

## Additional context
- This is the first time it happens. It does not happen for any other branch we have or had in the past.
- I would say I have not changed anything related to all this, but I am not sure.

**Note**: Not sure if this a real issue with the library or I am doing something wrong. I would have posted this in the fastai forums but I could not find an nbdev category. If there is a place for this discussion there, I will happily move it.

**Comment by sgugger** [comment]
The most recent of nbdev needs additional fields in `settings.ini`. To avoid breaking compatibility, those are added to your config file if not present with default values. The problem is that GitHub actions install the new nbdev and you have an older one, resulting in a mismatch between those files.

To fix: 
1. save your old settings.ini just in case, 
2. upgrade nbdev, 
3. run something like `nbdev_read_nbs` in your repo, 
4. checkout the changes in `settings.ini` and either keep this one or add the new fields in your old settings.ini.

**Comment by bepuca** [comment]
Thank you very much, this solved the issue.

Maybe it would be helpful to add a suggestion on updating the library if this error pops up. Do you think it is a good idea? If so, I could do the PR.

**Comment by sgugger** [comment]
Sure, a helpful error message can always help.
