### ISSUE TITLE
supporting multiple paths for nbs_path?

### ISSUE THREAD

**Issue by deep-diver** [fastai/nbdev#15]
In my programming sense, the notebooks could be better organized when they are stored into different categories of directories.

Let me know about what your thoughts

**Comment by sgugger** [comment]
This is possible but will require you to adjust the commands (you can pass any glob expression in them). The base library will keep it simple though.

If you want to discuss the issue more, please use the dedicated [topic](https://forums.fast.ai/t/nbdev-discussion/59145/) on the forum as we keep issues for knwon bugs only. Thanks!
