### ISSUE TITLE
show_doc fails in JupyterLab

### ISSUE THREAD

**Issue by gkaissis** [fastai/nbdev#151]
For some strange reason the IN_NOTEBOOK check fails on JupyterLab even though the `__class__.__name__` is identical to the one in the code. It works fine in the legacy Notebook. 🤔

**Comment by sgugger** [comment]
I think this is linked to your setup as I just run `IN_NOTEBOOK` in jupyter lab and got back `True`.

**Comment by gkaissis** [comment]
![Screenshot 2020-05-10 at 16 28 27](https://user-images.githubusercontent.com/48105485/81502067-fe4a5980-92db-11ea-9e29-5ad12353b375.png)


I don't get it though: `IN_NOTEBOOK` returns `True` for me as well! At the same time, `show_doc` fails with `name Markdown is not defined` which in my eyes can only come from the import up above.

**Comment by sgugger** [comment]
Again, it's a problem from your setup somehow. I can execute `show_doc` without any problem on JupyterLab. Make sure your ipython is up to date.

**Comment by gkaissis** [comment]
Thanks Sylvain, I'll check it out.
