### ISSUE TITLE
show_doc and `# exports module` don't play nice

### ISSUE THREAD

**Issue by BlackHC** [fastai/nbdev#154]
Using nbdev  0.2.18.

I added a module to an #exports to route code somewhere else. Now `nbdev_build_docs` fails with 

```
An error occurred while executing the following cell:
------------------
show_doc(BayesianCNN, default_cls_level=2)
------------------
```

(which is a cell that is created by the html conversion code for the cell whose target module I've changed)

I hope this provides sufficient information to reproduce it.

(BayesianCNN is a class that I defined in that cell as example, and then I thought: maybe I should collect this model in its own module to avoid copy-pasting the code over my notebooks.)

Thanks,
 Andreas

**Comment by sgugger** [comment]
There is nothing we can do to help without:
1. seeing the whole stack trace
2. seeing the notebook that creates the problem.

We are not magicians :)

**Comment by BlackHC** [comment]
```
nbdev_build_lib
Converted 01_batchbald.ipynb.
Converted 02_joint_entropy_computation.ipynb.
Converted 03_consistent_mc_dropout.ipynb.
Converted 04_active_learning.ipynb.
Converted 05_repeated_mnist.ipynb.
Converted 06_example_experiment.ipynb.
Converted 07_black_box_training.ipynb.
Converted A1_some_models.ipynb.
Converted index.ipynb.
touch batchbald
nbdev_build_docs
converting: /home/blackhc/PycharmProjects/bald-ical/03_consistent_mc_dropout.ipynb
An error occurred while executing the following cell:
------------------
show_doc(BayesianCNN, default_cls_level=2)
------------------

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-0dff4c94e4b1> in <module>
----> 1 show_doc(BayesianCNN, default_cls_level=2)

NameError: name 'BayesianCNN' is not defined
NameError: name 'BayesianCNN' is not defined

Traceback (most recent call last):
  File "/home/blackhc/anaconda3/envs/active_learning/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File "/home/blackhc/anaconda3/envs/active_learning/lib/python3.7/site-packages/fastscript/core.py", line 73, in _f
    func(**args.__dict__)
  File "/home/blackhc/anaconda3/envs/active_learning/lib/python3.7/site-packages/nbdev/cli.py", line 101, in nbdev_build_docs
    notebook2html(fname=fname, force_all=force_all, n_workers=n_workers)
  File "/home/blackhc/anaconda3/envs/active_learning/lib/python3.7/site-packages/nbdev/export2html.py", line 522, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: Conversion failed on the following:
03_consistent_mc_dropout.ipynb
Makefile:13: recipe for target 'docs' failed
make: *** [docs] Error 1
```
That's all I got in the console.

I'll see if I can create a very basic repo to reproduce this. It seems like quite a generic bug.

PS: And wow that was quick reply & fast turn-around from your side 🔥

**Comment by sgugger** [comment]
Ok, the error would indicate `BayesianCNN` has not been exported properly. Double-check it's indeed present in the modules and that the module has been installed at least with a dev install so that python can find it.

**Comment by BlackHC** [comment]
Have a look at https://github.com/BlackHC/reproduce_nbdev_154/ (and the repo) which allows on to reproduce the issue. Rename `02_core.ipynb` to `00_core.ipynb` or vice-versa

It's the order of notebook. If you try to export to a notebook that is run "later" than the current notebook, `nbdev_build_lib` will silently fail to export the cells and `nbdev_build_docs` will crash.

(However, if that notebook is new and the module does not exist yet, `nbdev_build_lib` will fail with an error message about the module not existing yet.)

I think it's not clear that the order of notebook execution matters so much. At least the error messages might need improvement.

Furthermore, I wanted to use the feature to write some cells into an appendix for later re-use, which is not really possible this way? (Or is there a way to change the order of notebooks in the nav bar?)

**Comment by sgugger** [comment]
> It's the order of notebook. If you try to export to a notebook that is run "later" than the current notebook, nbdev_build_lib will silently fail to export.

Oh, that's not very nice, we should fix that. Yes the order of execution matters, especially for cells exported in other notebooks.

> Or is there a way to change the order of notebooks in the nav bar?

You can write your custom sidebar by setting the corresponding attribute to true in your settings.ini and editing the file sidebar.json in docs/ (see the fastai2 project for an example of custom sidebar.json)

**Comment by BlackHC** [comment]
I think having order requirements is reasonable. Obviously, if it was possible to be more flexible, that would be great, but otherwise catching this case with a good error message could go 80% of the way.

My user story is that I have the main notebooks and introduce an example model (that I keep reusing) in one of the notebooks to show how to plug things together. I wanted to export that model into an appendix notebook to reuse this later without having to copy & paste the code again.

**Comment by pete88b** [comment]
Think I have a fix for this https://github.com/fastai/nbdev/pull/165 - as long as your converting all nbs, you can export to a notebook that is run "later"

hope this helps (o:

**Comment by sgugger** [comment]
Yup, #165 should fix this.

**Comment by BlackHC** [comment]
Thank you!
