### ISSUE TITLE
Deal with horizontally overflowing cell output in GitHub Pages

### ISSUE THREAD

**Issue by mikhas** [fastai/nbdev#160]
I found it necessary to handle overflow behaviour [not just for links](https://github.com/fastai/nbdev/blob/e9a5b1f76677d09da239be640f1cb8d179994a31/docs/css/customstyles.css#L88-L104) but for output_html in general. Perhaps the default for `customstyles.css` could be like so:

~~~
.output_html {
    overflow-y: scroll;
}
~~~

Otherwise, the static github.io page can trivially break, also wrt. the sidebar menu.

**Comment by sgugger** [comment]
Doesn't sound like it would break anything to me. Would you mind suggesting a PR with that change?

**Comment by hamelsmu** [comment]
@mikhas can you provide a repo or example where the overflow occurs in an undesireable way?  That way will give me something I can try to fix rather than trying to fix a problem in the abstract.  Thanks for your help!
