### ISSUE TITLE
Show doc in Colab

### ISSUE THREAD

**Issue by mpariente** [fastai/nbdev#169]
First, thanks for the tools !

I tried to use show_docs in Colab and this is what I got printed
`<IPython.core.display.Markdown object>`, however it works on jupyter notebook.
Is this a known issue? Is there a workaround?

**Comment by sgugger** [comment]
I'm not sure it has been tested before. If they don't want to display Markdown, then it can't work, no. You can always pass `disp=False` that will return you the Markdown code, that you can then copy and paste in a cell.

Another possibility is that you have to trust the notebook before seeing those results interpreted (you have to do this in jupyter for instance).

**Comment by mpariente** [comment]
> I'm not sure it has been tested before. If they don't want to display Markdown, then it can't work, no. You can always pass `disp=False` that will return you the Markdown code, that you can then copy and paste in a cell.
> 

Thanks for your answer, that works somehow but there is some code which is not rendered correctly (both in Colab and jupyter), linebreaks (`\n` in the output) for example.
