### ISSUE TITLE
Links to source code in nbdev documentation point to wrong lines 

### ISSUE THREAD

**Issue by antonbabkin** [fastai/nbdev#172]
I've noticed it on this [documentation page](http://nbdev.fast.ai/export2html). For example, link to source for [`adapt_img_path`](http://nbdev.fast.ai/export2html/#adapt_img_path) points to [line 174](https://github.com/fastai/nbdev/tree/master/nbdev/export2html.py#L174), while the function code starts on line 182.

**Comment by sgugger** [comment]
This is probably because the docs have not been update in a while. Will run the script now.

**Comment by sgugger** [comment]
Yup, that fixed it.
