### ISSUE TITLE
The nbdev pip package seems incompatible with the jupyter conda package 

### ISSUE THREAD

**Issue by algal** [fastai/nbdev#18]
I am no expert on how conda and pip interact, so I'm not sure if this incompatibility is worth worrying about. But I thought I would mention it here in case someone else encounters it:

If I use conda to install only python, and then use pip to install `nbdev` (and thus pull in `jupyter` as a dependency), then it's fine:

```
conda create -n working
conda activate working
conda install -y python
pip install nbdev
# notebooks work fine
```

However, when I use conda to install `jupyter`, and then use pip to install `nbdev`, I get in invalid install:

```
conda create -n broken
conda activate broken
conda install -y jupyter
pip install nbdev
pip check
# => ipython 7.10.1 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you have prompt-toolkit 1.0.18
# and notebooks don't open properly
```

I am not sure what's producing the incompatible requirement for the low version of prompt-toolkit 1.0.18. It seems to becoming from the requirement of an older version of  jupyter-console 5.2.0, as opposed to the jupyter-console 6.0.0 .

**Comment by sgugger** [comment]
Do you keep the bug with a full update of conda (conda update conda)?

**Comment by sgugger** [comment]
I removed the dep to put it for testing only (since it's only necessary for the CI in github).
