### ISSUE TITLE
Multiple flags on a code block

### ISSUE THREAD

**Issue by h17** [fastai/nbdev#181]
Use case: currently, combining flags such as collapse and hide_input is not possible.  
One could write another flag collapse_hide_input combining the two but in the long-run if number of flags increase it is idea to be able to run multiple runs.  The two possible formats that come to mind is a big more compact and easy to use
#flag1 flag2 ... flagn
or perhaps easier to parse via re
#flag1
#flag2
...
#flagn

**Comment by pete88b** [comment]
The latest (not yet released to PIP) version of nbdev supports quite a few combinations of flags.

See https://github.com/pete88b/decision_tree/ for examples

[This notebook](https://github.com/pete88b/decision_tree/blob/master/50_test_doc.ipynb) and its corresponding [doc page](https://pete88b.github.io/decision_tree/test_doc/) have examples of
- hiding input and collapsing output (`#hide_input` \ `#collapse-output`)
- hiding cells that use test flags (`#hide` /  `#slow`)

and also shows a few things that are not supported yet
- you can collapse input or output _but not both_.

your example is one that will never be possible (o: `#collapse` is short for collapse input

If you need other combinations, please feel free to create PRs against https://github.com/pete88b/decision_tree/ to explain what you need
