### ISSUE TITLE
nbdev_template repo creation ci fail

### ISSUE THREAD

**Issue by Arcturus122** [fastai/nbdev#183]
Hi, 
when clicking on nbdev_template link from nbdev tutorial, I can Create a new repo  but then the ci pipeline start and fail automatically (without changing anything in the code)

`
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 backcall-0.2.0 bleach-3.1.5 decorator-4.4.2 defusedxml-0.6.0 entrypoints-0.3 fastscript-0.1.4 importlib-metadata-1.6.1 ipykernel-5.3.0 ipython-7.15.0 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.17.1 jinja2-2.11.2 jsonschema-3.2.0 jupyter-1.0.0 jupyter-client-6.1.3 jupyter-console-6.1.0 jupyter-core-4.6.3 mistune-0.8.4 nbconvert-5.6.1 nbdev-0.2.18 nbformat-5.0.7 notebook-6.0.3 packaging-20.4 pandocfilters-1.4.2 parso-0.7.0 pexpect-4.8.0 pickleshare-0.7.5 prometheus-client-0.8.0 prompt-toolkit-3.0.5 ptyprocess-0.6.0 pygments-2.6.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pyyaml-5.3.1 pyzmq-19.0.1 qtconsole-4.7.5 qtpy-1.9.0 six-1.15.0 terminado-0.8.3 testpath-0.4.4 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.2.4 webencodings-0.5.1 widgetsnbextension-3.5.1 zipp-3.1.0
124
Obtaining file:///home/runner/work/nbdev_test/nbdev_test
125
    ERROR: Command errored out with exit status 1:
126
     command: /opt/hostedtoolcache/Python/3.6.10/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/runner/work/nbdev_test/nbdev_test/setup.py'"'"'; __file__='"'"'/home/runner/work/nbdev_test/nbdev_test/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uuq9d1po
127
         cwd: /home/runner/work/nbdev_test/nbdev_test/
128
    Complete output (5 lines):
129
    Traceback (most recent call last):
130
      File "<string>", line 1, in <module>
131
      File "/home/runner/work/nbdev_test/nbdev_test/setup.py", line 13, in <module>
132
        for o in expected: assert o in cfg, "missing expected setting: {}".format(o)
133
    AssertionError: missing expected setting: description
134
    ----------------------------------------
135
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
136
##[error]Process completed with exit code 1.`

I did the same process with the command line and the pushing a new repo but same error

**Comment by pete88b** [comment]
"without changing anything in the code" is the problem (o: there are a few things you need to do before a new project will build - if you follow https://nbdev.fast.ai/tutorial/ up to "Commit to Github", you'll have a working project

**Comment by Arcturus122** [comment]
Thanks a lot, it works now, I'll close the issue.
