### ISSUE TITLE
Handling of __future__ imports

### ISSUE THREAD

**Issue by davidallen353** [fastai/nbdev#185]
I typically write python in Python3.7, but I like to use the new annotations described in PEP-563 (planned for 3.10).

To do this, I include the future import `from __future__ import annotations`. However this must be the first executable line of code.

As far as I can tell, there is not a way of telling nbdev to include an exported line before the `__all__ = []` statement. Thus, the compiled code cannot run. Specifically, it raises the follow exception on import `SyntaxError: from __future__ imports must occur at the beginning of the file`.

I am not sure how best to fix this. I did write in a work-around. Specifically, I modified the `create_mod_file()` function in `nbdev.export` to read

```python
def create_mod_file(fname, nb_path):
    "Create a module file for `fname`."
    fname.parent.mkdir(parents=True, exist_ok=True)
    file_path = os.path.relpath(nb_path, Config().config_file.parent).replace('\\', '/')
    with open(fname, 'w') as f:
        f.write(f"# AUTOGENERATED! DO NOT EDIT! File to edit: {file_path} (unless otherwise specified).")
        f.write('\nfrom __future__ import annotations')  # THIS LINE IS THE WORK AROUND
        f.write('\n\n__all__ = []')
```
This is admittedly a very hack-y workaround, but it meets my needs.

**Comment by pete88b** [comment]
I can think of a couple of ways that nbdev could accommodate this;
- change export to write cells that contain `from __future__ ...` before `__all___`
    - sync would also need to be updated as cells might be written out of order
    - +ve: it would "just work" for nbdev users / -ve: quite a lot of changes to nbdev
- add a callback to [nbdev_callbacks](https://github.com/fastai/nbdev/pull/188) and update `create_mod_file` so users can provide addition header text
    - +ve: really simple to implement (assuming PR 188 is accepted) / -ve: users have to put `__future__` imports in 2 places (notebooks and callback)

Anyone else have any ideas? happy to work on these changes either way (o:

**Comment by jph00** [comment]
I think we should try the first way, since it really ought to "just work". Maybe try a PR and see how hairy it is? If it ends up making the code significantly more complex, we might want to revert and use the callback idea instead.
