### ISSUE TITLE
nbdev_build_lib: UnicodeDecodeError

### ISSUE THREAD

**Issue by cordmaur** [fastai/nbdev#190]
Hi, 

I've just installed nbdev on Windows 10 and was following the tutorial as the first steps.
nbdev_build_lib command was raising the following error: **UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 489: character maps to <undefined>**

That was easily corrected adding the encoding to the `read_config_file()` in `imports.py`.
```
def read_config_file(file):
    config = ConfigParser()
    config.read(file, encoding='utf-8')
    return config
```

Don't know if that is the only place to fix. Should I make a Pull request for it?

**Comment by jph00** [comment]
Yes please do.
