### ISSUE TITLE
Create Optional Docker environment for nbdev?

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#191]
I am have been wrestling with dependency management issues with nbdev.  I tried to debug this, including pair programming for while with @jph00 and the problem remains somewhat illusive.  However, a solution that works for me is to create a Docker container and use that as my development environment. 

I just wanted to ask, should I contribute this Docker environment that I create for myself back to nbdev, along with instructions on how to use it?  Some benefits:

- Totally optional doesn't interfere with anything
- Nice thing to have for those familiar with Docker and want to develop locally
- VSCode has nice utilities for quickly attaching to [locally running  Docker containers](https://code.visualstudio.com/docs/remote/containers)

Let me know what you think.  If this is not desired or a bad idea, feel free to close this issue. I just wanted to ask since I'm making this tool for myself and wanted to know if I should share. 

Thanks!

**Comment by pete88b** [comment]
I think this is a great idea :-) being a docker novice: this would be great to get me started and show how it should be done

**Comment by hamelsmu** [comment]
@pete88b This now exists: https://github.com/fastai/docker-containers

🎉 Closing this isssue

**Comment by messismore** [comment]
Has this been dropped from v2, @hamelsmu? I used to be able to simply spin up a dev container in VS Code, start all services automatically, no virtual environment shenanigans required 🥲
