### ISSUE TITLE
Generating docs when source and notebooks are in different folders

### ISSUE THREAD

**Issue by mjurkus** [fastai/nbdev#197]
My project setup looks like this:

```
docs/
notebooks/
  - index.ipynb
  - train.ipynb
  - model.ipynb
src/
  project/
    - model.py
```

`settings.ini` 
```
nbs_path = notebooks
doc_path = docs
doc_baseurl = /project/
lib_path = src/project
```

when executing `nbdev_build_docs` I keep getting the error for each notebook:

```
converting: /...../project_root/notebooks/train.ipynb
'/...../project_root/notebooks/train.ipynb' does not start with `/..../project_root/src'
```

while `nbdev_build_lib` works as expected.

What is wrong with my setup?

**Comment by mjurkus** [comment]
Solved by adding symlink to source folder as such `ln -s src/project project`.
Maybe there is another way to avoid this?

**Comment by matthias-stifter** [comment]
Not working on windows using `mklink /D project src\project`, where syntax is mklink /D  LINK TARGET. Any idea?

**Comment by jph00** [comment]
Best to use the forums to ask for help. forums.fast.ai
