### ISSUE TITLE
nbdev_test_nbs & GPUs

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#199]
Currently `nbdev_test_nbs` [fails for lack of a GPU](https://github.com/fastai/fastai2/runs/941561829?check_suite_focus=true#step:8:37) when run against fastai2.

@jph00 [had an idea](https://discordapp.com/channels/689892369998676007/689892370002870284/739898739027869777) that would be very useful:  a `requiresgpu` flag or something like this.

**Comment by hamelsmu** [comment]
ref: https://github.com/fastai/fastai2/issues/451

**Comment by jph00** [comment]
Fixed.
