### ISSUE TITLE
Regression - Newer version fails to run tests on Github Actions

### ISSUE THREAD

**Issue by lucasavila00** [fastai/nbdev#208]
The problem started when this line was added: https://github.com/fastai/nbdev/commit/0ce70e6a9998603e0b35d7035e433341e755e741#r41343538

Here I just cloned the template and it shows the error:
https://github.com/lucasavila00/nbdev_bug/runs/967587111?check_suite_focus=true

```
  File ".../nbdev/cli.py", line 159, in _test_one
    if 0<idx<n and n>1: time.sleep(idx/2)
TypeError: '<' not supported between instances of 'int' and 'NoneType'

```

This can be fixed by pinning the nbdev version on the ci file, as in this commit: https://github.com/lucasavila00/nbdev_bug/commit/d9ff527c2e861efacfc167adee3387d0745ee25b

```
    - name: Install the library
      run: |
        pip install jupyter
        pip install -Iv nbdev==0.2.23
        pip install -e .
```

**Comment by igorbrigadir** [comment]
I've also run into this error - it seems to work fine if i use `nbdev<=0.2.26` but `0.2.27` and `0.2.28` fail when running `nbdev_test_nbs` with `TypeError: '<' not supported between instances of 'int' and 'NoneType'`
 as above

**Comment by johnkabler** [comment]
I also ran into this issue, and solved it the same way @lucasavila00  did.

**Comment by jph00** [comment]
Should be fixed now
