### ISSUE TITLE
Wheel missing as dependency

### ISSUE THREAD

**Issue by JoshuaMathias** [fastai/nbdev#21]
After running pip install nbdev I receive this error (though it does appear to install correctly):
```
  Complete output from command /home/vagrant/wlyze/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6zfwmzwq/pyrsistent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmph67xwsmupip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
```
It appears that 'wheel' should be added to settings.ini based on this answer: https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by sgugger** [comment]
Adding it in settings.ini wouldn't help since you need it to run the setup. I guess it might be needed as a pre-dependency like packaging but out of curiosity, did you get the error after doing `pip install nbdev` or an editable install?

**Comment by JoshuaMathias** [comment]
I just did `pip install nbdev` (and on a new virtual environment, Python 3.6.8), nothing more.

**Comment by jph00** [comment]
I'm not sure this is fixable within nbdev.
