### ISSUE TITLE
local hyperlinks should work equally on notebooks and docs

### ISSUE THREAD

**Issue by fernandopastawski** [fastai/nbdev#212]
There should be a standard way to have relative internal hyperlinks which can be introduced in the notebooks and work there as well as in the generated documentation. Currently I am only aware of options that work either or.
- module name (without .ipynb and prepended number) works as a link in the generated docs.
- relative file path works as a link to other notebooks when editing notebooks.

I think the main advantage of nbdev is that it closely couples documentation and code. This means that it is very difficult for documentation to become outdated. However, if it is not possible to locally check the links, this can easily begin to happen.

**Comment by jph00** [comment]
I'm not aware of a way to do this in notebooks, but if you come up with a mechanism that works, let us know.
