### ISSUE TITLE
tst_flags not generating Jupiter notebook magic

### ISSUE THREAD

**Issue by feynlee** [fastai/nbdev#213]
Adding `tst_flags` in `settings.ini` no longer provides corresponding Jupyter magic commands. This breaks all of my code cells that were marked with these test magic commands. It will throw errors like this

`UsageError: Line magic function `%nbdev_slow_test` not found.`  

and the code in that cell can not be run in the notebook anymore. This is a big inconvenience since I rely on this functionality to explore and test certain code in the notebook and provide examples in the doc, but I don't want them to run during the `nbdev_test_nbs` command. 

I noticed that `_new_test_flag_fn` which generates new test magic flag was commented out in the [remove magic flags](https://github.com/fastai/nbdev/commit/11e9010016ff75907ea9b1cffd7b5ada206039ca) commit, yet this functionality is still included in the [documentation](https://nbdev.fast.ai/test/). What was the consideration for removing this functionality? When can I expect to be able to use these test magic flags again?

**Comment by jph00** [comment]
Please use a comment instead of the line magic for now - we haven't been able to get the magic flags working reliably across all our projects.
