### ISSUE TITLE
Is it possible to set up nbdev locally? For example, a Ubuntu PC. 

### ISSUE THREAD

**Issue by liwei46** [fastai/nbdev#22]
As in the title.

**Comment by sgugger** [comment]
I don't understand the question: you can `pip install nbdev`.
If you're thinking of your projects, they don't have to end up on GitHub/pypi if you don't push/publish them. In any case, discussion around the library is better done on the [forum](https://forums.fast.ai/t/nbdev-discussion/59145) as we keep issues for known bugs only.
