### ISSUE TITLE
should nbdev convert parameter names to links in markdown?

### ISSUE THREAD

**Issue by pete88b** [fastai/nbdev#221]
https://github.com/fastai/nbdev/pull/218 updated `show_doc` to not convert names in backticks to links - if the name is used as a parameter of the element passed to `show_doc`.

This means that you can backtick a module or function name in the doc string of a function and
- it will be formatted as code (not converted to a link)
- if the name is used as a parameter of the function.

I think it could be worth extending this behavior to the markdown following a show_doc call - as described [here](https://pete88b.github.io/nbdev_demo/apple.html).

**Comment by jph00** [comment]
I think if this can be implemented without making the code too complex, it's a good idea.

**Comment by pete88b** [comment]
Hi @jph00 

I've not yet found a clean way to keep track of the last element processed by `show_doc` - was hoping to do this without changes to `show_doc` but it looks like support for function interception is not ready for prime time yet (e.g. https://github.com/dlshriver/intercepts).
How about changing `_re_backticks` to ignore anything in triple backticks?

**Comment by jph00** [comment]
You can already use `<code>` to explicitly avoid link creation - does that suffice?

**Comment by pete88b** [comment]
Yes (o:

**Comment by jph00** [comment]
So, shall we close this, since we don't really have a solution?

**Comment by pete88b** [comment]
Makes sense to me
