### ISSUE TITLE
Export import declaration as the absolute import instead relative import

### ISSUE THREAD

**Issue by sakinaljana** [fastai/nbdev#227]
Hello @hamelsmu @jph00 @sgugger,

I have question about exporting import declaration from notebook into python module. Is it possible to opt for absolute import to be yielded during the export instead of relative import?

For instance, i have following cell:

```jupyter
#export
from module.test import *
```

normally, above cell will be imported as:

```python
from .test import *
```

Can we export it to be this one instead?

```python
from module.test import *
```

Thanks in advance!

**Comment by jph00** [comment]
Please use forums.fast.ai for questions
