### ISSUE TITLE
%nbdev_collapse_... does not display "Show/Hide" button

### ISSUE THREAD

**Issue by antonbabkin** [fastai/nbdev#228]
I may be doing something wrong, but I can't find a way to fix it, any help will be appreciated. The problem is that when I export a notebook as a HTML document, "Show/Hide" buttons are not displayed for collapsed input or output cells.

Here is an example: [notebook ](https://github.com/antonbabkin/rurec/blob/master/nbs/test_nbdev_collapse.ipynb) and [documentation](https://antonbabkin.github.io/rurec/test_nbdev_collapse/).

**Comment by antonbabkin** [comment]
As I could understand, my problem was mainly with outdated template files in the `docs/` directory. I have never used Jekyll or Ruby, and so it's hard to debug these things.

Now I tried to update by completely removing `docs/`, then copying a fresh `docs/` directory from [nbdev_template](https://github.com/fastai/nbdev_template) and running `nbdev_build_docs`. The good news is that I got collapse markers in the [page](https://antonbabkin.github.io/rurec/test_nbdev_collapse). The bad news is that all navigation and other Jekyll styling is gone. What did I miss now?

**Comment by pete88b** [comment]
Is it possible to revert your changes to `docs/` and then replace just `docs/css/customstyles.css` with https://github.com/fastai/nbdev/blob/master/docs/css/customstyles.css

**Comment by antonbabkin** [comment]
Thanks for the pointer, @pete88b ! Looks like I forgot to commit a couple new files in `docs/`, now it all looks good.

When I started the repo, I've decided to set up everything manually instead of cloning the nbdev template, so that I could better understand how things work. The downside is that now I need to manually make all updates that happen upstream.
