### ISSUE TITLE
Better support for other languages in export2html

### ISSUE THREAD

**Issue by ankitbko** [fastai/nbdev#231]
Let me know if this is not the correct place to discuss this feature request. I am coming from context of fastpages blog and the ask here is to have better support for multiple languages in export2html. The current implementation does convert cell containing any language into html however it has 2 limitation - 

1. The syntax highlight gets messed up as it always assume its python code.
2. Using tags such as `#hide_input` is a problem as `#` is not a comment syntax in other language. 

I use Databricks for most of my work so I can talk from its perspective. The way Databricks works is that it supports magic commands (%R, %md, %SQL, %scala and %python) to determine which language the code is written. 

1. For syntax highlighting is it possible to read the this and determine which language the code is in and change? It already does proper formatting for code segment in markdown under ``` tag. Wondering if that can be reused somehow.
2. Once the language is determined is it possible to switch which "tags" will be used to specify prefix in tag based upon language's comment syntax (`//hide_input` instead of `#hide_input`)?
a. In case this is not possible to dynamically change what prefix will be used, is it possible to make it configurable to an extent that users can specify what prefix can be used?

**Comment by pete88b** [comment]
To help with 2) Can you 'from nbdev import *' in a databricks notebook? If you can, you might be able to use nbdev magic flags like %nbdev_hide_input.

https://github.com/fastai/nbdev/blob/master/nbs/08_flag_tests.ipynb

**Comment by ankitbko** [comment]
In databricks the first line in code cell must be a magic command to change language (%scala, %R, etc). So once the language is changed it will through error as %nbdev_hide wont be recognized as a valid language statement.

**Comment by jph00** [comment]
Best place to discuss this is forums.fast.ai. If you develop a specific proposal for how to handle multi-language support, feel free to open a new issue to post it here.
