### ISSUE TITLE
No docs_serve in Makefile

### ISSUE THREAD

**Issue by ConnorJL** [fastai/nbdev#24]
In the [tutorial](http://nbdev.fast.ai/tutorial), it is said one can host a local version of the docs with the "make docs_serve" command. This doesn't seem to work for me, as there is no such target in the Makefile.

All my code is here (just a copy of the base template and some playing around): https://github.com/ConnorJL/nbdev-test

**Comment by sgugger** [comment]
Are you sure you have a dev install of nbdev? I'm not sure that addition made its way to the latest release (will make a new one later today) but the line for this is [there](https://github.com/fastai/nbdev/blob/ffc62e2c7cca2123bd778ed83c1086b06e84ee36/nbdev/template.py#L10).

Note that after updating nbdev, you need to remove your current Makefile as it's only generated by the command `nbdev_build_lib` if there is none. 
Please reopen if the problem persists.
