### ISSUE TITLE
Include data in the package

### ISSUE THREAD

**Issue by btrspg** [fastai/nbdev#258]
Hi there, 

Thanks for developing such a fantasy tool for package development. I wonder if I could include some data files in the jupyter notebook. 

In general python package, I specific the `setup.py` with 

```
include_package_data=True,
package_data={'': ['data/*.*']},
```
.
I don't know if I need to do it manually after `nbdev_build_lib` or can do it automatically in jupyter notebook or `settings.ini`.

Looking forward to your reply. 

Logan

**Comment by jph00** [comment]
I'd suggest just editing your setup.py
