### ISSUE TITLE
fastprogress bar in README.md doesn't render

### ISSUE THREAD

**Issue by joedockrill** [fastai/nbdev#259]
hi,

i have a fastprogress bar in my index, it ends up in README.md just rendering the html like this:

<style> /* Turns off some styling */ progress { /* gets rid of default border in Firefox and Opera. */ border: none; /* Needs to be in here for Safari polyfill so background images work as expected. */ background-size: auto; } .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar { background: #F44336; } </style> 100.00% [10/10 00:02<00:00 Images downloaded]

</br></br>
would it be difficult to render the text/console version for the markdown file?

**Comment by jph00** [comment]
Yeah fastprogress/nbdev requires a proper markdown environment, which github readme doesn't provide. Happy to take a PR to fix this, if there's interest, but not likely to do it myself.
