### ISSUE TITLE
The gitlab docs generator makes wrong sidebar links

### ISSUE THREAD

**Issue by jochym** [fastai/nbdev#260]
Since recent updates to nbdev (1.0.18 at least, probably earlier) the generation of sidebar navigation on gitlab stopped working correctly. It generates module_name.html links but the actual files are located in module_name/index.html. If you fix the paths and switch to custom sidebar it gets fixed in generation. If you keep autogenerated json file and patch it before running jekyll build, it still does not work (the links are still the same). You can check this in my fork of the gitlab template: (https://gitlab.com/jochym/nbdev_template). I have too little knowledge on jekyll to fix this or even properly debug but will gladly help by testing etc.

**Comment by tcapelle** [comment]
I think it is also broken on github...
I updated the gitlab repo, let's try to fix this.

**Comment by jph00** [comment]
I believe you just need to disable permalink: pretty in jekyll.
