### ISSUE TITLE
`<details>` Internal Markdown parsing support

### ISSUE THREAD

**Issue by josiahlaivins** [fastai/nbdev#277]
When making python docs, It would be nice to be able to have dropdowns. I found this can be done via the html `<details>` tag. However, it seems that nbdev does not support/understand the details tag, and so all the internal markdown will get ignored.

In a jupyter notebook I have 2 cells:

```bash
<details>

**This should be bold**

</details>
```

```bash
<details>

<b>This should be bold</b>

</details>
```

```python
# hide
from nbdev.cli import *
from nbdev.export import *
from nbdev.export2html import *
make_readme()
notebook2script()
notebook2html(n_workers=0)
```

The results from each is:
![image](https://user-images.githubusercontent.com/55600928/95349815-7c139080-088d-11eb-94bd-ae2d0fe610f9.png)

You will notice that the internal markdown does not get converted.

**Comment by hamelsmu** [comment]
Within a HTML block you can only put HTML due to the limitations of Jekyll.  There is no great way around this, unfortunately.  AFAIK.  Please feel free to let me know if I'm wrong or if there is something I'm overlooking.
