### ISSUE TITLE
Some URLs in README are not found (404)

### ISSUE THREAD

**Issue by JiaxiangBU** [fastai/nbdev#28]
I find some URLs in README not found, like

> the export functionality from jupyter notebooks to a python library

export: http://nbdev.fast.ai/export.html

But I can access https://nbdev.fast.ai/export/

Similarly, http://nbdev.fast.ai/export2html.html, http://nbdev.fast.ai/export2html.html

**Comment by sgugger** [comment]
Thanks for flagging, this is now fixed.
