### ISSUE TITLE
[enhancement] Support Arbitrary Static Site Generators

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbdev#285]
# Proposed feature:

VuePress uses Markdown rather than HTML's when building documentation. Currently we have a working little hack inside of `nbdev_build_docs` to get everything working:
```python
notebook2html(fname=fname, force_all=force_all, n_workers=n_workers, pause=pause, cls=MarkdownExporter, template_file='md.tpl')
```
We add in the `cls` and `template_file` and simply rename our `html` to `md` and this seems to do the trick, though further integration would be better. An example running website can be found [here](https://iyaja.github.io/walkwithfastai.github.io/vision.clas.single_label.html#importing-the-library-and-the-dataset)

There are some other issues that would need to be worked out however, as currently we have `nbdev_nb2md`, and the proposed option would allow for `nbdev_build_docs` to work with markdown-exportation as well

**Comment by hamelsmu** [comment]
If the target is vuepress it might be good to specify if you need any special front matter or any other kind of markup in addition to the markdown to make sure things work per normal, such as all the extra nbdev features (example showing/hiding cells) ?

**Comment by muellerzr** [comment]
@hamelsmu I was going to open another issue about that actually, so may just be better to have this as an encompassing "vuepress" issue instead. The other issue we're facing with right now is linking up source code to the documentation by mention (such as say having `DataLoader` link to it's source code)

**Comment by muellerzr** [comment]
@hamelsmu with the hack to `nbdev_build_docs` it winds up working similar (in regards to the tags, not necessarily options like collapse and hide, we haven't tested that)

**Comment by borisdayma** [comment]
Just a comment that I believe vuepress targets more documentation sites, but it's definitely great.
There's also nuxt/content which is similar (accepts markdown) but a bit more flexible.

**Comment by iyaja** [comment]
@muellerzr @hamelsmu Vuepress supports a number of markdown extensions that allow you to add, for example, tip/warning/hide blocks or line highlighting in code blocks. They have more details on their [docs page](https://vuepress.vuejs.org/guide/markdown.html). However, I believe these extensioins may not work with every Vuepress theme. One useful feature might be auto-generated vuepress-style configs for the navbar.

But more generally, I think there are a lot of other documention generators that build from markdown files ([mdBook](https://github.com/rust-lang/mdBook), [docusaurus](https://docusaurus.io/), etc.), so if nbdev could support something like `nbdev_build_md_docs` that built general-purpose markdown without any specific vuepress syntax, then anyone could use any generator they want.

**Comment by hamelsmu** [comment]
I’m not sure that “bring your own static site generator” is a good idea,
only because that would make it much harder and raise the difficulty of
using nbdev to build docs significantly.

I believe that we have to provide the integrations for this reason.  Using
and configuring a static site generator is not trivial, especially when it
comes to converting markdown to conform to all the little features of each
SSG and to also be compatible with the nbdev language like “show/.hide
cells”

**Comment by hamelsmu** [comment]
I discussed this with @jph00 and he mentioned that he wanted to build this in a modular way to support arbitrary static site generators (SSG's) with paved path towards Hugo.   I would personally like to also build a paved path to VuePress, esp for fastpages, so I can help be the guinea pig for this kind of thing.  

I'll add this to the v2 list

**Comment by hamelsmu** [comment]
P.S. I renamed this issue to 

> Support Arbitrary Static Site Generators

To make it more general

**Comment by jph00** [comment]
Should be fixed in v2
