### ISSUE TITLE
Colons break badges, title, and quote in generated documentation

### ISSUE THREAD

**Issue by iyaja** [fastai/nbdev#287]
Adding colons (`:`) in the first H1 tag of a source notebook seems to cause the title, badges, and quote to not render in the built documentation.

For an example of this, see this [notebook](https://github.com/AIDA-UIUC/ai_workshops_old/blob/master/00_introduction.ipynb) and it's corresponding [webpage](https://aida-uiuc.github.io/ai_workshops/introduction.html).

**Comment by hamelsmu** [comment]
If you surround it with double quotes it won't break

**Comment by hamelsmu** [comment]
I have this warning in fastpages for this reason as well

![image](https://user-images.githubusercontent.com/1483922/97817122-47f27c00-1c4f-11eb-8336-cf2f1ddcd78b.png)

Given that we are updating to v2, not sure if we want to find a way to do something clever to fix this on behalf of users or to add it to the docs.  @jph00 WDYT?

**Comment by hamelsmu** [comment]
More background:

There is not a great solution for this.  In fastpages, I tried to defensively put quotes around the title front matter for people, but then that broke when the title itself already had quotes.  However, I'm sure something clever can be done to form valid YAML and check it first (I just didn't want to because Liquid is a pain as a programming language).

**Comment by jph00** [comment]
Does backslash-escaping in the frontmatter fix it? If so, nbdev should be that automatically. Or perhaps we should also surround in quotes, and backslash-escape any embedded quotes?

**Comment by hamelsmu** [comment]
> Does backslash-escaping in the frontmatter fix it?

No I believe not (unless I'm doing it wrong).  I was doing more research and found this [SO Thread](https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-i-e-or-in-yaml) and looks like we can just string replace colons with `&#58;` I believe, so I think this could be a good solution to this problem!

**Comment by jph00** [comment]
Should be fixed in v2
