### ISSUE TITLE
[enhancement] Make default_exp optional

### ISSUE THREAD

**Issue by sebarthel89** [fastai/nbdev#288]
Hey there,

first of all, thank you very much for making this project public. It really helps to empower people that love to work with notebooks.

For me, it would be very helpful if default_exp is not mandatory.

Instead, I would love to fall back to the notebook filename if no export name is given. Before I create a PR, I want to get your opinion about this idea.

Thanks in advance!

**Comment by hamelsmu** [comment]
@sebarthel89 as @tcapelle mentioned, There are situations where you might not want to export at all, for example when you are making a page for documentation purposes only, like a tutorial.  (In fact I have done this recently).

I'll go ahead and close this.

**Comment by Journerist** [comment]
what do you think about other exporting strategies? like having a set of export strategies like this:

- explicit export (current, default)
- default_all_by_name -> takes the filename and exports it to the configured location
- there can be more

**Comment by sebarthel89** [comment]
what do you think about other exporting strategies? like having a set of export strategies like this:
* explicit_export (current, default)
* default_all_by_name -> takes the filename and exports it to the configured location
* there can be more

**Comment by sebarthel89** [comment]
seriously, the requirement for me would be avoiding the need to put it all the time on the top. Let's brainstorm together @tcapelle :). I would appreciate getting some more ideas and insights from your side than just a "NO" 😂
