### ISSUE TITLE
Missing import statement in the tutorial?

### ISSUE THREAD

**Issue by AllenDowney** [fastai/nbdev#289]
Hi.  I am following the tutorial using a copy of the template repository and ran into a problem at this step:

https://nbdev.fast.ai/tutorial.html#Add-in-notebook-export-cell

When I run

```
notebook2script()
```

I get 

```
NameError: name 'notebook2script' is not defined
```

I assume I was supposed to import it, but I don't see instructions for doing that.

I guessed it might be

```
from nbdev import notebook2script
```

But that gets me

```
ImportError: cannot import name 'notebook2script' from 'nbdev' (/home/downey/anaconda3/envs/.../lib/python3.8/site-packages/nbdev/__init__.py)
```

Thanks for any help you can provide.

**Comment by jph00** [comment]
Thanks @AllenDowney we'll add that to the tutorial.

A great way (IMO) to learn about using nbdev in practice is to look at notebooks for projects that use it. One really simple project is `fastwebhook`, which does demonstrate all the key features - here's the notebook for that:

https://github.com/fastai/fastwebhook/blob/master/00_core.ipynb

You'll see the last cell is this:

```
from nbdev.export import notebook2script
notebook2script()
```

Alternatively, you can run `nbdev_build_lib` in your terminal. Feel free to reopen this issue if this doesn't resolve your question.

**Comment by AllenDowney** [comment]
My version of `00_core.ipynb` does not have that cell.  I got it by copying the template on GitHub.

**Comment by jph00** [comment]
That's a good point - I was referring to not to the template, but to:

https://github.com/fastai/fastwebhook/blob/master/00_core.ipynb

Cool idea to add the cell to the template though - will do that!

**Comment by BagelOrb** [comment]
Was working through some tutorial which recommended me to do `notebook2script()`, but that function doesn't exist anymore. 

I guess I should use `from nbdev.export import nb_export` instead? How would I use it to copy a marked number of cells  automatically to a similarly names .py file?

Would be nice to have a very simple example file in this repo. Sadly, I don't have the time to watch a 1.5 hour tutorial.

**Comment by BagelOrb** [comment]
I finally got it to work like this:

```python
#|hide
#|default_exp train_fastai
```

```python
#|export
some_important_code()
```

```python
#|hide
from nbdev.export import nb_export

nbname = 'train_fastai.ipynb'
nb_export(nbname=nbname, lib_path='')
```

Note that the `#|default_exp train_fastai` needs to match the file name or else the export will silently fail.
