### ISSUE TITLE
_config.yml is not generated using nbdev_build_docs

### ISSUE THREAD

**Issue by daviddemeij** [fastai/nbdev#29]
When using `nbdev_build_docs` from the command line the `_config.yml` file in the `docs` folder is not generated. 

When using the below code in a notebook cell it does work.
```
#hide
from nbdev.export import *
notebook2script()
```

**Comment by sgugger** [comment]
Yes, but you are mixing two commands: your cell is the equivalent of `nbdev_build_lib`. You have to run this at least once before running `nbdev_build_docs` (it needs the package to exist to work).
