### ISSUE TITLE
A way to check for broken links

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#294]
There has to be a way to follow all the links in the docs and report any broken links.  People are constantly complaining about some link being broken in the docs, this makes me think we need CI for this, and I think this is possible.

**Comment by krishnakalyan3** [comment]
What do you think of this 

`https://github.com/bartdag/pylinkvalidator`

**Comment by hamelsmu** [comment]
Thanks Krishna this seems useful

**Comment by hamelsmu** [comment]
this has been implemented in [fastai/fastlinkcheck](https://github.com/fastai/fastlinkcheck)
