### ISSUE TITLE
A page that shows all the flags

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#296]
It would be useful to have a single page or cheatsheet that shows all the magic flags like `#hide`, `#hide_input`, `#slow`, etc.

**Comment by feras-oughali** [comment]
I have been trying to find all possible flags in the documentation but it was scattered all over. Then, I noticed this issue. So, I put up a page for all flags (hopefully I didn't miss anything from the docs). 

However I'm not sure about the flags related to tests. My understanding is that those flags are not fixed and defined in the settings.ini

Here is a link to the page: https://feras-oughali.github.io/nbdev/flags.html 

note: tests section is not finalized.
