### ISSUE TITLE
broken image urls

### ISSUE THREAD

**Issue by daviddemeij** [fastai/nbdev#30]
I found out my previous pull request resulted in some broken URLs (as pointed out in #28), this didn't show up in my tests since the tests were using the previous URL pattern. 

I saw that @sgugger already fixed some of these issues by setting a `doc_url` in `settings.ini` (while I was also working on it) and it seems to be working now. The only downside of this is that some URLs will point to an external source when running the code locally, but I guess this is not a big issue and I cannot find a cleaner solution right now either. 

I just want to point out that same problem causes image URLs to not work (if they are not on the homepage), for example here http://nbdev.fast.ai/merge/  
The image refers to http://nbdev.fast.ai/merge/images/merge.PNG instead of to http://nbdev.fast.ai/images/merge.PNG but http://nbdev.fast.ai/images/export_example.png on the http://nbdev.fast.ai/ still works.

**Comment by sgugger** [comment]
The work on urls is ongoing (We have actually split doc_url between doc_host and doc_baseurl so that the links also work when you test your doc website locally).
I'll look at the images as I continue working on this.

**Comment by sgugger** [comment]
Image links are fixed now.
