### ISSUE TITLE
Upgrade to nbconvert >= 6

### ISSUE THREAD

**Issue by AlexJoz** [fastai/nbdev#305]
Hello!

We used to deploy our jupyter notebook based apps with __Voila__ (https://github.com/voila-dashboards/voila).  

Not so long ago, we started utilising __nbdev__ and already like it a lot, but having 'nbdev' and 'voila' deps together fail the dependency tree resolution of the project.
Actually, __viola__ requires `nbconvert>=6.0.0,<7`, while __nbdev__ - `nbconvert<6`

Do you know what's holding you back from upgrade (ver. 5 -> 6 of `nbconvert`). If it's not a hard fix, mb we can contribute?

Thanks in advance.

**Comment by agoose77** [comment]
It is likely the big 6->7 template system overhaul that is preventing an upgrade. `nbdev` doesn't seem to do much customisation of the `nbconvert` machinery, so it's likely just the templates that need to be modified to inherit from the new templates (although the old templates are still there for compatibility IIRC), and possibly the `nbdev` code that specifies where `nbconvert` looks for templates might need to be upgraded.

**Comment by hamelsmu** [comment]
This will be fixed with [nbconvert v2](https://github.com/fastai/nbdev/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+2+of+Nbdev%22) we are already aware of this change, and @jph00 is using the latest nbconvert version in [the development branch](https://github.com/fastai/nbdev/tree/nbconvert6).  Just ask for a bit of patience as we are working on it right now!

**Comment by AlexJoz** [comment]
@hamelsmu, hello! Are there any time estimations for releasing v2 or at least this fix?  Thanks in advance =)

**Comment by hamelsmu** [comment]
> Are there any time estimations for releasing v2 or at least this fix? 

No estimate

**Comment by michaelaye** [comment]
didn't this happen? I had to upgrade to nbconvert=6 to get nbdev working, I believe?

**Comment by benoit-cty** [comment]
I also need an upgrade of nbdev with support of new Jupyter frameworks. See https://github.com/fastai/nbdev/pull/457
In the meanwhile I use docker to build the docs.

**Comment by tylere** [comment]
Any update on this issue?
It is making it problematic to use of nbdev with modern jupyter components.
Could it be decoupled from the [v2 milestone](https://github.com/fastai/nbdev/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+2+of+Nbdev%22), which hasn't seen much activity in the last year?

**Comment by jph00** [comment]
fixed
