### ISSUE TITLE
github (or gitlab) account required

### ISSUE THREAD

**Issue by diegoroversi** [fastai/nbdev#306]
From tutorial looks like nbdev require a github (or gitlab) account. It's quite disappointing to have to use a cloud service to use nbdev... It's possibile to use nbdev with all the required software on my own pc?

Thanks.

**Comment by hamelsmu** [comment]
There is no requirement to use github or gitlab.  You can use [nbdev_new](https://nbdev.fast.ai/cli.html#nbdev_new) to setup a new nbdev project without ever logging into GitHub.  

Hosting docs and using CI are completely optional, and you can choose to ignore GitHub / GitLab for that.
