### ISSUE TITLE
Add markdown and param docs to docstring

### ISSUE THREAD

**Issue by jph00** [fastai/nbdev#318]
e.g. `add_docs(param_docs={...}, xtra_docstring="""...""")`

**Comment by AmadeusHovekamp** [comment]
I tried to find where the docstring conversion to html elements happens. Could you point me to it so that I can change my docstrings accordingly? Thanks!

**Comment by AmadeusHovekamp** [comment]
Deleting the html files, running nbdev_build_lib first and only then nbdev_build_docs seems to have fixed my issue.

But I am still looking forward to the table styled param documentation proposed on Twitter 2020-11-09! :)

**Comment by fredguth** [comment]
@jph00 I would like to contribute to this issue.  I already understand how `all_docs` works. But I didn't understand your suggestion.  Could you give an example of how would all_docs be used?

**Comment by fredguth** [comment]
BTW, add_docs is part of fastcore, should this issue be the other repo?

**Comment by jph00** [comment]
We ended up using `docments` for this
