### ISSUE TITLE
Inconsistent custom sidebar behaviour

### ISSUE THREAD

**Issue by ojscholten** [fastai/nbdev#322]
I've encountered an inconsistency in the sidebar behaviour when using the `custom_sidebar = True` in the `ini` file and wanted to document my findings to help future developers and hopefully get some light on the issue.

***Issue***: Malformed `sidebar.json` files work, but cause the menu bar to always collapse instead of remaining open with the current page highlighted.

***Examples***: [Working project](https://sachinruk.github.io/torchlife//hazard.Cox) ([working sidebar.json](https://github.com/sachinruk/torchlife/blob/master/docs/sidebar.json)), and [project with menu always collapsed](https://kshitij09.github.io/fast_impl/tutorial.arch_explore/) ([broken sidebar.json](https://github.com/Kshitij09/fast_impl/blob/master/docs/sidebar.json))

***Additional info***: In my own project using [this sidebar.json](https://github.com/pysan-dev/pysan/blob/master/docs/sidebar.json) the menu opens on the correct page, but with `.html` added to each of the items it still works but the menu is always collapsed. I've searched through the forums and found the fast.ai sidebar.json [example post](https://forums.fast.ai/t/nesting-sidebar/74050) (and the [one(s)](https://github.com/fastai/nbdev/issues/219) on [github about it](https://github.com/fastai/nbdev/issues/26)), but created this issue because I believe they're different problems (creating vs malformed).

***Context***: This may be theme specific (default theme) in which case this behaviour may not be relevant. This is also using custom sidebar jsons so may not be in the remit of a bug in this project, but more of a general note somewhere for people that encounter this issue in the future.

***Error Messages***: None - this appears to be an undefined behaviour issue.

Please close if out of scope or to archive for future custom sidebar users :)

**Comment by jph00** [comment]
Should be fixed in v2
