### ISSUE TITLE
functions in module but not in docs

### ISSUE THREAD

**Issue by bblais** [fastai/nbdev#324]
I am new to nbdev, and this question may be more about proper programming practices, but I'll often have functions that are used in a library but really aren't meant to be documented as part of the library.  They support the functions in the library (e.g. wrapping arrays, redirecting stdout, etc...) In nbdev `#hide` removes them from the library, so they can't be used, and `#export` includes them in the docs which I find to be cluttering.  Is there a best practices that I am running into, or an option I am missing?  I notice in nbdev source itself, there is `from nbdev.imports import *` yet there doesn't seem to be a `#default_exp imports` anywhere, which may be what I'm referring to (a place to put imports which don't make it into the docs) but I don't see how that's implemented.

**Comment by hamelsmu** [comment]
> in nbdev #hide removes them from the library, so they can't be used, and #export includes them in the docs which I find to be cluttering.

`#hide` removes them from the docs, not the library
`#export` adds them to the library, and will also appear in the docs by default unless you also specify `#hide`

Take the tutorial and walk through the minimal example, and I think it will clarify many of your questions.

**Comment by bblais** [comment]
> `#hide` removes them from the docs, not the library

Yes, that's what I thought...but here's an example.  In the package here [https://github.com/bblais/pyndamics3](https://github.com/bblais/pyndamics3), in the file `00_core.ipynb` the third cell which includes the class `InterpFunction` if I change `#export` to `#hide`, remake the lib and docs, the class definition disappears from `core.py` in the package.  Gone from the library, and the docs.   I was following the guidance in the tutorial to port a package I had worked on before to check out nbdev.

**Comment by hamelsmu** [comment]
> If I change #export to #hide

If you don't have `#export` then the code will not be exported to the library.  If you want to export the code to the library, but also hide it from the docsyou need:

```
#export
#hide
...
```

For example, in [This notebook](https://github.com/fastai/fastcore/blob/master/nbs/01_basics.ipynb)
![image](https://user-images.githubusercontent.com/1483922/100173203-e5238780-2e7e-11eb-88da-87a202862751.png)



You can also hide exported functions and classes without any markup if you name your function indicating that it is private with a leading underscore, like `_my_function` (which is probably a good idea to do anyways).

HTH

**Comment by hamelsmu** [comment]
I'll go ahead and close this, lmk if this is not resolved.

**Comment by bblais** [comment]
thanks!  that's perfect!
