### ISSUE TITLE
nbdev_update_lib behaving incorrectly for #nbdev_comment _all_ = ['blah']

### ISSUE THREAD

**Issue by thakkarparth007** [fastai/nbdev#328]
I accidentally came across this bug.
I have a cell with `_all_ = ['blah']` in notebookA. In the corresponding python file, this gets translated as `#nbdev_comment _all_ = ['blah']`. 

Now, I ran `nbdev_update_lib` after making a tiny change in one of my python files to fix the corresponding notebook. Turns out, the `#nbdev_comment _all_ = ['blah']` bit gets copied to notebookA and screws up my imports in some other files.

Ideally, `#nbdev_comment ` should get removed before getting applied to the notebook.

**Comment by hamelsmu** [comment]
@thakkarparth007 can you share a reproduceable example with code, etc.?  A GitHub repository with links to files and steps to take would be ideal.

**Comment by hamelsmu** [comment]
nbdev automatically creates `__all__` for you.  Are you wanting to override that?  There is a way to control what goes into `__all__` and what stays out of `__all__` with the `export` and `exporti` flags etc.  I could be misunderstanding, LMK

**Comment by thakkarparth007** [comment]
I wanted to export some imported modules explicitly. I'd been doing that by modifying the `__all__` variable directly because I thought I read that in some older version of docs, but the latest docs ask to use `#add2all`. I've not tested it with that but since it's specifically designed for this purpose, I believe it'd work. Closing this issue because it doesn't seem to affect the latest version.
