### ISSUE TITLE
possible error in tutorial - 00_core vs. index?

### ISSUE THREAD

**Issue by paulkarayan** [fastai/nbdev#33]
see tutorial sections:
https://nbdev.fast.ai/tutorial/#Add-a-class

![image](https://user-images.githubusercontent.com/1227327/71689794-c6447000-2d57-11ea-9d57-d9ad9296d15c.png)

I think this is supposed to be 00_core.ipynb

**Comment by sgugger** [comment]
Thanks for flagging, fixed, will update the docs in a separate commit.
