### ISSUE TITLE
Docs Suggestion: Add clearer parameter guidelines for export

### ISSUE THREAD

**Issue by aronchick** [fastai/nbdev#332]
In reading through several of the docs, it wasn't clear how to format `#export` for the purposes of creating a different external file.

It might be nice to here (https://nbdev.fast.ai/export.html#notebook2script) or elsewhere to list some examples for how to add a parameter to `#export`

**Comment by hamelsmu** [comment]
Marking this for @romanofoti

**Comment by hamelsmu** [comment]
@jph00 is going to look into this soon.  I have created a [demo notebook for this in an nbdev repo](https://github.com/hamelsmu/nbdev_export_demo/blob/master/demo.ipynb) which we may consider adding to the docs.

**Comment by hamelsmu** [comment]
I'm working on this now
