### ISSUE TITLE
CSS image question

### ISSUE THREAD

**Issue by tburnett** [fastai/nbdev#333]
I'm using nbdev to develop/test/document code, thank you for this. But since the code is a science analysis, I'm using it to present data analysis. As such, I generate Matplotlib figures, save them as png files, then include as images.  My HTML for this sets width, and includes the figure in link a to the image file. This allows me to generate a large image, but display a reduced size, with the possibiliy that a user can click on it to see details.  This works fine in jupyter, but the  width attribute gets overridden in the CSS for the document that nbdev generates. 
A separate perhaps issue is that the conversion to README.md does not handle the "figure" tag.
Example of this is my repo  https://github.com/tburnett/light_curves

**Comment by tburnett** [comment]
Well, the reason, I think,  is that it is within a div with class "post-content", and there is a css file `costumstyles.css` that has the following fragment
```
.post-content img {
    margin: 12px 0px 3px 0px;
    width: auto;
    height: auto;
    max-width: 100%;
    max-height: 100%;
```
in it **three** times.
Deleting them all solves my problem, but only temporarily, since this file appears to get updated from somewhere. I'll commit this change, but I'm hoping that someone will suggest a more elegant solution.

**Comment by hamelsmu** [comment]
@tburnett this is a little tricky to change, but you have to change it in the right place! 

You must make sure you edit the css file located in `/docs/css` **not** in `docs/_site/css` (the latter one is generated from the former).  

You are correct about the duplicated css, which I removed in #348.  closing this now, let us know if you have any more questions (on a new issue). 

cc: @jph00
