### ISSUE TITLE
`git diff` on a merge conflict fails with an error from `nbdev_clean_nbs` script

### ISSUE THREAD

**Issue by jnareb** [fastai/nbdev#334]
When running `git diff` from a terminal inside Jupyter Notebook (or rather JupyterLab) when there is a merge conflict in the repository, I get the following error from `nbdev_clean_nbs` called from `textconv` diff filter:

```
$ git diff
[...]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\nbdev_clean_nbs.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\fastcore\script.py", line 103, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "c:\programdata\anaconda3\lib\site-packages\nbdev\clean.py", line 86, in nbdev_clean_nbs
    nb = json.load(open(f, 'r', encoding='utf-8'))
  File "c:\programdata\anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\programdata\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\programdata\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 108 column 1 (char 4184)
fatal: unable to read files to diff
```

The `nbdev_clean_nbs` is called by gitattributes mechanism, see `.gitconfig` entry:
```
[diff "ipynb"]
        textconv = nbdev_clean_nbs --disp True --fname
```

**Comment by igorbrigadir** [comment]
I can't tell for sure it's the same thing, but i think I got into trouble with this before, because of the way git deals with merge conflicts, it does this to files:

```
<<<<<<< HEAD
some code
=======
some conflicting code
>>>>>>> branch-a
```

Which breaks the ipynb file json - making it impossible for nbdev to read the ipynb file. The only solution is to fix it manually in a text editor to make sure the json is valid again.

**Comment by jnareb** [comment]
Why do it manually, if it can be done automatically using the diff/merge driver mechanism?

`nbdev` should in my opinion provide a <u>**merge driver**</u> in addition to **textconv driver** it provides, something like the [git-json-merge](https://github.com/jonatanpedersen/git-json-merge) (in JavaScript) or [git-merge-drivers](https://github.com/rmedaer/git-merge-drivers) (in C++), but in Python:

Then it would be enough to add the following to `.gitconfig` created by the `nbdev_install_git_hooks` command:
```ini
[merge "json"]
    name = custom merge driver for json files
    driver = git-json-merge %A %O %B
```
And the following line to `.gitattributes`:
```gitattributes
**/*.ipynb merge=json
```

**Comment by igorbrigadir** [comment]
Yes! This would be a much better solution!

**Comment by hamelsmu** [comment]
@jnareb can you educate me a bit mroe on how the git merge driver works from a user interface perspective?  

Doesn't the user still have to choose which version of the code needs to be favored in the conflict manually?

**Comment by jnareb** [comment]
@hamelsmu :  a [custom merge-driver](https://git-scm.com/docs/gitattributes#_performing_a_three_way_merge) in Git affects how three versions of a file are merged when a file-level merge is necessary during `git merge`, and other commands such as `git revert` and `git cherry-pick`.

You need to configure `*.ipynb` files to use custom merge driver in the `.gitattribute` file, for example:

```gitattributes
**/*.ipynb merge=ipynb
```

Then define the custom merge driver in the config, in the `.gitconfig` file, for example:

```gitconfig
[merge "ipynb"]
    name = custom merge driver for Jupyter Notebooks
    driver = nbdev_merge_driver %A %O %B
```

The `%A`, `%O` and `%B` in the above configuration are placeholders which are replaced with the names of temporary files when Git invokes the custom merge driver.
- `%O` is the ancestor version (merge base)
- `%A` is the current version (ours)
- `%B` is the merged version (theirs)

The merge driver is expected to leave the result of the merge in the file named with `%A` by overwriting it, and exit with zero status if it managed to merge them cleanly, or non-zero if there were conflicts.

Additional placeholders exists:
- ` %L` is the conflict marker size (i.e. the number of characters in `<<<<<<<`, `=======` and `>>>>>>>`)
- `%P` is the pathname in which the merged result will be stored (e.g. when renames).

Let's assume that the base version looks like this:
```ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

Let's assume that on main branch we have added the Markdown cell, and now the notebook looks like this:
```ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- quux"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

The other side also added the Markdown cell, but with different contents:
```ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Hello world!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```


The default built-in `text` merge driver (as opposed to built-in `binary` merge driver, which saves our version without any merge markers or any attempts at merging, and mark files as conflicted) adds conflict markers, that creates the following file - which is not a valid `*.ipynb` file:
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
<<<<<<< HEAD
    "- quux"
=======
    "Hello world!"
>>>>>>> side
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```


The custom merge driver could try to put merge markers inside cells, and not outside of them. I have not checked how for example [git-json-merge](https://github.com/jonatanpedersen/git-json-merge) or [**nbdime**](https://github.com/jupyter/nbdime) does it, but for this example the result could look like this, with conflict markers inside cell:
```ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<<<<<<< HEAD\n",
    "- quux\n"
    "=======\n",
    "Hello world!\n",
    ">>>>>>> side"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```
Perhaps it would be a good idea to add some tags to mark the conflict area explicitly.

-------

However, I don't currently have no idea what to do if there were some cells added, or one side added Markdown cell, and the other side added code cell, which currently results in the following merge result - which is not a valid Jupyter Notebook
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
<<<<<<< HEAD
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello world\n"
     ]
    }
   ],
   "source": [
    "print(\"Hello world\")"
=======
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Hello world!"
>>>>>>> side
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

**Comment by jnareb** [comment]
One **_simple_** solution could be for `nbdev_clean_nbs` to print a warning and exit when encountering invalid `*.ipynb` file, instead of crashing.

**Comment by jnareb** [comment]
The custom merge driver that [nbdime](https://nbdime.readthedocs.io/) provides, namely `git-nbmergedriver`, configured in the following way:
```gitconfig
[merge "jupyternotebook"]
        driver = git-nbmergedriver merge %O %A %B %L %P
        name = jupyter notebook merge driver
```
(there is also a full-fledged custom diff driver provided by nbdime, namely `git-nbdiffdriver`), produces the following merge result, with conflict markers as separate Markdown cells:
```ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- foo\n",
    "- bar\n",
    "- baz"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<span style=\"color:red\">**<<<<<<< local**</span>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- quux"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<span style=\"color:red\">**=======**</span>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Hello world!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<span style=\"color:red\">**>>>>>>> remote**</span>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

This is for the case in the next previous comment. It is admittedly a more generic solution, as it works even when one side added Markdown cell and the other added code cell.

**Comment by igorbrigadir** [comment]
As a user, i think nbdime as a default merge driver / tool would be ideal to have in nbdev

**Comment by jph00** [comment]
We already have that. It's called `nbdev_fix_merge`. It's not actually set up to integrate directly with git (although that would be nice to add) - for now you just have to call it manually.

**Comment by igorbrigadir** [comment]
I totally missed that `nbdev_fix_merge` existed, thanks!

**Comment by hamelsmu** [comment]
If I'm understanding the above conversation this issue should be closed as it seems `nbdev_fix_merge` is the solution to the issue raised.     Going ahead and closing this

**Comment by jnareb** [comment]
Using `nbdev_fix_merge` is a solution to a problem, but not to the issue of **bad user experience**! In my opinion CLI tools should never crash but rather show an error message (in addition to failing gracefully), especially if the problem is _not_ something exceptional. Tools that are run automatically should not crash in particular.

Does `pip` crash when given unexpected command, or when there is no Internet connection?

Therefore I don't think this issue is solved, and I think that it should be reopened.

The proper solution would, in my opinion, be the following:

- fail gracefully: when given unexpected input the `nbdev_clean_nbs` CLI tool should show an error message, and simply do not clean the notebook, and do not return error code, or crash - this would allow `git diff` to proceed, even if with degraded results (spurious changes)
- advise user: when given unexpected input and detecting Git merge conflict, `nbdev_clean_nbs` should advise user in a warning to use `nbdev_fix_merge` (or install 'nbdime')

In the future perhaps nbdev should install merge driver (`nbdev_fix_merge` could possibly be repurposed to do this) and perhaps also diff driver (in addition to textconv diff driver), or suggest installing 'nbdime' in the documentation. This way merge conflicts would be handled automatically.

**Comment by hamelsmu** [comment]
Ok thanks for explaining I'll let @jph00 comment (and possibly reopen)
