### ISSUE TITLE
Tutorial says there is no conda package for nbdev

### ISSUE THREAD

**Issue by flowirtz** [fastai/nbdev#340]
The [tutorial reads](https://nbdev.fast.ai/tutorial.html#Install-nbdev):
> There is not a conda package for nbdev, so you'll need to use pip to install it.

On the [installation page](https://nbdev.fast.ai/#Installing), however, it says:
> nbdev is on PyPI and conda so you can just run `pip install nbdev` or `conda install -c fastai nbdev`.

I'm pretty new to this conda/python/nbdev world or at least haven't used it for a while, but do I understand correctly that this is a mistake in the tutorial?

I'm very happy to (try to) fix it, just wanted to double-check I didn't misunderstand it.

**Comment by jnareb** [comment]
I have tried installing nbdev via `conda` (on MS Windows 10, with Anaconda3 Python distribution), and it didn't work correctly: all scripts like `nbdev_clean_nbs` (that are required for it to work correctly) were missing.

I have uninstalled conda package, and installed pip package, and it works.

**Comment by AyrtonB** [comment]
I use nbdev from a conda install and it works fine for almost everything but I've also encountered the same issue described by @jnareb where the CLI methods such `nbdev_clean_nbs` don't work unless I reinstall with pip.

**Comment by hamelsmu** [comment]
@jph00 is nbdev supposed to be conda installable?

**Comment by jph00** [comment]
Yes it is.

**Comment by hamelsmu** [comment]
I resolved conflicting information present in the tutorial via

![image](https://user-images.githubusercontent.com/1483922/103041291-d934ef00-452a-11eb-8a95-44398ed4d844.png)

**Comment by jnareb** [comment]
What about conda package not installing the CLI tools?

Also, the first part now mentions conda, but the detailed steps do not.

**Comment by hamelsmu** [comment]
> What about conda package not installing the CLI tools?

If that is an issue, would you mind opening a seperate issue for that?  Thanks so much!

> Also, the first part now mentions conda, but the detailed steps do not.

The detailed steps should probably only show 1 path but I'll make a change to clarify this even further!
