### ISSUE TITLE
Cells created in Colab not exported to script, while using pre-existing Jupyter created Notebooks

### ISSUE THREAD

**Issue by sheikmohdimran** [fastai/nbdev#343]
**Cells created in Colab not exported to script, while using pre-existing Jupyter created Notebooks**

We are using for nbdev for a project where people use a combination of Jupyter environment and Colab.
I loaded up an existing notebook (created in jupyter) in colab, and created new cells with relevant code. The tests passed. 

However, notebook2script does not export the cells that have been created in colab. They only export the cells created by Jupyter.

As a workaround, I had to duplicate the existing cells and change the contents to add/modify new code.

Steps to recreate:
1. Create nbdev setup in local server/pc using conda environment.
2. Create a sample notebook.
3. Commit to Github.
4. Clone the repository in google drive via colab.
5. Open the sample notebook in colab and add new cells with code.
6. Run notebook2script, the code from newly created cells will not be exported.

**Comment by hamelsmu** [comment]
@sheikmohdimran my understanding is that nbdev doesn't support developing directly in Colab (however there should be no problem running the code directly in Colab).  That being said @muellerzr has some workarounds to enable this for the very motivated.  

@muellerzr do you mind commenting on this issue with your workflow?  I'll go ahead and close this now.  

cc: @jph00
