### ISSUE TITLE
[Feature request] Add configuration to extension for differente languages

### ISSUE THREAD

**Issue by tyoc213** [fastai/nbdev#347]
The other day installed Julia and it added create new Julia file, which runs on nbdev. Then I just went to a nbdev project and added a new Julia notebook and it did output the file as .py file, but "it worked" no errors trhow.

So I think would be nice if the writing of files extensions could be handled from:

* inside a jupyter notebook
* from the main configuration

Sure, for compiled languages (which IIRC you can add to jupyter notebooks), people will still need to launch their compile process in the output directory... or maybe have a "build command" that is just launched after output of input files. But I think the first step would be to change the extension of files.

##### Why?

Well, there are lots of other languages who doesnt have a nice literate programming which help you keep in sync code and documentation.

If it add lots of issues on top of nbdev that is compatible with python, maybe not worth it to try to add "all possible languages", maybe only allow some little tweeks for similar envs to python which just require the extension maybe.

**Comment by hamelsmu** [comment]
I'm not sure that we can try to make nbdev language agnostic, there are lots of features that are specific to python.  Perhaps you could use a subset of these features with other languages, but I'm not sure this is something we want to claim.  

If someone is willing to share a working prototype with nbdev in another language, this would be a good conversation starter!  

Closing this issue.  cc: @jph00
