### ISSUE TITLE
including nbdev in requirements.txt causes build error in google app engine

### ISSUE THREAD

**Issue by hugocool** [fastai/nbdev#352]
In deploying a simple flask app (which uses a monkey patched version of nbdev.export2html) i included nbdev in the requirements file.
This causes a build error in google app engine:

`Step #1 - "builder": INFO     pip_install_from_wheels took 0 seconds
Step #1 - "builder": INFO     starting: pip_install_from_wheels
Step #1 - "builder": INFO     pip_install_from_wheels /env/bin/python3.7 -m pip install --no-deps --prefix /tmp/tmpnTFnIm/env /tmp/tmpVrtrNR/wheel/pip-20.3.3-py2.py3-none-any.whl --disable-pip-version-check
Step #1 - "builder": INFO     `pip_install_from_wheels` stdout:
Step #1 - "builder": Processing /tmp/tmpVrtrNR/wheel/pip-20.3.3-py2.py3-none-any.whl
Step #1 - "builder": Installing collected packages: pip
Step #1 - "builder":   Attempting uninstall: pip
Step #1 - "builder":     Found existing installation: pip 20.1.1
Step #1 - "builder":     Uninstalling pip-20.1.1:
Step #1 - "builder":       Successfully uninstalled pip-20.1.1
Step #1 - "builder": Successfully installed pip-20.3.3
Step #1 - "builder": 
Step #1 - "builder": INFO     `pip_install_from_wheels` had stderr output:
Step #1 - "builder":   WARNING: The scripts pip, pip3 and pip3.7 are installed in '/tmp/tmpnTFnIm/env/bin' which is not on PATH.
Step #1 - "builder":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Step #1 - "builder": 
Step #1 - "builder": INFO     pip_install_from_wheels took 1 seconds
Step #1 - "builder": INFO     starting: pip_install_from_wheels
Step #1 - "builder": INFO     pip_install_from_wheels /env/bin/python3.7 -m pip install --no-deps --prefix /tmp/tmph6JqO3/env /tmp/tmpVrtrNR/wheel/pluggy-0.13.1-py2.py3-none-any.whl --disable-pip-version-check
Step #1 - "builder": INFO     `pip_install_from_wheels` stdout:
Step #1 - "builder": 
Step #1 - "builder": INFO     `pip_install_from_wheels` had stderr output:
Step #1 - "builder": /env/bin/python3.7: No module named pip
Step #1 - "builder": 
Step #1 - "builder": ERROR    error: `pip_install_from_wheels` returned code: 1
Step #1 - "builder": INFO     pip_install_from_wheels took 0 seconds
Step #1 - "builder": INFO     build process for FTL image took 103 seconds
Step #1 - "builder": INFO     full build took 103 seconds
Step #1 - "builder": ERROR    `pip_install_from_wheels` had stderr output:
Step #1 - "builder": /env/bin/python3.7: No module named pip`

any ideas on how to resolve this bug?

**Comment by hamelsmu** [comment]
@hugocool do you think this issue should be opened with the folks at Google?  I'm not sure this is an issue with nbdev, as you patched nbdev to do something specific (which we do not have access to), and then you are trying to use your patched version to interface with a third party tool that we do not support.  This might be a question that is better suited for the forums. 

However, if you do post on the forums, I would recommend providing a reproducible example that is public so someone may be able to help, and talk more about what you are monkey patching and why.   

Thanks cc:/ @jph00
