### ISSUE TITLE
TypeError: 'PosixPath' object is not iterable

### ISSUE THREAD

**Issue by FGhavamian** [fastai/nbdev#353]
When executing `nbdev_build_lib` I got this error: `TypeError: 'PosixPath' object is not iterable`.

I realized that the `read` function in `backports/configparser/__init__.py` does not handle a case where the path is of object `pathlib.PosixPath`. 

Looking at the `configparser` [package](https://github.com/jaraco/configparser/blob/ac8cb18fc75313d994e438c1c39ea2dcac9c2c05/src/backports/configparser/__init__.py#L730), I see that they handle such cases. It appears that nbdev is using a different version of the `configparser` package.

**Comment by hamelsmu** [comment]
@FGhavamian can you provide a way to reproduce your error?

**Comment by hamelsmu** [comment]
(sorry for closing this by accident, reopened now)

**Comment by FGhavamian** [comment]
The issue is not with nbdev. I write the conclusion here just in case. 
In my workplace, `apache-airflow==1.10.6` is used which requires `configparser >=3.5.0,<3.6.0`.
`fastcore` and consequently `nbdev` however, don't work with these old versions of `configparser`.
The solution is to have separate environments for `apache-airflow==1.10.6` and `nbdev`.
