### ISSUE TITLE
Does nbdev support ignore the part of `if __name__ == "main"`

### ISSUE THREAD

**Issue by BirkhoffG** [fastai/nbdev#354]
I have some code like this:

```
# cell
def train(param_1, param_2,...):
    ...

if __name__ == "main":
    train(...)
```

The `train` function is developed through nbdev in the notebook, and I want to write the main function directly in the python file without sync back to the notebook and cause conflicts. 

Does `nbdev` support ignore code in the python module without syncing back to the notebook? 

Thank you!

**Comment by hamelsmu** [comment]
I would suggest `call_parse` as demonstrated here instead:  https://fastcore.fast.ai/script.html#Example

if you really want to use `if __name__ == "main"` in a cell in the notebook and export that if you wish just like any other code.  But I suggest creating that cell in a notebook.   If you do this you will need something like this

```py
from fastcore.utils import in_jupyter
if __name__ == '__main__' and not in_jupyter():
  ...
```
