### ISSUE TITLE
nbdev searches for .ipynb in all subdirectories including hidden ones

### ISSUE THREAD

**Issue by BlackHC** [fastai/nbdev#357]
`nbdev_build_docs` for one searches for notebooks using `glob('**/*.ipynb')` which also collects hidden directories.

I'm using a Jupyter-Lab extension (https://github.com/krassowski/jupyterlab-lsp) which stores additional backups in a `.virtual_documents` folder, which lead to issues for me as they get picked up by `nbdev_build_docs`.

The current code in `nbdev_build_docs` ignores `.ipynb_checkpoints` specifically. Could this be expanded to ignore hidden directories in general?

Thanks,
 Andreas

**Comment by hamelsmu** [comment]
Are you using the latest version of nbdev?  

`nbdev_build_docs` filters out hidden directories with this line of code:

```py
    if fname is None:
        files = [f for f in Config().path("nbs_path").glob('**/*.ipynb')
                 if not f.name.startswith('_') and not '/.' in f.as_posix()]
```

I tested it and it does ignore hidden directories.   You can upgrade to the latest nbdev by cloning this repo and running pip install -e .   Alternatively I believe that `pip install -U nbdev` should work because this was a change made 4 months ago.

**Comment by BlackHC** [comment]
Thank you! I have the latest version installed. Please see below for links to code that has issues.

The following line causes issues with `nbdev_build_docs` (in master): 

https://github.com/fastai/nbdev/blob/7fcc358f9a4ab7709d0d5808bfb02a7456930eac/nbdev/export2html.py#L713

I've seen a similar issue in:

* `nbdev_read_nbs`: https://github.com/fastai/nbdev/blob/7fcc358f9a4ab7709d0d5808bfb02a7456930eac/nbdev/test.py#L130

* `nbdev_clean_nbs`: https://github.com/fastai/nbdev/blob/6c4934a2ddfa40ea27b5f229f21ee77aea1a479e/nbdev/clean.py#L83

* `nbdev_trust_nbs`: https://github.com/fastai/nbdev/blob/05b7a910044b3858217f240d6225c9a9e4f8a49d/nbdev/sync.py#L162

I hope this helps.

Thanks,
 Andreas

**Comment by hamelsmu** [comment]
cc: @jph00 looks like potentially we are trying to find notebooks using slightly different or repeated logic in different places.  Might be worth thinking about this, or also at least keeping this in mind for v2

**Comment by muellerzr** [comment]
@BlackHC can you try in the latest master build? @hamelsmu and I slightly touched on this, so the logic has been changed (and I think this was caught when we did this).

**Comment by hamelsmu** [comment]
This is still an issue it did not get fixed in what @muellerzr is describing

**Comment by hamelsmu** [comment]
Checklist for fixes as I make them

- [x] nbdev_build_lib

- [ ] nbdev_read_nbs

- [ ] nbdev_build_docs

- [ ] nbdev_test_nbs

- [ ] `nbdev_clean_nbs`

- [ ] `nbdev_trust_nbs`:

**Comment by JohannesStutz** [comment]
Unfortunately, I still have this problem. Running nbdev version 1.1.12 on Windows. Both `nbdev_build_docs` and `nbdev_build_lib` don't ignore the hidden `.ipynb_checkpoints` folder.

**Comment by JohannesStutz** [comment]
I just noticed: the problem does not appear when using `notebook2script` in-notebook. Only when calling `nbdev_build_lib` in the terminal.

**Comment by BlackHC** [comment]
Thanks so much for fixing this! Everything seems to work fine now.
