### ISSUE TITLE
VSCode Notebooks: Cells are not being exported due to CRLF and CR line endings

### ISSUE THREAD

**Issue by bybunni** [fastai/nbdev#365]
Cells marked `#export` with `CR` and `CRLF` line endings are not being exported. In the example json notebook below only the `LF_exports` function will be properly exported (Windows 10, Python 3.8). Ran into this with VSCode on Windows which will use `CRLF` in the Notebook Editor unless `Files: Eol` is set to `\n` in File->Preferences->Settings.

`{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# default_exp core"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# module name here\n",
    "\n",
    "> API details."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#hide\n",
    "from nbdev.showdoc import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "def LF_exports(arg):\n",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\r",
    "def CR_does_not_export(arg):\r",
    "    return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\r\n",
    "def CRLF_does_not_export(arg):\r\n",
    "    return"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {}
 },
 "nbformat": 4,
 "nbformat_minor": 2
}`

**Comment by hamelsmu** [comment]
This issue is being re-opened because of #432 we cannot just strip all CRLF/CR's from notebooks we have to be more thoughtful as that seems to break other things such as LaTeX.  

References: https://github.com/fastai/nbdev/issues/422 and https://github.com/fastai/nbdev/issues/427

**Comment by jakubLangr** [comment]
Any update on this? Seems to still be happening with `1.1.14`

**Comment by jph00** [comment]
Should be fixed in v2
