### ISSUE TITLE
Allow for a one-time only (potentially) .py -> .ipynb generation

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbdev#369]
Goal is to allow for quick and easy use/conversion from non-nbdev repositories into nbdev repositories. Will be looking into this

**Comment by hamelsmu** [comment]
Are you still working on this?  Should this be left open?

**Comment by muellerzr** [comment]
@hamelsmu I passively am. If you/Jeremy see enough value in it I can post my code here, otherwise I may develop it separately.

**Comment by hamelsmu** [comment]
Today I learned about [JupyText](https://jupytext.readthedocs.io/)

You can convert any python file to a JupyterNotebook with the command ` jupytext --to ipynb somefile.py`

In your directory with .py files you can run:

```bash
#!/bin/bash
for f in [^_]*.py; do # .py files except those with underscore in front
    jupytext --to ipynb $f
done
```
This will convert all python files to notebooks, excluding any file names that begin with an underscore!  Let me know if you want to keep this open, but I'll close for now!

**Comment by muellerzr** [comment]
@hamelsmu this is awesome! May write a blog post or something about this, great find!

**Comment by hamelsmu** [comment]
> May write a blog post or something about this, great find!

That's a great idea!  I particularly like your ideas you brought up in discord about building on this and inserting some additional nbdev things into the notebooks automatically for the user
