### ISSUE TITLE
Conda nbdev package is severely outdated, and and its script don't work on Windows

### ISSUE THREAD

**Issue by jnareb** [fastai/nbdev#372]
The "Installing" section of nbdev homepage documentation (<https://nbdev.fast.ai/#Installing>) says:

> nbdev is on PyPI and conda so you can just run `pip install nbdev` or `conda install -c fastai nbdev`.

However the conda version is severely outdated as compared to PyPI version: 0.2.40 on conda, 1.1.6 on PyPI.

Additionally the scripts provided by conda installation does not work on MS Windows:

```
> nbdev_clean_nbs
Program 'nbdev_clean_nbs' failed to run: No application is associated with the specified file for this operation
At line:1 char:1
+ nbdev_clean_nbs
+ ~~~~~~~~~~~~~~~.
At line:1 char:1
+ nbdev_clean_nbs
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by jnareb** [comment]
Note that for clean `nbdev` installation beside uninstalling `nbdev` installed via `conda`, one needs to uninstall also `fastcore` and `fastscript` packages installed as dependencies by conda before installing `nbdev` via `pip`.

**Comment by jph00** [comment]
nbdev latest is always automatically uploaded to anaconda:

https://anaconda.org/fastai/nbdev

MS Windows is not currently supported - sorry about that.

**Comment by jnareb** [comment]
@jph00 : I wonder why while the current version of `nbdev` is 1.1.11,  `conda install -c fastai nbdev` installs version 0.2.40. while `pip install nbdev` installs 1.1.6 (on MS Windows, using Anaconda Python distribution)...

It would be nice to have the fact that `nbdev` on conda is not supported on MS Windows explicitly said in the documentation.

**Comment by jph00** [comment]
OK I've added that information.
