### ISSUE TITLE
Tutorial maybe to be improved

### ISSUE THREAD

**Issue by j-k** [fastai/nbdev#373]
I did just my first steps in using this tool, so maybe it's not an issue but my wrong understanding. Following the tutorial the built docs did not show up. I had of course to "git add" the generated files, too (like index.html). But it only says:

You can now git commit and git push. Wait a minute or two for Github to process your commit, and then head over to the Github website to look at your results.

**Comment by hamelsmu** [comment]
Can you be more specific on how to the language can be changed to make it clearer for you?  

Also, after doing the minimal example (see the docs), you might want to make a PR to ammend the docs, this will be good practice for you in terms of using nbdev.

**Comment by muellerzr** [comment]
@hamelsmu I think this is along the lines of add in the fact we should add to use `git add *`, as some folks may have never used GH before, so it would be good for them to learn
