### ISSUE TITLE
Allow <img> tags to be indented.

### ISSUE THREAD

**Issue by ctwardy** [fastai/nbdev#375]
It seems nbdev won't convert _indented_ image tags, so the generated README and pages break on GitHub.

For example this in `nbs/index.ipynb`:
```html
<img src="images/Jacobs_logo_rgb_black.svg" width="200"/><img alt="Satellites Visible" src="images/starmap_new.png" width="300">
```

Generates this in `/README.md`, correctly rerouting the first image to `nbs/images`, but leaving the second looking in `images/` where it fails.

```html
<img src="nbs/images/Jacobs_logo_rgb_black.svg" width="200" style="max-width: 200px"><img alt="Satellites Visible" src="images/starmap_new.png" width="300">
```

Likewise, if you put these into a table to force side-by-side layout, neither converts.  `nbs/index.ipynb`:
```html
<table>
    <tr style="background-color:#FFFFFF">
        <td style="background-color:#FFFFFF">
            <img src="images/Jacobs_logo_rgb_black.svg" width="200"/>
        </td>
        <td><img alt="Satellites Visible" src="images/starmap_new.png" width="300"></td>
    </tr>
</table>
```

Generates `/README.md`:
```html
<table>
    <tr style="background-color:#FFFFFF">
        <td style="background-color:#FFFFFF">
            <img src="images/Jacobs_logo_rgb_black.svg" width="200"/>
        </td>
        <td><img alt="Satellites Visible" src="images/starmap_new.png" width="300"></td>
    </tr>
</table>


This was [diagnosed in the forum last June](https://forums.fast.ai/t/nbdev-fastpages-how-to-insert-images-side-by-side/73500/6?u=ctwardy). Zero-indenting seems to fix it.

**Comment by omlnaut** [comment]
It seems that the reason for this the regex in 03_export2html.ipynb:

```^(<img\ [^>]*>) #   Catching group with <img some_html_code> ```

This regex only captures the <img> tag if it's at the beginning of the line. There is a comment explaining this, which says:
> Beginning of line (since re.MULTILINE is passed)

I don't quite understand why enabling MULTILINE makes it necessary that the current pattern should start at a line beginning though. As far as I can tell removing the ^ character should fix the regex. I can't test this at the moment, it might break something further down the line.

**Comment by jph00** [comment]
Should be fixed in v2
