### ISSUE TITLE
The only supported license is apache2

### ISSUE THREAD

**Issue by jnareb** [fastai/nbdev#385]
In my opinion at least all licenses available in GitHub license chooser should be available: 

- Apache License 2.0 (the only one available, as `apache2`)
- GNU General Public License v2.0
- GNU Lesser General Public License v2.1
- GNU General Public License v3.0
- GNU Affero General Public License v3.0
- MIT License
- BSD 2-Clause "Simplified" License
- BSD 3-Clause "New" or "Revised" License
- ...

**Comment by hamelsmu** [comment]
Addressing this via https://github.com/fastai/nbdev_template/pull/42

**Comment by hamelsmu** [comment]
We have put some generic licenses now as you suggested in the template, as well as propagate whatever we can from settings.ini instead of failing if you want to use a license not already predefined. 

Thanks for opening this issue.
