### ISSUE TITLE
function reference URL in tip or note will break jekyll build

### ISSUE THREAD

**Issue by daviddemeij** [fastai/nbdev#40]
I discovered that when using a function reference URL in a `> note:` or `> tip:` it will break the jekyll build locally as well as on my Heroku app with the following exception:
```
Liquid Exception: Invalid syntax for include tag: content="The <a href="utils#example_func">The <code>example_func</code></a> does something ." Valid syntax: {% include file.ext param='value' param2='value' %} in utils.html
```
I confirmed this by removing one of the links (then it gave an error on the next one) and by removing both of them (solving the error).

I think this is caused by the double quotes in the url breaking the `content=" ... "`, maybe a solution would be to use single quotes in the translation of the urls to html. I will try this and make a pull request if it works.

**Comment by sgugger** [comment]
Fixed by #41
