### ISSUE TITLE
`> Note:` should support multi-line block quotes

### ISSUE THREAD

**Issue by alexlenail** [fastai/nbdev#402]
xref https://github.com/fastai/fastpages/issues/492

This (I think) entails editing the regex:

https://github.com/fastai/nbdev/blob/3e9546e62d319781a7855b31ae40f1ad07815086/nbdev/export2html.py#L105-L112

to allow for multi-line block quotes.

**Comment by hamelsmu** [comment]
I am not sure this is desirable and introduces ambiguities between new lines and what is supposed to be part of the Note block.  This kind of thing is better served with HTML or something similar that has an opening and closing tags that allow you to encapsulate the text you want to style a certain way.

There is a limitation on how far "Markdown" style things can be rendered, and isn't meant to be a wholesale replacement for HTML but just shortcuts for common use cases.  

I'm happy to discuss other ideas incase I'm missing something!  LMK your thoughts

**Comment by hamelsmu** [comment]
Spoke with Jeremy, we decided that this is not something we want to pursue for same reasons in my comment above.  Going ahead and closing this issue.
