### ISSUE TITLE
Idea: pre-commit hook support?

### ISSUE THREAD

**Issue by igorbrigadir** [fastai/nbdev#403]
Pre-commit hooks are extremely versatile, and widely used: https://pre-commit.com/ The general idea is that things are triggered and run automatically when you commit or push a change in a git repository.

`nbdev` already uses git hooks, so this is a suggestion to align a bit better with the pre-commit framework.

I've been toying around with using nbdev with pre-commit hooks in https://github.com/igorbrigadir/nbdev-api-template because things like the `nbdev_clean_nbs` and `nbdev_build_lib` etc scripts felt like they could be run automatically like this.

Some stumbling blocks i've encountered:

`nbdev_diff_nbs`: is too strict in highlighting changes in code, especially when using auto formatters like black.

It also doesn't exit with an error if it does find changes - not sure if this is intended or not, because the github actions fail the run when changes are detected. Maybe a pre-commit hook is better for this?

I've often wasted a lot of time waiting for github actions to pass because i accidentally added an extra white space or something in a notebook.

A separate issue is how to deal with formatting in the notebook - there are plugins for jupyter that may help, or maybe nbdev can format things by default?

`nbdev_test_nbs`: this is a very useful thing that i've come to depend on as part of CI builds - specifying subsets of notebooks to run with `--fname` is very useful.

Unfortunately when using pre-commit hooks that passes all changed files as 1 parameter there's some messing you need to do with `xargs` to get it to work right. This isn't a big issue but it would be nice if the command line worked like other pre-commit supporting scripts - like `black` or `flake8` for example.

In an ideal world, i'd love a setup where i have a notebook that i make changes to, commit to git, and it will clean, export, test, the change in the background for me with pre-commit hooks.

There are a few separate issues in all of this, and a bunch of different small changes to nbdev will be needed to support pre-commit hooks properly but i'd love to hear your opinions:

Is this a good direction? Is it something worth supporting or should it be left for people to implement themselves?

**Comment by tcapelle** [comment]
this would be very nice

**Comment by hugocool** [comment]
Is there any established best-practice on how to integrate nbdev with pre-commit hooks?

**Comment by igorbrigadir** [comment]
I forgot i made this issue.. this is how i did it: https://github.com/igorbrigadir/nbdev-api-template/blob/master/.pre-commit-config.yaml

**Comment by hugocool** [comment]
thanks!

**Comment by jph00** [comment]
I think a better approach might be to use post-save jupyter hooks. We have one in nbdev now (see nbdev_install_hooks) so you can see how they work.
