### ISSUE TITLE
nbdev_new fails on calling the GitHub API without guidance

### ISSUE THREAD

**Issue by aronchick** [fastai/nbdev#404]
I've created a template repo and then cloned it locally:

```
https://github.com/aronchick/temp_notebook_repo
```

I mistakenly set it to private - but when I did "nbdev_new", I got the below error.

````````
Traceback (most recent call last):
  File "test_file.py", line 15, in <module>
    cli.nbdev_new()
  File "/home/daaronch/.local/lib/python3.8/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/daaronch/working_trash/nbdev/nbdev/cli.py", line 111, in nbdev_new
    branch = urljson(url_json)['default_branch']
  File "/home/daaronch/.local/lib/python3.8/site-packages/fastcore/net.py", line 122, in urljson
    res = urlread(url, data=data)
  File "/home/daaronch/.local/lib/python3.8/site-packages/fastcore/net.py", line 112, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
fastcore.basics.HTTP404NotFoundError: HTTP Error 404: Not Found
```
Ideally, you would still be able to pick up my local auth, and not have this problem. Regardless, it doesn't feel "natural" - doing something locally shouldn't have any impact based on what I've decided to do in the cloud (e.g. private/public).

It would be nice if the error notification was a bit cleaner. Here's a simple line I wrote - I couldn't do a PR because I couldn't figure out how to make all the pre-commit stuff work for the nbdev library or how to debug properly.

**Comment by hamelsmu** [comment]
I just fixed this in master.  You should get a clean error message now.  I didn't actually see this issue, I started working on it serendipitously when I realized this could happen so it's interesting that you raised the issue!  

cc: @jph00 

Also there are new docs 😄 I just added

![image](https://user-images.githubusercontent.com/1483922/105639232-e562e380-5e2b-11eb-81d4-59c6f939f18c.png)

**Comment by hamelsmu** [comment]
You will need to upgrade by

1. clone this repo
2. `pip install -e .`

**Comment by hamelsmu** [comment]
f

**Comment by hamelsmu** [comment]
Correction: you will not get an error message, it will try to gracefully use a default and warn you about it.  Also, support for private repos are now added.  BTW they released private GitHub pages as well recently.

**Comment by aronchick** [comment]
😍 thank you for the unbelievably quick response!


________________________________
