### ISSUE TITLE
nbdev_build_lib should auto create modules on first occurance

### ISSUE THREAD

**Issue by aronchick** [fastai/nbdev#405]
Rather than requiring a series of empty notebooks, it'd be great if when you use nbdev_build_lib, it auto created the backing python file on first occurance.

For example, let's say I have a simple notebook like this:
```
#default_exp core
print foo
---
# export first_function
print bar
---
# export second_function
print qaz
```

In this case, if I ran nbdev_build_lib, it'd create three python files. Today, I have to create two empty notebooks, each of which come first (alphabetically) and put `#default_exp first_function` and `#default_exp second_function` in each.

**Comment by hamelsmu** [comment]
_I edited the formatting of your comment so I could understand it_, just needed to place the psuedo code in block quotes.  

I think I vaguely remember that this will fail if you don't have an empty notebook for your module, so this is why you have to create the empty notebooks, correct?  

@jph00 is this something to address now or after / during v2?

**Comment by jph00** [comment]
Unfortunately I don't think this is possible using our current infrastructure.
