### ISSUE TITLE
Ruby 3.0.0 and Jekyll

### ISSUE THREAD

**Issue by lvwerra** [fastai/nbdev#406]
I ran into this issue when trying to serve the docs locally with Ruby 3.0.0:

https://github.com/jekyll/jekyll/issues/8523

Adding `gem "webrick"` to the `docs/gemfile` resolved the issue. Happy to create a PR but I am no Ruby expert so I don't know if this has downstream effects.

**Comment by igorbrigadir** [comment]
Out of curiosity, is this before or after the "upgrade" to docs: https://github.com/fastai/nbdev_template

>If you are using an older version of this template, and want to upgrade to the theme-based version, see this helper script (more explanation of what this means is contained in the link to the script).

https://gist.github.com/hamelsmu/977e82a23dcd8dcff9058079cb4a8f18

**Comment by lvwerra** [comment]
It is after the upgrade. I used the script to update my repo.

**Comment by hamelsmu** [comment]
GitHub pages [support 2.7.1](https://pages.github.com/versions/) so its best to downgrade your environment to maintain parity or use some kind of virtual environment to run this version for nbdev, as you want your local version to reflect the same environment in which the docs are hosted. 

I don't think this is something we are going to tackle right now as we are going to start using Hugo in the near future for nbdev.

cc: @jph00 incase I missed something.

**Comment by lvwerra** [comment]
Sounds good to me. I'll downgrade ruby, I wasn't aware of that requirement. Thanks for clarifying!
