### ISSUE TITLE
Not Found: http://0.0.0.0:4000/lib_name/module.html

### ISSUE THREAD

**Issue by josiahls** [fastai/nbdev#408]
I have a bug with a strange instance where index.htmls are being created in place of regular htmls. Note that: I can force the page to show the correct htmls via for example:
`http://0.0.0.0:4000/recipe_management/core/index.html`
works fine but is extremely weird. 

For example note that `_site` directory is wrong.:
```bash
docs
├── _config.yml
├── core.html
├── css
├── _data
├── data_model.html
├── feed.xml
├── fonts
├── Gemfile
├── Gemfile.lock
├── images
├── _includes
├── index.html
├── js
├── _layouts
├── licenses
├── manager.html
├── servers.html    # Notice that it is still correctly generating the html's here?
├── service.html    # Notice that it is still correctly generating the html's here?
├── sidebar.json
├── _site
│   ├── assets
│   │   └── css
│   │       └── style.css
│   ├── core
│   │   └── index.html
│   ├── css
│   ├── data_model
│   │   └── index.html
│   ├── feed.xml
│   ├── fonts
│   ├── Gemfile
│   ├── Gemfile.lock
│   ├── images
│   ├── index.html
│   ├── js
│   ├── licenses
│   ├── manager
│   │   └── index.html # Should just be manager.html for example
│   ├── servers
│   │   └── index.html # Should just be servers.html for example
│   ├── service
│   │   └── index.html   # Should just be service.html for example
│   ├── sidebar.json
│   ├── sitemap.xml
│   └── tooltips.json
├── sitemap.xml
└── tooltips.json
```
But the sidebar has the correct routes:
```json
{
  "some_service": {
    "Overview": "/",
    "Core": "core.html",
    "Data Model": "data_model.html",
    "Servers": "servers.html",
    "Manager": "manager.html",
    "SomeService": "service.html"
  }
}
```
I get a route not found error:
![image](https://user-images.githubusercontent.com/19930483/106063950-0abf4e00-60c7-11eb-8428-47db39c96246.png)

By nbs dir is:
![image](https://user-images.githubusercontent.com/19930483/106064556-119a9080-60c8-11eb-85e9-e289f662b674.png)

My nbdev version is: 
```bash
pip show nbdev 
Name: nbdev
Version: 1.1.12
Summary: Writing a library entirely in notebooks
Home-page: https://github.com/fastai/nbdev/tree/master/
Author: Sylvain Gugger and Jeremy Howard
Author-email: info@fast.ai
License: Apache Software License 2.0
Location: /miniconda/envs/master37/lib/python3.7/site-packages
Requires: nbconvert, pip, fastcore, jupyter-client, pyyaml, packaging, jupyter, nbformat, ipykernel
Required-by: 
```

I wonder if nbdev is somehow thinking that my notebooks are trying to specify submodules? But if so, why is the sidebar correctly showing they are flat?

**Comment by lvwerra** [comment]
I am having a similar issue. It works if I remove `.html` from the URL in the browser?

**Comment by hamelsmu** [comment]
Hmmm if by any chance you try to upgrade your nbdev to use the theme https://gist.github.com/hamelsmu/977e82a23dcd8dcff9058079cb4a8f18 

does that help?

**Comment by josiahlaivins** [comment]
It didn't change anything. I'm using docker btw, so I'm building from scratch everytime. I upgraded nbdev, copied the docs folder from nbdev_template:
![image](https://user-images.githubusercontent.com/55600928/106462149-b2d86c80-6463-11eb-814f-59241f64d7c9.png)
Rebuilt my image to use the new Gemfile,

And now I get:
`Liquid Exception: Could not locate the included file 'important.html' in any of ["/opt/project/recipe_management/docs/_includes", "/var/lib/gems/2.5.0/gems/jekyll-theme-primer-0.5.4/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in data_model.data_model.html`

when I try executing the jekyll server.

**Comment by josiahls** [comment]
It didn't change anything. I'm using docker btw, so I'm building from scratch everytime. I upgraded nbdev, copied the docs folder from nbdev_template:
![image](https://user-images.githubusercontent.com/55600928/106462149-b2d86c80-6463-11eb-814f-59241f64d7c9.png)
Rebuilt my image to use the new Gemfile,

And now I get:
`Liquid Exception: Could not locate the included file 'important.html' in any of ["/opt/project/recipe_management/docs/_includes", "/var/lib/gems/2.5.0/gems/jekyll-theme-primer-0.5.4/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in data_model.data_model.html`

when I try executing the jekyll server.

**Comment by hamelsmu** [comment]
You need to copy the entire nbdev template not just the docs folder

**Comment by hamelsmu** [comment]
Also see the readme of the template there is a script that helps you
upgrade the template as well

**Comment by hamelsmu** [comment]
I verified that copying or upgrading the template properly avoids this issue.  Please let us know if you continue to experience this error and will be happy to reopen.

**Comment by lvwerra** [comment]
@hamelsmu yes, I used the script to upgrade an existing project. do you have any idea what i could check do debug this?
