### ISSUE TITLE
conda package is too outdated

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fastai/nbdev#409]
I  tried to install the package from Anaconda from the fastai channel.
as in the readme
> conda install -c fastai nbdev

It seems to be too outdated.

> nbdev                  0.2.40               fastai

This would cause trouble [nbdev tutorial fails with new template](https://github.com/fastai/nbdev_template/issues/34)
I have experienced this combination of issues first hand

**Comment by hamelsmu** [comment]
Just updated this
