### ISSUE TITLE
#collapse_input is not working 

### ISSUE THREAD

**Issue by feras-oughali** [fastai/nbdev#410]
#collapse_input is not working.
example from docs:
https://nbdev.fast.ai/export2html.html#Collapsable-Code-Cells

I don't see any button or link to hide input.

**Comment by benoit-cty** [comment]
Hello, any news on this ?

It's really a nice feature.

**Comment by ayasyrev** [comment]
Use #collapse or #collapse_show

**Comment by benoit-cty** [comment]
Thanks, `#collapse` is working like `#collapse_input` :+1:

**Comment by benoit-cty** [comment]
If I understand well, the has to be updated, because https://nbdev.fast.ai/export2html.html#Collapsable-Code-Cells is different from the code at https://github.com/fastai/nbdev/blob/48b9acf6d6a96d211d0fe43ce9cb84bbc81613da/nbdev/export2html.py#L216

**Comment by kevinbird15** [comment]
I believe you can also use #collapse_hide to do the same thing as #collapse which would line up a bit better with the #collapse_show naming

**Comment by benoit-cty** [comment]
Yes, here is a [demo of the possibilities](https://documentation.leximpact.dev/leximpact_prepare_data/memo_style#Cacher-/-montrer) : In French Show=Montrer and Hide=Cacher.
