### ISSUE TITLE
How to install fastrelease_conda_package  

### ISSUE THREAD

**Issue by TejasAvinashShetty** [fastai/nbdev#411]
When making make_release the conda package fails to be produced.
I face this error.
>/bin/bash: fastrelease_conda_package: command not found
make: *** [Makefile:28: conda_release] Error 127

It seems to me that 'fastrelease_conda_package ' is not installed at my end.
But how do I do it?
I did not find any instructions in the example nor in the tutorial.

**Comment by hamelsmu** [comment]
Please reinstall nbdev by using the latest version

`pip install -U git+https://github.com/fastai/nbdev.git`

This will fix the problem.

**Comment by TejasAvinashShetty** [comment]
Thanks, @hamelsmu. Will try out when free.
