### ISSUE TITLE
nbdev_update_lib errors out when fname not supplied

### ISSUE THREAD

**Issue by RenzoBenemerito** [fastai/nbdev#415]
https://github.com/fastai/nbdev/blob/f8d6ed294425a6b306eeff09a640714dc5ed252d/nbdev/sync.py#L126

When doing nbdev_update_lib without specifying the optional fname argument, it fails with an error as shown below instead of traversing the lib path directory.

![image](https://user-images.githubusercontent.com/28670327/106884244-ffe66800-671b-11eb-8450-f21295b02c2d.png)

**Comment by RenzoBenemerito** [comment]
I think its caused by this commit [https://github.com/fastai/nbdev/commit/f2f4c32c385d3dc7920edd723d73f704bc00255d#diff-d8cd2fcd987f7884b494f7373cf50eb48cd2f925120114e153b08f779e326f95](url)

**Comment by hamelsmu** [comment]
> I think its caused by this commit https://github.com/fastai/nbdev/commit/f2f4c32c385d3dc7920edd723d73f704bc00255d#diff-d8cd2fcd987f7884b494f7373cf50eb48cd2f925120114e153b08f779e326f95

Is a broken link.  Also I cannot reproduce your error make sure you are using the latest version fo nbdev

pip install -U git+https://github.com/fastai/nbdev.git

**Comment by hamelsmu** [comment]
If upgrading doesn't fix it for you will be happy to reopen this issue please let me know.

**Comment by RenzoBenemerito** [comment]
> If upgrading doesn't fix it for you will be happy to reopen this issue please let me know.

The problem still persists, I already have the latest version of nbdev

![image](https://user-images.githubusercontent.com/28670327/106990702-be070180-67af-11eb-8fc2-17b53a1ee220.png)

I think we need to add a None checker before the if statement in the code. If the default of fname is None and you execute the if statement fname.endswith, it will cause the error seen above.

**Comment by hamelsmu** [comment]
Thanks.  I was testing the wrong command!  I was testing `nbdev_update_lib` instead 🤦🏽  sorry.   This is going to be fixed shortly via #416

**Comment by RenzoBenemerito** [comment]
> Thanks. I was testing the wrong command! I was testing `nbdev_build_lib` instead 🤦🏽 sorry. This is going to be fixed shortly via #416

Thank you sir! 💯
