### ISSUE TITLE
Auto UTF-8 encoding of docs/*.html files when running nbdev_build_docs

### ISSUE THREAD

**Issue by AlanGanem** [fastai/nbdev#417]
I'd like to have some performance infos about my functions displayed in my docs, using `%%timeit` magic key. Turns out the 𝜇 char displayed in my notebooks are not UTF-8 decodable and It seems like jekyll doesn't handle non UTF-8 chars in html files automatically.

it would be nice to automatically UTF-8 encode the .html files generated when running `nbdev_build_docs`

**Comment by hamelsmu** [comment]
Hi @AlanGanem 👋🏽 

If you remove all non-utf8 characters does that solve your issue?  It would be nice to get an idea of the workaround you tried (if any) as that may be helpful for us to think about when exploring solutions.

**Comment by AlanGanem** [comment]
Hey there @hamelsmu , thanks for the reply!

Yes, it does solve the issue. There are issues when displaying the html, becaus the solution i came up with is quite simple and overrides the non utf-8 decodable chars for a <?> char, although i think this is the expected beahviour.

i've added two functions to nbdev_build_docs.py script:

`
def utf8encode(file_path):
	'''
	encodes a file to utf-8
	'''	
	with open(file_path, 'r+', encoding='utf-8', errors = 'replace') as file:				
		file.write(file.read())
		file.truncate()
	
	print(f'Converted {file_path} to utf-8 decodable')
	return	

def get_html_paths(roots):	
	'''
	gets path of html files recursively starting from root in roots(list of roots)
	'''
	assert isinstance(roots,(tuple,list,set))
	all_files = []
	for root in roots:
	    files = glob.glob(f'{root}/**/*.html',
	                      recursive=True)
	    all_files += files if type(files) != str else [files]

	return all_files
`

And called them during the script call:

`
if __name__ == '__main__':
	#make html files utf-8 decodable
	paths = get_html_paths(['docs'])
	for path in paths:
		utf8encode(path)
	
	sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
	sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_build_docs')())
`

**Comment by jph00** [comment]
Should be fixed in v2
