### ISSUE TITLE
Best practice for exporting to top-level namespace?

### ISSUE THREAD

**Issue by will-henney** [fastai/nbdev#419]
Hi,

I was working through the tutorial and example project, and I have a (possibly dumb) question: what is the recommended way to export code into the top-level namespace of my library?  In the examples, if I define a function in `00_core.ipynb` then it will be accessible as `mylib.core.myfunc()`, whereas I want it to be available as `mylib.myfunc()`.  Normally, I would add an import to  `__init.py__` to achieve this.   How should it be done in nbdev?

Thanks

Will

**Comment by will-henney** [comment]
So, I think I might have worked out the answer, which is to edit `__init__.py` as in a regular library, right?  I had initially been wary of editing any of the `.py` files, since I assumed they were all auto-generated and vulnerable to being clobbered.  But I now see that `__init__.py` does not have the warning line at the top of it, so I am hoping it is safe to edit.  Apologies if this is not the right forum for usage questions.

**Comment by hamelsmu** [comment]
Yes you can add things to `__init__`, however, a convention we have used is to add an `all.py` file with all the things we want in it.  You can do that as well if you like.  We create that manually.  Example: https://github.com/fastai/nbdev/blob/master/nbdev/all.py

Hope that helps!
