### ISSUE TITLE
Math in Markdown

### ISSUE THREAD

**Issue by juansensio** [fastai/nbdev#42]
Hi. I am using nbdev to develop my library and everything works fine except for the rendering of math in the README.md. It looks ok in the documentation, but it is not rendered in Github's README.md (the $$ signs still appear). I can see you have the same issue in your very own REDME.md. Are you aware of this issue ? Thanks.

**Comment by ofou** [comment]
The math rendering on github is currently unsupported as explained on [this](https://github.com/github/markup/issues/897#issuecomment-326506820) thread and [re-opened](https://github.com/github/markup/issues/1294) on the Github's markup issues.
