### ISSUE TITLE
How to adjust `nbs_path` to reflect clean, robust package structure

### ISSUE THREAD

**Issue by lazarillo** [fastai/nbdev#420]
I have gone through the tutorials, and I am really excited about `nbdev`. I am not sure if it is faster/better than my current workflow, but I see that it has the potential to be far better once I know it better and once it matures further.

I am therefore interested in understanding if I am using the folder structure properly.

I would like to have a separate folder where the notebooks live.  I understand that I can do this via setting `nbs_path`.  But I cannot seem to get any *depth* to the folder structure.  If I just take the simple example with the cards, I would like to have a structure something like this

```bash
.
├── carddeck
│   └── __pycache__
├── docs
│   └── _data
└── notebooks
    ├── card
    └── games
```

where `notebooks` is my `nbs_path` where I want all of the notebooks to live with the "actual work".  Within that folder, I have sub-folders `card` where the `Card` class lives, but where a function like `deal` might live.  I would also want a folder `games` that would have Blackjack, Texas Hold 'Em, whatever.

I do not understand how I can get the `nbs_path` in the `settings.ini` file to recognize this hierarchy.  When I run `nbdev_build_lib`, it does not recognize anything not in that top `notebooks` level.  I tried to use wildcards in several different ways, but could not get it to recognize anything.

How do I have *depth* recognized in the `nbs_path`?

---

Possibly related: I do not understand the purpose of separating the `index.ipynb` file from the rest.  Am I supposed to create all of my notebooks, then pick & choose what I want to copy & paste into the final documentation?  I was hoping there would be a way to have a menu recognize all of the sub-pages.  For instance, using my example above, there would be a menu link in the documentation that would show `card` and `games`.

I understand I am new, but it seems very hard to make things that are large in size. What am I missing?  Are there good tutorials covering this?

**Comment by hamelsmu** [comment]
what if you sent `recursive = True` in `settings.ini`

**Comment by hamelsmu** [comment]
Closing this issue as I believe my answer re: recursive addresses this question.   `index.ipynb` generates the README.md (this is mentioned in the docs).  All your notebooks become documentation, not just the index.ipynb.  

(I suggest breaking up your issues into different ones, rather than one large Q/A if it turns out you have additional follow-up questions that are not related to the folder depth).

**Comment by lazarillo** [comment]
Hi @hamelsmu , OK, I will try with the `recursive = True`.  I forgot to follow up on this until now.  I will try this week and see if that solves it.  Sounds like you are confident it will.  :)
