### ISSUE TITLE
Broken links to source code when there are dunder methods

### ISSUE THREAD

**Issue by LucaPapariello** [fastai/nbdev#421]
### General comment
I went through the [tutorial](https://nbdev.fast.ai/tutorial.html) and [minimal example](https://nbdev.fast.ai/example.html) to learn more about nbdev (IMO it's a very cool library!). The example is where I ran into some problems that I couldn't solve.

### Bug description
I created a new [project](https://github.com/LucaPapariello/nbdev_cards) to replicate the steps of the nbdev example. The links to source code in the documentation of the `Deck` [module](https://lucapapariello.github.io/nbdev_cards/deck.html) are all correct, while those of the `Card` [module](https://lucapapariello.github.io/nbdev_cards/card.html) only partially. The link to the Card class is fine, while those to the two special methods are broken.

### Expected vs. actual behavior
The file `docs/card.html` should contain the right link to source code (e.g. `href="https://github.com/.../card.py#..."`), but it contains `href="__main__.py#L..."` (see e.g. [here](https://github.com/LucaPapariello/nbdev_cards/blob/fbe2ce8e3d6f430d417d479bfaa0bd277d2a190d/docs/card.html#L146)).

The [official example](https://github.com/fastai/deck_of_cards) has the same issue. The links to the Deck [module](https://fastai.github.io/deck_of_cards/deck.html#Deck) are fine (when substituting `hamelsmu` with `fastai`), but those in the Card [module](https://fastai.github.io/deck_of_cards/card.html) are not. The link to the `.__eq__` method is broken (see [this line](https://github.com/fastai/deck_of_cards/blob/651181e82d7b14df15d6ea3ebd19420ec8faad5d/docs/card.html#L177) in the html file).

**Comment by hamelsmu** [comment]
Yes this is a bug.  I can confirm that this is wrong in the official example as well. 

https://fastai.github.io/deck_of_cards/card.html#Card.__eq__

**Comment by TejasAvinashShetty** [comment]
Is this similar to [#36 in nbdev_templae](https://github.com/fastai/nbdev_template/issues/36) @LucaPapariello @hamelsmu

**Comment by LucaPapariello** [comment]
Thank you for pointing out this possible connection between the two issues. 

I'm not sure this is the same though, as you mention that the "source link for any piece of code" is broken. The issue I reported is a bit more specific: links to source code seem to be mostly fine, except for those of special/dunder methods defined in the `00_...` notebook. All the links appearing in [Deck](https://lucapapariello.github.io/nbdev_cards/deck.html) are indeed correct, and the first one in [Card](https://lucapapariello.github.io/nbdev_cards/card.html) is as well.

**Comment by hamelsmu** [comment]
> Is this similar to #36 in nbdev_templae @LucaPapariello @hamelsmu ?

No AFAIK that issue was a user error, was not a real issue.  Thanks

**Comment by hamelsmu** [comment]
To clarify this is only happening for dunder methods, everything else appears to be fine

**Comment by jph00** [comment]
Should be fixed in v2
