### ISSUE TITLE
Carriage returns being inappropriately stripped, ex:  LaTeX \right to \night

### ISSUE THREAD

**Issue by lewtun** [fastai/nbdev#422]
Hello,

When running `nbdev_clean_nbs` all my `\right` LaTeX commands in Markdown cells are getting converted to `\night` which breaks the LaTeX syntax and doesn't render in the docs.

**Steps to reproduce:**

1. Run `nbdev_new` to create a new project
2. Edit the `index.ipynb` notebook to include a Markdown cell with the following LaTeX equation
```
$$\left(a + \frac{b}{c} \right)$$
```
3. Run `nbdev_clean_nbs`
4. Inspect `git diff index.ipynb`

**Expected behaviour**

`nbdev_clean_nbs` preserves LaTeX parentheses

**Actual behaviour**

From the `git diff`:

```
diff --git a/index.ipynb b/index.ipynb
index 31356b0..dd008d1 100644
--- a/index.ipynb
+++ b/index.ipynb
@@ -74,6 +74,13 @@
     "1+1"
    ]
   },
+  {
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
+    "$$\\left(a + \\frac{b}{c} \\night)$$"
+   ]
+  },
   {
    "cell_type": "code",
    "execution_count": null,
@@ -90,5 +97,5 @@
   }
  },
  "nbformat": 4,
- "nbformat_minor": 2
+ "nbformat_minor": 4
 }
```

**System info**

- `nbdev` version: 1.1.12
- Platform: Darwin-20.2.0-x86_64-i386-64bit
- Python version: 3.7.7

**Comment by hamelsmu** [comment]
@muellerzr mind taking a look at this issue re: my comment in #355 about your CRLF cleaning PR?

**Comment by hamelsmu** [comment]
@muellerzr fastcore has an [in_colab](https://fastcore.fast.ai/basics.html#in_colab) perhaps  that may be helpful here?  

.... although I suppose someone could also try  do LaTex on Colab

**Comment by muellerzr** [comment]
@hamelsmu I think the solution may be to minimally replace `CRLF`. IE have the regex match:
`[\r\n]+` and replace it with `\n` rather than just all `\r`.
