### ISSUE TITLE
Unstripped notebook error

### ISSUE THREAD

**Issue by jcpayne** [fastai/nbdev#434]
I'm repeatedly getting the error "Detected unstripped out notebooks" when I push commits from my local repo to my Github repo; both repos were built on an nbdev template and the rest of the nbdev functionality works fine.  

I have run (and re-run) `nbdev_install_git_hooks` on my local machine (Mac/Intel), and have also run `nbdev_clean_nbs` several times, re-commited, etc.  I ran `conda update nbdev` but the nbdev version before and after was v1.0.18.   

Any advice or suggestions?  I've run into problems with the notebook stripping before.

**Comment by hamelsmu** [comment]
can you share a repo with files where this is occurring?

**Comment by jcpayne** [comment]
Hi Hamel, I just sent you an invitation (it's called trident_dev).

**Comment by jcpayne** [comment]
Hi Hamel,

It’s a private repo because we are analyzing images that have restrictions on them.  I sent you a collaborator invitation so you could have a look, but please don’t send the link to anyone else.  

 

I very much appreciate you taking a look!

 

John

**Comment by jcpayne** [comment]
I'm narrowing down the problem a bit; turns out it is a single notebook that is causing the trouble.  The notebook is like a fastai tutorial notebook, inasmuch as it contains no code.  Manually stripping out all output in that notebook via the Jupyter command "Clear all outputs" still results in an error, but if I delete the notebook entirely, the error goes away.

**Comment by hamelsmu** [comment]
It looks like I cannot reproduce this error.  I just cloned your repo and was able to run `nbdev_clean_nbs` which appears to clean all notebooks.  It looks like you resolved the issue on your own?  I also looked at your GitHub Actions log and tried to locate the notebook you were having issues with which appear to be `nbs/04_aml-pipeline-run-inference.ipynb`, I also tried getting that from your `dev_nbs` folder and running `nbdev_clean_nbs` and everything was properly stripped on that.

You can test this out yourself by 
1. calling `nbdev_clean_nbs`
2. Commiting the changes
3. calling `nbdev_clean_nbs`
4. running `git status -uno -s` -> this will tell you if the cleaning in step 3 changed anything, which it shouldn't since you have already cleaned things.    

If you try steps 1 & 2 and push the changes, you shouldn't receive any error.   If this is only happening when you don't do steps 1 & 2 this means that we have isolated the problem to your git hooks.  Can you do this testing and let us know?

**Comment by jcpayne** [comment]
Hi Hamel, I'm sorry, I should have told you a bit more.  As you noted, the single notebook `04_aml-pipeline-run-inference.ipynb` is the cause of the trouble.  I copied the directory structure of the fastai library when I created the repository:
- my code notebooks are in `/nbs` and that is the one which is processed during the `nbdev_build_lib` step
- I also have a directory called `/dev_nbs` where I put notebooks that are in development.  
 
I discovered that:
1. I could bypass the 'unstripped' error by moving the offending notebook to `/dev_nbs`(the nbdev hook tests still fail because of missing libraries, but they successfully get past the "unstripped" step).  
2. The "unstripped" problem returns if I move the notebook to `/nbs`.

**Comment by hamelsmu** [comment]
> could bypass the 'unstripped' error by moving the offending notebook to /dev_nbs(the nbdev hook tests still fail because of missing libraries, but they successfully get past the "unstripped" step).

I did the same thing, and could not reproduce the error.  Did you try pip installing the latest dev version of nbdev?

**Comment by jcpayne** [comment]
To be clear: the error appears when the notebook is in /nbs and NOT when it is in /dev_nbs.  I get an error every time.  
I'll try installing the dev version -- thanks for the suggestion.

**Comment by jcpayne** [comment]
OK, that fixed it!  Thanks so much.  Now if I just fix the library import problems, I'll have a working nbdev project :)

I really appreciate your help - thank you for sticking with me through it.

**Comment by jcpayne** [comment]
Hamel I'm now trying to pick up my previous nbdev question about installing complicated dependencies.  Since you also participated in that discussion, may I ask you one more thing?  Jeremy wrote " _Since nbdev just passes the string directly to pip, there's nothing we can do to support requirements that pip doesn't support_."  

I should have replied that pip _does_ support the requirement, both from the command line and inside a Dockerfile; for example, this works:  
`pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html`

but I haven't been able get it to run as part of the `requirements` line in `settings.ini`; I tried entering just the filename:  
`requirements = https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html` (plus other packages).

Would you have any idea what to try next?

**Comment by hamelsmu** [comment]
Thanks, glad that worked.
