### ISSUE TITLE
nbdev cli tools not installing on windows with conda

### ISSUE THREAD

**Issue by ashish-ram** [fastai/nbdev#436]
I am using conda on windows 10. I created a new conda env and installed nbdev via conda install. 
Then created a github repo from the template and cloned it to local. I can not run nbdev_install_git_hooks on the cli nor can I run any nbdev_ commands. What should I do to properly configure nbdev on windows. I don't think the documentation covers this clearly.

**Comment by hamelsmu** [comment]
@ashish-ram can you please provide some more information:

- Does pip work?
- Are you using WSL ?
- What are the exact setup step you used?
- Can you import nbdev in python?  `python -c "import inbdev"` ?
- What version of python are you using `python -V`

**Comment by ashish-ram** [comment]
@hamelsmu 
1. tried with both pip and conda
2. no, I am not using WSL. I am using the anaconda command prompt and windows cmd
3. I followed the instruction on the nbdev tutorial. (https://nbdev.fast.ai/tutorial.html)
4. import screenshots
![image](https://user-images.githubusercontent.com/6511786/109105368-ccfc2680-7753-11eb-9b2c-1cc4f39f25b2.png)
![image](https://user-images.githubusercontent.com/6511786/109105504-12b8ef00-7754-11eb-83fa-8a7a44f194b4.png)
5. python version : Python 3.6.12 :: Anaconda, Inc.

**Comment by hamelsmu** [comment]
@jph00 is it true that you must use WSL if you are going to use windows?   Are you familiar with this particular way of what this user is trying to do in Windows?

**Comment by roemeor** [comment]
I had the same issue on Windows 10 / Miniconda. The conda install does not seem to generate the .exe files for the cli commands. pip install works - the executables are created and the cli commands work, no WSL needed.

**Comment by jph00** [comment]
I'm not sure why the CLI tools aren't installing on Windows. @mszhanyi, do you have an idea?

**Comment by mszhanyi** [comment]
I tried that pip is OK but conda has issue.  Is there anything wrong on conda package?

**Comment by jph00** [comment]
I believe there's a problem with the conda package, yes. Not sure what the source of the problem is though.

**Comment by mszhanyi** [comment]
looks there's trouble creating a .exe file from a .py
![image](https://user-images.githubusercontent.com/16190118/109253316-7ca3c800-782a-11eb-8709-65698d992e56.png)

**Comment by ashish-ram** [comment]
@mszhanyi I have the same observation. It did not create the .exe files. 
Also, @roemeor and @mszhanyi, can you tell me how did you make nbdev work with pip? did you use pip inside a conda env or without any vertual env? I will be happy just to make it work somehow and play around for now.

**Comment by mszhanyi** [comment]
I use pip inside a conda env

**Comment by ashish-ram** [comment]
@mszhanyi, I was able to use "nbdev_install_git_hooks" using a pip. Thanks!
 Here are the steps I took,
`conda create -n myenv python=3.6
pip install nbdev `

**Comment by jph00** [comment]
@mszhanyi yup we are aware pip works - this issue is about why it doesn't work using conda. We could add something to the readme stating that conda/windows isn't supported, if we can't solve this...

**Comment by ashish-ram** [comment]
> @mszhanyi yup we are aware pip works - this issue is about why it doesn't work using conda. We could add something to the readme stating that conda/windows isn't supported, if we can't solve this...

I wonder if anyone has tried nbdev with conda in linux or in WSL environment. I have tried it only in wondows.

**Comment by jph00** [comment]
nbdev works fine in Linux and WSL with conda.

**Comment by philescandon** [comment]
I've tried many different configurations on my windows 10 machine.
Installing nbdev via conda would only work with python = 3.6 - same results as @ashish-ram.
`conda create -n nbenv python=3.6`
`conda install -c fastai nbdev`

I could install nbdev via pip with python 3.9
`conda create -n nbPIP`
`pip install nbdev`

Until the conda package is corrected - Windows users should just use pip to install nbdev to get a working system.

**Comment by barrypj** [comment]
I've been experimenting with the latest nbdev on Ubuntu and Windows, see #451 for a separate issue I had.  

When I try to run the nbdev_ commands from the Anaconda prompt on Windows I get messages telling me that the commands cannot be found.  The installer has placed them in the \Anaconda3\Scripts folder but these files do not appear to be set as "executable" so cannot be executed directly from the command-line.  My workaround is to run these scripts directly with python using commands like this from within my project folder (so you may need to adjust the path shown below based on where you run these commands from):

> python ..\..\Anaconda3\Scripts\nbdev_build_lib

> python ..\..\Anaconda3\Scripts\nbdev_build_docs

I'm working mainly on Linux, so am not clear how files are set to "executable" on Windows.  Perhaps this needs to be incorporated into the nbdev install mechanism?

**Comment by jph00** [comment]
@mszhanyi we need a way to create the installer directly from the Makefile with `make release` - we can't upload files manually that you provide here. Also, we need to support more python versions.

How did you go about creating that installer?

Maybe best to just submit the PR then I can test it directly?

**Comment by RichardScottOZ** [comment]
Same problem with conda when I tried it today.

**Comment by oleon6** [comment]
> I've been experimenting with the latest nbdev on Ubuntu and Windows, see #451 for a separate issue I had.
> 
> When I try to run the nbdev_ commands from the Anaconda prompt on Windows I get messages telling me that the commands cannot be found. The installer has placed them in the \Anaconda3\Scripts folder but these files do not appear to be set as "executable" so cannot be executed directly from the command-line. My workaround is to run these scripts directly with python using commands like this from within my project folder (so you may need to adjust the path shown below based on where you run these commands from):
> 
> > python ..\..\Anaconda3\Scripts\nbdev_build_lib
> 
> > python ..\..\Anaconda3\Scripts\nbdev_build_docs
> 
> I'm working mainly on Linux, so am not clear how files are set to "executable" on Windows. Perhaps this needs to be incorporated into the nbdev install mechanism/instructions?

I'm new to nbdev, very excited to get using it.  I have the same issue and workaround as @barrypj.  Wondering if this has been resolved?  (Apologies if this is not the write place/way to ask.)

**Comment by Wingmore** [comment]
Can confirm on windows, the executables are **not** created using `conda install -c fastai nbdev`. But is ok with `pip install nbdev`
