### ISSUE TITLE
docs_serve Makefile task limits jenkyll server to local access

### ISSUE THREAD

**Issue by fabraz** [fastai/nbdev#439]
When you use a container as your Jekyll server you might face some troubles reaching the application, since it denies any access other than local. 

I've run a container with the following command:
```shell
sudo docker run -p 4000:4000 -v /home/fb/code/nbdev:/home -id -d ubuntu:20.04
```

Then I've run make:
```shell
make nbdev_build_docs
```

In the host machine I could not manage to browse the url `http://localhost:4000`

To solve this issue, I just change the line 15, adding host parameter like this:

```shell
 cd docs && bundle exec jekyll serve --host 0.0.0.0
```

**Comment by hamelsmu** [comment]
The makefile is meant for local debugging.  If you are trying to run a Docker application we have [this docker compose file](https://github.com/fastai/nbdev/blob/master/docker-compose.yml) in this repo that configures the host as you mention.  

I'm not sure there is something that should be changed?

**Comment by fabraz** [comment]
Your concern makes sense to me, @hamelsmu! Let leave as it is. 

Don't you think it deserves a mention in the troubleshooting section? I guess other devs might find it useful.

Thanks!
