### ISSUE TITLE
Can't run make docs_serve due to ruby can't find gem bundler

### ISSUE THREAD

**Issue by NumesSanguis** [fastai/nbdev#443]
Following the steps under "View docs locally" to use Ruby with Jekyll:
https://nbdev.fast.ai/tutorial.html#View-docs-locally

# Problem
I ran into the issue when either calling `make docs_serve` or `bundle install` (Ubuntu 18.04):
```
$ make docs_serve
cd docs && bundle exec jekyll serve
Traceback (most recent call last):
	2: from /home/user/gems/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Makefile:15: recipe for target 'docs_serve' failed
make: *** [docs_serve] Error 1
```

After Googling for this error, it seems that nbdev was bundled with:
```
$ cd docs
$ cat Gemfile.lock | grep -A 1 "BUNDLED WITH"
BUNDLED WITH
   2.1.4
```
https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

Checking which version I had with `$ gem i bundler`, it turned out to be: `bundler-2.2.13`, which I got by following the steps under:
https://jekyllrb.com/docs/installation/ubuntu/

# Solution
Running `gem install bundler -v '2.1.4'` solved my issue.

# Next step
Could either:
- The documentation be updated that the command in the solution possible needs to be executed.
- Find a solution to have nbdev work with a newer version of gem bundler (I have no clue)?

**Comment by hamelsmu** [comment]
> Find a solution to have nbdev work with a newer version of gem bundler (I have no clue)?

That gem bundler is the one that is required because of GitHub pages.  

> The documentation be updated that the command in the solution possible needs to be executed.

When I follow the official instructions I get a newer version of bundler and am not able to reproduce your issue.  It is likely that it is your local environment that is causing this issue.   I know this works because it works in CI when I build-docs with nbdev on a fresh Ubuntu OS with CI.   

Let me know if you are able to reproduce this issue anywhere else.

**Comment by jakubLangr** [comment]
Just to clarify, I got the same error on Ubuntu 20.04 with `nbdev` version `1.1.14`.
