### ISSUE TITLE
Private repo pages fail due to unnecessary adding of repo_name/ to hyperlink (GitHub pages)

### ISSUE THREAD

**Issue by NumesSanguis** [fastai/nbdev#444]
Related forum post: https://forums.fast.ai/t/private-repo-pages-fail-due-to-unnecessary-adding-of-repo-name-to-hyperlink-github-pages/86453

Was not sure if this is a bug or me doing something wrong.

-----

Following a combination of the tutorial and example from the docs:
- https://nbdev.fast.ai/tutorial.html
- https://nbdev.fast.ai/example.html

# Private repo problem
I created a `deck_of_cards_nbdev` repository. The only change I made is that the repository is **private**.
When the repository is private, instead of getting a website link in the format of: `https://username.github.io/repo_name/`,
the format is: `https://random-name-64892e2e.pages.github.io/` (note the lack of **repo_name**).

The index page works fine, but when I for example click on "Card" in the menu, the page wants to navigate me to: `https://random-name-64892e2e.pages.github.io/deck_of_cards_nbdev/cards.html`.
Due to this appending of **deck_of_cards_nbdev**, the link does not work.

It should instead be: `https://random-name-64892e2e.pages.github.io/cards.html` (manually going here works).

# Question
How do I prevent this appending of "repo_name/" to all links on GitHub pages made from a private repository?

# Note
Locally (with `make docs_serve`) the links work fine: `http://127.0.0.1:4000/deck_of_cards_nbdev/cards.html`

**Comment by hamelsmu** [comment]
Instead of chaning settings.ini can you try changing the baseurl appropriately in `docs/config.yaml` ?

**Comment by NumesSanguis** [comment]
@hamelsmu Thank you for the suggestion. Changing in `settings.ini` the following:
```
doc_baseurl = /%(lib_name)s/
```
with
```
doc_baseurl = /
```
actually worked, but I forgot to rerun:
```
nbdev_build_lib
nbdev_build_docs
```
, hence the
> !!! Detected difference between the notebooks and the library
As I posted on the forum: https://forums.fast.ai/t/private-repo-pages-fail-due-to-unnecessary-adding-of-repo-name-to-hyperlink-github-pages/86453/3

**Comment by hamelsmu** [comment]
Thanks!  Glad this worked cc: @jph00 

I'll open a separate issue about adding documentation for this.
