### ISSUE TITLE
Add documentation for private pages

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#445]
You have to change `docs/_config.yaml` for private gh pages on enterprise per this issue #444 

We should add documentation for this.

**Comment by NumesSanguis** [comment]
Note that changing the following inside `settings.ini` (not `docs/_config.yaml`) is enough:
```
doc_baseurl = /  # before: /%(lib_name)s/ 
```
Just don't forget to rerun the `nbdev_build_docs` command.

This change is necessary because of the naming patterns when creating a website of a private repo: `https://random-name-64892e2e.pages.github.io/`

**Comment by jph00** [comment]
Should be fixed in v2
