### ISSUE TITLE
nbdev_build_lib fails with error on "docs/_data/topnav.yml" file.

### ISSUE THREAD

**Issue by barrypj** [fastai/nbdev#451]
On Ubuntu 20.10 and latest version of Windows 10, Anaconda installs **nbdev-0.2.40** when the **conda install -c fastai nbdev** command is used per the Tutorial's instructions.  When the **nbdev_build_lib** command is issued, it fails with an error on the "docs/_data/topnav.yml" file.  To fix this (on Ubuntu), I had to _force_ Anaconda to upgrade to the latest version of nbdev (1.1.13) with  this command: **conda upgrade -c fastai nbdev**.  I suspect this will also fix things on Windows 10, too.  You may wish to consider mentioning this in your docs.  An earlier reported issue, with the same problem, solved this by using pip instead on conda, but the **conda upgrade** command did the trick for me.

**Comment by barrypj** [comment]
I can confirm that the extra **conda upgrade -c fastai nbdev** command is also required on Windows 10.  Note that I am working with fresh installs of Anaconda Individual on both Linux and Windows in an attempt to mimic the steps/events most "newbies" might follow/experience here.  The Tutorial runs with no errors after the **upgrade** command is run.

**Comment by s-boardman** [comment]
Same issue and resolution for RHEL 7.9.

**Comment by hundertmark** [comment]
Same issue and resolution on macOS Big Sur (11.2.3)

**Comment by srishti-gupta-me** [comment]
> **conda upgrade -c fastai nbdev**.

Resolved with the above solution

**Comment by ChrisRichardMiles** [comment]
conda upgrade -c fastai nbdev.

Resolved with the above solution
on wsl after installing with conda.
