### ISSUE TITLE
Dealing with data files

### ISSUE THREAD

**Issue by aphecetche** [fastai/nbdev#462]
I'm struggling with the packaging of data files ... (somewhat similar to #258)

If I understand correctly (and please bare with me, I'm not a python expert) to package some data files in a "regular" (aka non nbdev) environment, one would  : 

- include the data files into the package directory : in nbdev I assume that would be the root dir (`nbs_path`)
- add `include_package_data=True` in `setup.py`: that is done by default by nbdev 
- add a `package_data={'': ['*pattern_to_data_file*']}` to `setup.py`
- use `pkg_resources` to locate the data file in the package files themselves (i.e. the ones using the data files)

so far I guess I was able to achieve the first 3 three points as after `make dist` my data file (the .root file) seems to be in the expected location : 

```
ar -zvtf dist/m2_exp_alice-0.0.9.tar.gz
drwxr-xr-x  0 laurent staff       0 11 avr 23:43 m2_exp_alice-0.0.9/
-rw-rw-r--  0 laurent staff    2838 11 avr 17:43 m2_exp_alice-0.0.9/CONTRIBUTING.md
-rw-rw-r--  0 laurent staff   11357 17 fév 01:39 m2_exp_alice-0.0.9/LICENSE
-rw-r--r--  0 laurent staff     140 11 avr 23:27 m2_exp_alice-0.0.9/MANIFEST.in
-rw-r--r--  0 laurent staff    1447 11 avr 23:43 m2_exp_alice-0.0.9/PKG-INFO
-rw-r--r--  0 laurent staff     478 11 avr 20:06 m2_exp_alice-0.0.9/README.md
drwxr-xr-x  0 laurent staff       0 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice/
-rw-r--r--  0 laurent staff      22 11 avr 23:35 m2_exp_alice-0.0.9/m2_exp_alice/__init__.py
-rw-r--r--  0 laurent staff     399 11 avr 23:35 m2_exp_alice-0.0.9/m2_exp_alice/_nbdev.py
-rw-r--r--  0 laurent staff     183 11 avr 23:35 m2_exp_alice-0.0.9/m2_exp_alice/clustering.py
-rw-r--r--  0 laurent staff     506 11 avr 23:35 m2_exp_alice-0.0.9/m2_exp_alice/mapping.py
-rw-r--r--  0 laurent staff  895136 11 avr 23:28 m2_exp_alice-0.0.9/m2_exp_alice/mch-mapping-run2-tree.root
drwxr-xr-x  0 laurent staff       0 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/
-rw-r--r--  0 laurent staff    1447 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/PKG-INFO
-rw-r--r--  0 laurent staff     459 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/SOURCES.txt
-rw-r--r--  0 laurent staff       1 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/dependency_links.txt
-rw-r--r--  0 laurent staff      20 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/entry_points.txt
-rw-r--r--  0 laurent staff       1 11 avr 20:07 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/not-zip-safe
-rw-r--r--  0 laurent staff      14 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/requires.txt
-rw-r--r--  0 laurent staff      13 11 avr 23:43 m2_exp_alice-0.0.9/m2_exp_alice.egg-info/top_level.txt
-rw-r--r--  0 laurent staff     687 11 avr 23:35 m2_exp_alice-0.0.9/settings.ini
-rw-r--r--  0 laurent staff      38 11 avr 23:43 m2_exp_alice-0.0.9/setup.cfg
```

But I'm completely at lost concerning the last point. If I try to use `pkg_resources` in my notebook I get a cryptic : 

```
NotImplementedError: Can't perform this operation for loaders without 'get_data()'
```

and if I try to bypass `pkg_resources` I can get my [notebook](https://github.com/aphecetche/m2_exp_alice/blob/nbdev/notebooks/mapping.ipynb) to access the file, but the pypi package can not...

Any advice on how to properly deal with data files would be most welcome :wink:

**Comment by michaelaye** [comment]
Same here, and this SO issue mentions some delicate differences between sdist and bdist_wheel in the comments: https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distutils 

Would be really nice if this could be added to the settings.ini and automatically added to the created setup.py. I just looked at setup.py's Modified date though, it's not been changed since long so i don't understand when it's being created; also, when I remove it, `make dist` doesn't work, so it doesn't seem to be dynamically created at all? I cannot find any dynamic setup.py creation in the nbdev docs either, so I'm now confused about that comment in the setup.py saying we should edit settings.ini and not setup.py.

**Comment by jph00** [comment]
please try forums.fast.ai for help
