### ISSUE TITLE
Idea: Add in return annotation to the documentation?

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbdev#463]
I'm playing around with return annotations in functions and seeing how they look/appear in the generated documentation. For example I could have something such as:

```python
def _format_func_doc(func, full_name=None):
    "Formatted `func` definition to show in documentation"
    try:
        sig = inspect.signature(func)
        fmt_params = [format_param(param) for name,param
                  in sig.parameters.items() if name not in ('self','cls')]
        return_anno = getattr(sig, 'return_annotation', '')
        link = get_source_link()
        return_anno = f"<code>class</code> {return_anno.__name__}" if inspect.isclass(return_anno) else return_anno
    except: 
        fmt_params = []
        return_anno = None
```
And have it generate something like:
![image](https://user-images.githubusercontent.com/7831895/114416684-8c773180-9b76-11eb-87d0-dfb3d8c061b0.png)

Source code looks like so:
```python
    @classmethod
    def load(cls, model_name_or_path: str) -> AdaptiveModel:
        """Class method for loading a constructing this tagger

        * **model_name_or_path** - A key string of one of Flair's pre-trained Token tagger Model
        """
        tagger = cls(model_name_or_path)
        return tagger
```

Thoughts @hamelsmu or @jph00 ?

**Comment by hamelsmu** [comment]
I think its a good idea to document all of a function's arguments.  Right now, I'm not sure there is a consistent way of doing this.  

One thing we should discuss is the docstring nomenclature.  Seems like you just have markdown in there, which seems fine but its worth discussing if anyone sees any other approaches?  i.e. should we try to render numpy docstrings or other formats of docstrings?

**Comment by muellerzr** [comment]
@hamelsmu the function arguments were just about what we were doing in this particular library. The important aspect here (imo) is documenting also if they include a return-type annotation (in raw python as it's consistent, ie the `->`)

**Comment by jph00** [comment]
Should be fixed in v2
