### ISSUE TITLE
Hyperlinks grouped with parentheses in README's subtitle

### ISSUE THREAD

**Issue by lewtun** [fastai/nbdev#464]
Hi folks,

I'm finding that hyperlinks and parentheses get grouped together in the README's subtitle which produces undesired output. For example, consider the following Markdown cell

**index.ipynb**

```
# Welcome to nbdev
> Create delightful python projects using [Jupyter Notebooks](https://jupyter.org/) and here is a parentheses (2021)
```

Running `nbdev_build_docs` produces

**README.md**

```
# Welcome to nbdev
> Create delightful python projects using <a href='https://jupyter.org/) and here is a parentheses (2021'>Jupyter Notebooks</a>
```

It seems that the opening and closing parentheses are getting mixed up (presumably from some regexp magic 😉 ). Note that I don't see this behaviour in other uses of `>` blocks, probably because the output isn't converted to HTML?

### Environment info

I'm using `nbdev==1.1.14` and python 3.9.2

**Comment by hamelsmu** [comment]
The mechanics of that specific noteblock actually get fed into a YAML file. 

If you are trying to add anything other than text it gets tricky really fast.  You can put raw HTML in the noteblock and it should render (not markdown).  Also enclose the noteblock in double quotes to escape special characters.

**Comment by lewtun** [comment]
thanks a lot for the explanation and tip re using raw HTML!
