### ISSUE TITLE
`@typedispatch` functions break documentation site

### ISSUE THREAD

**Issue by andrewtruong** [fastai/nbdev#471]
Issues:
1. `@typedispatch` functions do not render properly in the doc site:
![image](https://user-images.githubusercontent.com/15385696/115899346-a2191080-a42c-11eb-863e-2b3805f66fa6.png)

2. `@typedispatch` functions break the table of contents:
![image](https://user-images.githubusercontent.com/15385696/115899466-c543c000-a42c-11eb-85ba-dec064c3cc5a.png)

Minimal example:
```python
#export
from fastcore.all import typedispatch
from nbdev.showdoc import *

@typedispatch
def func(x:int):
    return x

@typedispatch
def func(x:float):
    return x

show_doc(func)
```

**Comment by andrewtruong** [comment]
To resolve issue 1: `func` should inherit `__name__` and `__doc__` from methods

**Comment by jph00** [comment]
Should be fixed in v2
