### ISSUE TITLE
A command for uploading to the test PyPi server?

### ISSUE THREAD

**Issue by tirthajyoti** [fastai/nbdev#472]
Can you guys add a command for uploading to the [Test PyPi server](https://test.pypi.org/) instead of the main one? Surely, this will reduce the clutter on the main server that many may complain about.

Of course, a separate set of credentials must be added to the config file by the user for this to work.

**Comment by tourdownunder** [comment]
Hi @tirthajyoti 

I made a few small changes to get this in tonight in https://github.com/tourdownunder/nbdev/pull/1. I was able to successfully with my gitlab repo that has a private package index.

What do you think?

**Comment by tirthajyoti** [comment]
Thx!
