### ISSUE TITLE
Dataframe not showing up clean in the Readme.md

### ISSUE THREAD

**Issue by tirthajyoti** [fastai/nbdev#474]
When I have a Notebook cell just with a single **Pandas DataFrame** in my `index.ipynb`, then the corresponding `Reademe.md` has **some of the HTML style code showing up extraneously**. For example, this kind of thing shows up [on my repo Readme](https://github.com/Tirthajyoti/mldsutils/tree/master/) before displaying the actual data table.

The `build_docs` generated HTML files [look fine](https://tirthajyoti.github.io/mldsutils/) though. 

```
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }
.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
```

**Comment by hamelsmu** [comment]
In the meantime, a workaround would be to render your dataframe as markdown in your notebook.  There are some ways to do this https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html

**Comment by tirthajyoti** [comment]
Thank you. I will try this.

**Comment by jph00** [comment]
Should be fixed in v2
