### ISSUE TITLE
Support determenistic builds

### ISSUE THREAD

**Issue by andaag** [fastai/nbdev#48]
Currently nbdev installs the latest versions of dependencies, so unless you put every transitive dependency in settings.ini which is quite cumbersome. You won't have deterministic builds.

I'd like to see support for systems that deal with this better. requirements.txt is probably the most used one, but I strongly favor pipenv personally. (https://pipenv.kennethreitz.org/en/latest/)

One way of doing this that should be fairly flexible is separating "how to install the dependency management tool + running it..". 
```
requirements = pipenv
requirements_cmd = pipenv install
```

Either that or supporting picking up a requirements.txt / Pipfile* files in the root directory.

**Comment by sgugger** [comment]
Hi there! We keep issues for known bugs only, so please use the [forum](https://forums.fast.ai/) for all feature requests. We can definitely think of how to make the dep management more flexible to support more use cases, and the forum would be a great place to gather community's ideas on how to do that best.
Closing this in the meantime.

**Comment by Elijas** [comment]
@andaag @sgugger Is there any progress on this? Any thread in the forum?
