### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by saurk** [fastai/nbdev#487]
It says that nbdev should work on 3.8 . But the moment I alter min_python = 3.6 to min_python = 3.8, I encounter errors that it's incompatible in GitHub Actions. How do I enable 3.8, is there a new nbdev_template that we need to use ?

**Comment by hamelsmu** [comment]
>  encounter errors that it's incompatible in GitHub Actions

Can you be more specific and provide a reproducible example?

**Comment by saurk** [comment]
It got solved , had to change the python version under github/workflow and
then in the config file. Thanks for the follow up.
