### ISSUE TITLE
say_hello function in tutorial.html needs to return f'Hello {to}!', not just print it

### ISSUE THREAD

**Issue by leifulstrup** [fastai/nbdev#49]
The say_hello function in tutorial.html needs to return f'Hello {to}!'

If not, the assert test throws an error.

**Comment by sgugger** [comment]
It does return that. Not sure what the issue is?

**Comment by leifulstrup** [comment]
Example say_hello function in the tutoial instructions has print as the last statement. When I run the assert test it fails. I revised the function to return the value after the print statement. The assert test now works. I think your example needs to be revised.

**Comment by sgugger** [comment]
Ah got it! Should be fixed now.

**Comment by coderbee** [comment]
Minor typo in nbs/tutorial.ipynb. Edit settings.init -> Edit settings.ini
