### ISSUE TITLE
nbdev_build_docs fails with import error for un-existing import line

### ISSUE THREAD

**Issue by anjayluh** [fastai/nbdev#491]
This is the error returned
An error occurred while executing the following cell:
------------------
from nbdev.showdoc import show_doc
from pyintegrators.twitter import *
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f63d9caafaed> in <module>
      1 from nbdev.showdoc import show_doc
----> 2 from pyintegrators.twitter import *

The cell was updated days ago to this but it still insists on the error

![image](https://user-images.githubusercontent.com/13086425/118947199-c8649a00-b95f-11eb-9286-0226580e00a2.png)

To replicate, write a wrong import line and run the nbdev_build_docs command then remove the line with the error and rerun the nbdev_build_docs command

**Comment by jph00** [comment]
Should be fixed in v2
