### ISSUE TITLE
How do I use nbdev for private, offline projects?

### ISSUE THREAD

**Issue by adamryczkowski** [fastai/nbdev#494]
Hi!

I would really want to give the nbdev a try for my next project. Unfortunately, I work in a corporate environment and the code I write is not public by default. The dependency on the Github/Gitlab seems pretty hard-wired to me. Where can I get an example of the `settings.ini` or the full workflow in general, that does not depend on putting my code into any external services?

This issue is pretty much a duplicate of https://github.com/fastai/nbdev/issues/446, which unfortunately got closed on non-substantive grounds.

**Comment by igorbrigadir** [comment]
I use nbdev with private repos (but on github).

I think as far as github requirements go, it's really only the docs and github actions that are github specific - which aren't critical to the rest of nbdev working.

You can still generate docs and host them elsewhere, or not at all, and github actions just run some checks using `nbdev_diff_nbs` and `nbdev_test_nbs`.

**Comment by adamryczkowski** [comment]
Thank you @igorbrigadir  for the answer. 

Do you happen to know, what should I put in the required fields of the settings.ini, that concern the Github-related functionality? The fields are marked as required in the official documentation of nvdev.

**Comment by igorbrigadir** [comment]
As far as i can tell, in https://github.com/fastai/nbdev_template/blob/master/settings.ini i don't think it matters what you put in, you can put whatever non github urls you like - nbdev itself will still work and generate scripts etc, if you're using a different git repo. Maybe the docs might break, and you may need some extra edits to get them deployed someplace in non github if you need.
