### ISSUE TITLE
nbdev_test_nbs fails with "preprocess() missing 1 required positional argument: 'resources' "

### ISSUE THREAD

**Issue by ericperez-01** [fastai/nbdev#497]
Running nbdev 1.1.14 on an M1 Apple Silicon mac (probably not relevant here). Nbconvert version 5.5.0.  Issue is that test.py in nbdev sends a single argument to the nbconvert preprocessor:

(line 84, test.py): ep.preprocess(pnb)

However, the nbconvert requires two arguments, including a missing dictionary. Quick fix is to send an empty dictionary:

(line 84, test.py): ep.preprocess(pnb,{})

This line fixes the issue, but I don't know if this will break the build for others.

**Comment by jph00** [comment]
Many thanks for the report
