### ISSUE TITLE
Best practice for using/loading data from a file for unit tests?

### ISSUE THREAD

**Issue by tijeco** [fastai/nbdev#498]
I have a few functions I would like to have unit tests for that require loading data from a file. What is the best way in nbdev to have it set up so that those files are included in the package and github CI is able to find to run the tests?

I've read through this (https://docs.python.org/3.4/distutils/setupscript.html#installing-additional-files) which goes over how to do something like this using regular setup.py utils. Is it possible to set `data_files` in `settings.ini` for this purpose?

Otherwise, what would be considered the best approach to accomplish something like this under the nbdev framework?

**Comment by jph00** [comment]
Please use forums.fast.ai for help
