### ISSUE TITLE
Using 'nbs_path' breaks nbdev_test_nbs

### ISSUE THREAD

**Issue by jib** [fastai/nbdev#503]
When using *nbs_path* in settings.ini like this, as suggested in the comment:
```
# Change to, e.g. "nbs", to put your notebooks in nbs dir instead of repo root
nbs_path = nbs
```

Means that ```nbdev_test_nbs``` [chdirs](https://github.com/fastai/nbdev/blob/master/nbdev/test.py#L113-L115) into that directory, and then executes the tests.

However, ```nbdev_build_lib``` generates the libraries in the repository root, meaning that that the test suite will not find the generated library:

```sh
$ nbdev_test_nbs
testing /drive/my_repo/notebooks/00_core.ipynb
testing /drive/my_repo/notebooks/index.ipynb
Error in /drive/my_repo/notebooks/index.ipynb:
An error occurred while executing the following cell:
------------------
#hide
from my_lib.core import *
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-16658a355e74> in <module>
      1 #hide
----> 2 from my_lib.core import *

ModuleNotFoundError: No module named 'my_lib'
ModuleNotFoundError: No module named 'my_lib'

Traceback (most recent call last):
  File "/path/to/virtualenv-E1lbfNIS/bin/nbdev_test_nbs", line 8, in <module>
    sys.exit(nbdev_test_nbs())
  File "/path/to/virtualenv-E1lbfNIS/lib/python3.9/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/path/to/virtualenv-E1lbfNIS/lib/python3.9/site-packages/nbdev/test.py", line 120, in nbdev_test_nbs
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: The following notebooks failed:
index.ipynb
```

The work around is to do an editable install of the built libs, or run with PYTHONPATH set: 
```sh
$ PYTHONPATH=`pwd` nbdev_test_nbs
testing /drive/my_repo/notebooks/00_core.ipynb
testing /drive/my_repo/notebooks/index.ipynb
All tests are passing!
```

The structural fix is [add](https://github.com/fastai/nbdev/blob/master/nbdev/test.py#L113-L115) the repo root dir to sys.path:
```python
import sys
sys.path.append(repo_root)
```

Unfortunately it wasn't clear to me where the code for computing the repo root lived, so I was not able to attach a patch right away.

**Comment by jph00** [comment]
This is documented here: https://nbdev.fast.ai/tutorial.html#Note-if-using-a-subdirectory-to-contain-.ipynb-files-instead-of-the-project-root .

(If you figure out how to avoid the issue entirely, we'd happily take a PR to do that.)
