### ISSUE TITLE
Git-lfs working with nbdev

### ISSUE THREAD

**Issue by simeneide** [fastai/nbdev#506]
Hi,
I am working on converting an existing repo into a nbdev repo to get the docs+pip "for free". So far, great experience.

However, as it is a data repo, I have added the data files using git lfs. Git lfs requires to add the relevant files to `.gitattributes` to function properly, however, the nbdev framework overwrites this and does not seem to allow me to re-add the needed attributes for git lfs. It fails saying the git status is not clean, but the same command works fine locally.

![image](https://user-images.githubusercontent.com/7136076/124452552-c6775e80-dd86-11eb-8988-999da7e29f0a.png)

The exact commit can be seen here:
https://github.com/finn-no/recsys_slates_dataset/pull/6/commits/8bba5fa32b102f25cbc6eeb837feae59cd6ceb6b

**Comment by jph00** [comment]
This should be fixed now.
