### ISSUE TITLE
nbdev_build_doc does not support foo.bar style libraries

### ISSUE THREAD

**Issue by jib** [fastai/nbdev#507]
Not all libraries are created in top level name spaces. In fact, one of the guidelines for corporations creating python libraries is to use [name space packages](https://packaging.python.org/guides/packaging-namespace-packages/) to avoid polluting the top level namespace. The general style of these packages is:

```python
mycorp.mylib.functionality
```

Which translates to the filesystem as:
```sh
$ROOT/mycorp/mylib/functionality.py
```

This layout IS supported in [settings.ini](settings.ini) using `lib_name` and `lib_path` respectively:
```ini
[DEFAULT]
lib_name = mycorp.mylib
lib_path = mycorp/mylib
```

And using these settings, `nbdev_build_lib` behaves as expected, and generates the `.py` files under `mycorp/mylib/`. However, `nbdev_build_docs` does not support this layout, and will fail:

```sh
$ nbdev_build_docs
converting: /repo/notebooks/99_nbdev_example.ipynb
'/repo/notebooks/99_nbdev_example.ipynb' is not in the subpath of 'repo/mycorp/' OR one path is relative and the other is absolute.
Conversion failed on the following:
99_nbdev_example.ipynb
Traceback (most recent call last):
  File /virtualenv/bin/nbdev_build_docs", line 8, in <module>
    sys.exit(nbdev_build_docs())
  File /virtualenv/lib/python3.9/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 643, in nbdev_build_docs
    if fname is None: make_sidebar()
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 708, in make_sidebar
    create_default_sidebar()
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 700, in create_default_sidebar
    dic = {Config().lib_name: _create_default_sidebar()}
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 692, in _create_default_sidebar
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 692, in <listcomp>
    titles = [_get_title(f) for f in fnames if f.stem!='index']
  File /virtualenv/lib/python3.9/site-packages/nbdev/export2html.py", line 682, in _get_title
    with open(fname, 'r') as f: code = f.read()
FileNotFoundError: [Errno 2] No such file or directory: '/repo/notebooks/docs/nbdev_example.html'
```

The issue is on this line: [nbdev.export2html:490](https://github.com/fastai/nbdev/blob/418cb79d7d009bc71ee826298592a9c5e8559f05/nbdev/export2html.py#L490), where the code explicitly goes *one* level up from `lib_path`:
```python
meta_jekyll['nb_path'] = str(fname.relative_to(Config().path("lib_path").parent))
```

As with [issue #503](https://github.com/fastai/nbdev/issues/503), the correct fix is to use `repo_root` here, instead of a single `updir`. Unfortunately, I still did not find where that is defined, or I'd have attached a patch.

For this issue, the work around is much more tedious though:
```sh
$ nbdev_build_lib
[edit settings.ini, and change lib_path from mycorp/mylib -> mycorp]
$ nbdev_build_docs
[edit settings.ini, revert the change]
```

**Comment by michaelaye** [comment]
Does this commit help?

https://github.com/fastai/nbdev/commit/52ab26a0fc65be6958037b10809480aa7e77f949#diff-2addd0a4d53dbf6a6583e07ef80ea27c4247f0d9af3487195800beb253711f54L1208-R1208

It looks like `os.path.relpath(nb_path, Config().config_file.parent)` gives you `repo_root` ?

**Comment by jph00** [comment]
Should be fixed in v2
