### ISSUE TITLE
Multiline string causes syntax error in _nbdev.py

### ISSUE THREAD

**Issue by remidomingues** [fastai/nbdev#523]
Hello team,

When generating python scripts from Jupyter notebooks using the following code snippet
```
from nbdev.export import notebook2script
notebook2script()
```
it seems multiline variables are not correctly handled. Say I have a notebook `nb_with_multiline_string.ipynb` which contains (at script level) the variable
```
var2 = '''just
a
value
'''
```
The index variable in the generated _nbdev.py file will contain a syntax error, thus blocking future lib installations:
```
index = {"var1": "nb1.ipynb"}": "nb_with_multiline_string.ipynb",
              "var2": "nb_with_multiline_string.ipynb"}
```
This issue has been observed on nbdev 1.1.22.

Best regards.

**Comment by remidomingues** [comment]
Similarly, using multiline strings (even if these are only comments) such as this one in a notebook:
```
"""
def a<b>():
"""
```
Will result in an invalid Python script containing:
```
__all__ = [
    "a<b>"
]
```

**Comment by jph00** [comment]
Should be fixed in v2
