### ISSUE TITLE
EOL incorrectly rendered in README.md on Windows

### ISSUE THREAD

**Issue by jfthuong** [fastai/nbdev#530]
When using nbdev on Windows, I got incorrect line endings in my README:

```
.... CR
CR LF
....
```

![image](https://user-images.githubusercontent.com/1401809/133989924-4185553f-a8ad-4e4d-84b6-1965a91d848c.png)

This creates extra empty lines that sometimes break the Markdown format (e.g. quote blocks, numbered bullet list, ...).

However, this works fine on Linux

![image](https://user-images.githubusercontent.com/1401809/133990041-560893db-b17e-4571-85a4-c71303bdf5a4.png)

**Comment by jph00** [comment]
Should be fixed in v2
