### ISSUE TITLE
Jupyter Import Enhancement

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbdev#532]
Idea for nbdev:  It’d be nice if nbdev had a way to import a notebook, instead of having to build the library if you update a dependency.

For example:  if I have 01.ipynb and 02.ipynb, with 02.ipynb requiring stuff from 01.ipynb.  

If I change notebook 01.ipynb, then I have to build the lib before 02 will be able to import the changes.  It would save a step if I could import 01.ipynb directly so I don't have to rebuild after each notebook change.  Then, whenever you build the library, the py module is rewritten to import the appropriate py file based on what the notebook generates.

Then as a next step it'd be cool if the build lib that creates the actual py files could be optional locally entirely and have that as a part of the CI/CD process when you push to github.

I think this falls apart if you have multiple notebooks creating 1 module, or vice versa, though I’ve never done that personally and do not know if that is an important feature for nbdev.  Maybe there could be a way around that, but I think it could get too complex and messy without a 1:1 notebook to module.

It looks like the import-ipynb pip library does jupyter notebook importing, but this would need to only run cells with proper nbdev flags.

**Comment by jph00** [comment]
I can't really think of a good way to do this, but feel free to reopen it if you're able to prototype a promising direction.
