### ISSUE TITLE
Documentation: Indicate supported Python versions

### ISSUE THREAD

**Issue by michaelaye** [fastai/nbdev#534]
Hi!
Thanks for your lovely tools.

I believe it would be great for dissemination to be upfront with the supported Python versions.
I fished out from a few issues like e.g. https://github.com/fastai/nbdev/issues/454 that 3.9 wasn't supported in April 2021.
Is that still the case? (A few trials seem to indicate that it still doesn't work).
I cannot find any statements about supported version in the docs, and I think to prevent new users from getting frustrated trying it, it would be good to clearly state them somewhere upfront in the docs.

If you let me know where this should appear I can submit a PR.

**Comment by michaelaye** [comment]
Oh, and another thing I'm not sure I understand: Is a py38 nbdev env able to safely compile a py39 package, if it doesn't use any new 3.9 features? Or are there things breaking underneath still?

**Comment by manuvazquez** [comment]
For me python 3.9.7 is fine despite having "declared" python 3.8 in settings.ini and.github/workflows/main.yml (I'm not using any python 3.9 feature). Anyway, it would be nice python 3.8+ official support.
