### ISSUE TITLE
Documentation Needed: nbdev_update_lib

### ISSUE THREAD

**Issue by muellerzr** [fastai/nbdev#538]
When addressing an issue today, I found out that to run `nbdev_update_lib` on a nested file, such as `fastai.vision.core` `recursive` **needs** to be set to `True` in your `settings.ini`.

cc; @jph00  and @hamelsmu, not sure if you two were aware of this behavior. Is this a bug? Or just document it

**Comment by muellerzr** [comment]
More on said issue, there also was an issue with relative paths. For example this did not work for an individual:
```python
nbdev_update_lib --fname $(pwd)'/foo/dags/etl_pyspark.py'
```
But this did:
```python
nbdev_update_lib --fname $(pwd)'/foo/dags/etl_pyspark.py*'
Converted dags/etl_pyspark.py.
```
Perhaps we need to update something with the nbglob in update_lib to support an individual filename?

**Comment by nglillywhite** [comment]
Hey @muellerzr, I'd love to help here but I also want to respect which direction you'd like. Do you want me to improve the docs to explain this behaviour or look into changing functionality to support relative paths and individual files, or both.... I can put together a PR depending on what you think is best.

**Comment by muellerzr** [comment]
Thanks for the offer! I mostly would like @jph00's input first, as I'm not 100% sure the original intention behind this and what would be best to do. From there you're more than welcome to :)

**Comment by jph00** [comment]
This is all being overhauled pretty thoroughly for nbdev3, so I'm not sure it's worth putting too much into this at this stage.

**Comment by nglillywhite** [comment]
Fair enough, I guess the issue can be closed? I'd love to contribute to nbdev3 if possible, based on the contribution guide, the suggestion is to look through open issues etc but I'm guessing the overhaul might be a closed activity. Either way, thanks Jeremy and Zach, happy to pick this up anytime if it becomes appropriate again.
