### ISSUE TITLE
Hi Jeremy: VS Code new Jupyter extensions - implications for nbdev?

### ISSUE THREAD

**Issue by Mjboothaus** [fastai/nbdev#540]
Hi @jph00 - hope you're doing well in Qld :)

See [https://code.visualstudio.com/blogs/2021/08/05/notebooks](https://code.visualstudio.com/blogs/2021/08/05/notebooks).

An excerpt:

### The future looks bright

> To complete the metaphor, notebooks in VS Code have matured from those awkward teen years into (young) adulthood, confident and strong, with a bright future. Working with VS Code notebooks may take a bit of adjustment if you are moving from Jupyter, but we hope it will be worth it in the end. And, as we always try to do, you can customize the experience through settings (search for @tag:notebookLayout in the Settings editor).

> We believe that expanding VS Code's rich coding experiences and ecosystem to include comprehensive Jupyter Notebook support makes for a great tool for bringing powerful new insights into your daily development.

and [DataSpell by Jet Brains](https://www.jetbrains.com/dataspell/)

**Just wondering what you think are the implications for `nbdev`**.

Cheers,
Michael @ DataBooth

**Comment by jph00** [comment]
We're hoping things will work fine in vscode
