### ISSUE TITLE
Feature request: defer evaluation of test cells until the end of notebook

### ISSUE THREAD

**Issue by Torvaney** [fastai/nbdev#541]
Hi all,

I would like to propose that nbdev defer evaluation of test cells until after the exported cells have been evaluated. I think that this would more accurately mimic the behaviour of other test suites (where source and test code live separately) and lead to less unexpected behaviour.

My reasoning is explained below by way of an example I recently came across when using nbdev with [Typer](https://typer.tiangolo.com/).

In one notebook, I had defined a command-line application with multiple subcommands with [Typer](https://typer.tiangolo.com/). After each subcommand, I had some tests to validate that the app was working as expected.

See the mini example below:

```python
# Cell 1

import typer
import typer.testing

# Cell 2

app = typer.Typer()

# Cell 3 (notebook only)

test_runner = typer.testing.CliRunner()

# Cell 4

@app.command()
def command1(file: typer.FileText):
    typer.echo('Do some stuff')

# Cell 5 (notebook only)

result = test_runner.invoke(app, ['command1' '-'], input='some input')
assert result.exit_code == 0
assert result.stdout == 'Do some stuff'

# Cell 6

@app.command()
def command2(file: typer.FileText):
    typer.echo('Do some other stuff')

# Cell 7 (notebook only)

result = test_runner.invoke(app, ['command2' '-'], input='some input')
assert result.exit_code == 0
assert result.stdout == 'Do some other stuff'
```

When running the app from the command line, it worked as expected. However, when running `nbdev_test_nbs`, it failed!

The reason for this was that the app (`typer.Typer()`) behaves differently depending on how many subcommands have been added. When only one command exists, that is the only entrypoint to the app and thus no subcommand needs to be specified in the cli. When more than one exists, you need to specify the subcommand.

`nbdev_test_nbs` runs the notebook cells sequentially. This means that Cell 5 (in the example above) is run before the second subcommand (defined in Cell 6). Therefore the application behaves differently to how it is expected to run in real life. This isn't good for testing.

In this specific example, I was able to workaround this issue by adding a new, dummy subcommand before Call 5 that is not exported (i.e. only defined when testing).

An alternative, and more general workaround for similar issues would be to move all testing code to the end of the notebook, so that it's only run once all the source code has been defined. However, this undermines one of the key selling points of nbdev, in which the source code and tests exist together, providing contextual information to one another.

A more solid solution that I would like to propose is altering the order of evaluation of the notebook cells when the tests are run. I am uncertain about the best implementation and/or user interface for this. It could be done by default (i.e. _all_ non-exported cells run after the exported ones when the tests run), or non-default order of test execution could be managed by additional flags.

I think the former makes sense, and as far as I can tell, well-constructed notebooks shouldn't suffer unexpected consequences from the change: 

> Everything that is not an exported cell is considered a test, so you should make sure your notebooks can all run smoothly (and fast) if you want to use this functionality as the CLI.

But I can understand wanting to keep the default behaviour consistent for the sake of avoiding extra hassle for existing users.

Thanks

**Comment by jph00** [comment]
We prefer the tests to run just like the notebook runs, so we're not likely to make this change, sorry.
