### ISSUE TITLE
FR: nbdev-slim option?

### ISSUE THREAD

**Issue by KaeganCasey** [fastai/nbdev#546]
Hello,
I love nbdev so much and would love to use it more but I am rarely developing packages for pip or conda and don't need separate documentation from my notebooks. It would be amazing if there was a slimed down version of nbdev that people could use for data science projects and experiments that don't necessarily result in a package being created at the end of it all. Hopefully this could eliminate a lot of the setup involved in the settings.ini file as well. I have seen another project called nbdev-minimum but it would be great to have an official version from you that supports mainly converting notebooks to .py files automatically using the provided flags.

This is my first time creating a feature request or issue on github so apologies if I am not following the appropriate format or posting in the proper place.

**Comment by joLahann** [comment]
I would also appreciate that. It would be nice if you could have options in the settings.ini to disable/enable features such as documentation or github integration.

**Comment by jph00** [comment]
nbdev2 will provide exactly that! :)
