### ISSUE TITLE
nbdev_test_nbs failing with nbdev 1.1.23

### ISSUE THREAD

**Issue by filipj8** [fastai/nbdev#547]
Hello,

I'm getting an error in github actions with the latest version of nbdev (1.1.23) during the `Run tests` step:
`[Errno 17] File exists: '/home/runner/.ipython'`

The github actions definition  by default installs the latest version of nbdev under the `Install the library` step. Removing that and pinning nbdev to 1.1.22 got the CI working again.

I'm unable to reproduce the error locally, could interactions with the github actions `checkout@v2` or `setup-python@v2` used in `main.yml` be causing this behavior?

**Comment by jph00** [comment]
I'm not sure, sorry - it's hard to know what to suggest without a repro.
