### ISSUE TITLE
home_sidebar does not work properly

### ISSUE THREAD

**Issue by hdocmsu** [fastai/nbdev#548]
Hello, 

Thanks for building the nbdev!

The sidebar (navigation on the left side of the page) looks fine at the Overview (https://fastai.github.io/deck_of_cards/), but when I click on either Card or Deck (https://fastai.github.io/deck_of_cards/deck.html) the sidebar is minimized. It is not a big issue if there are only 1 or 2 items in the sidebar, but it would be inconvenient if there are 5-10 items.

Note that the sidebar works perfectly on the nbdev document page.
https://nbdev.fast.ai/
https://nbdev.fast.ai/sync.html

If possible, please config the nbdev_template so that the sidebar is properly displayed.

Thanks.

**Comment by jph00** [comment]
Should be fixed in v2

**Comment by hdocmsu** [comment]
Thanks a lot, Jeremy, for the heads up. I look forward to trying nbdev v2 when it is officially released!
