### ISSUE TITLE
Add suport for documentation versions

### ISSUE THREAD

**Issue by Carloscerq** [fastai/nbdev#552]
Hi, I think that maybe a great addiction to nbdev would be some kind of support for multiple versions of the documentation. 

This way he could have in docs something like:

```
 Project
└───Current version
│   │   File One
│   │   etc.
│   
└─── Version X.Y.Z
│   │   File One
│   │   etc.
```

**Comment by jph00** [comment]
Sounds great, but not on our todo list at the moment, sorry.
