### ISSUE TITLE
Add an option to export converted doc notebooks to Markdown

### ISSUE THREAD

**Issue by lucharo** [fastai/nbdev#553]
Hi, I am using nbdev within a GH Enterprise instance and find it quite hard to be used because lots of nbdev and nbdev_template (and github pages more widely) seem to be perfectly tailored for public GH but not for the enterprise counterpart (access to remote theme as the main example)

I am trying to work around nbdev to still use the excellent features that allow to make a python module out of nbs but I am trying to use nbdev docs with a custom theme. I haven't seen examples of this in the web (because why would anyone want to do this if the base nbdev is already very decent and requires no effort). I am attempting to use the [github pages minimal theme](https://github.com/pages-themes/minimal) which expects to have markdown as the main file format to build the page. I was wondering if `nbdev_build_docs` could have an option to export the notebooks as `md` instead of `html`

**Comment by danielmitchell** [comment]
I would also like the option of exporting the docs to markdown as an alternative to html. We use private Bitbucket and Gitlab repos internally and being able to have the docs viewable natively within the repo as .md files would be fantastic.

**Comment by jph00** [comment]
Unfortunately I don't have access to GH Enterprise so it's hard to support it. PRs are welcome, however, for anything that makes things work better on that platform. Also take a look at nbdev2 when it's out in a few weeks - that'll export to .md by default.
