### ISSUE TITLE
Installing nbdev Breaks Kaggle Notebook Saving

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/nbdev#556]
Installing nbdev in a Kaggle notebook breaks saving the notebook due [incompatible nbconvert requirements](https://www.kaggle.com/product-feedback/284575#1587164). Kaggle requires nbconvert-6.1.0, but nbdev requires nbconvert<6.

Packages that install nbdev as part of their requirements, such as ohmeow/blurr#57, can trigger this dependency mismatch.

**Comment by jph00** [comment]
nbdev2 should resolve this since it doesn't need jupyter.
