### ISSUE TITLE
Cannot generate documentation: 'coroutine' object is not subscriptable

### ISSUE THREAD

**Issue by jfthuong** [fastai/nbdev#558]
Hi,

When trying to generate docs from notebooks I got the following error:

```python
[IPKernelApp] ERROR | KeyboardInterrupt caught in kernel.
'coroutine' object is not subscriptable
/home/user123/.local/lib/python3.7/site-packages/nbdev/export2html.py:511: RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
  return False
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I'm using:

* Python 3.7
* Linux (Ubuntu on WSL)
* `nbdev` 1.1.23

What is wrong?

Note: the generation works fine on Windows (but I got some other problems => see issue #559).

**Comment by Pyth314** [comment]
```
'coroutine' object is not subscriptable
/usr/local/lib/python3.8/site-packages/nbdev/export2html.py:511: RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
  return False
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Conversion failed on the following:
02_io.ipynb
converting /data-lab/tempr_ds/notebooks/lib_nbs/index.ipynb to README.md
```


Same problem for me on a
- docker instance : python:3.8-buster
- host : mac M1 

Question : 
What will be the steps if I want to build a brand new documentation from library notebooks, in order to avoid having residual previously autogenerated html files ?

**Comment by josiahlaivins** [comment]
Been getting a similar error for a few months now. This is stopping me from using the new docment module/new nbdev :( . I get:
```
/opt/conda/lib/python3.9/site-packages/nbdev/export2html.py:515: RuntimeWarning: coroutine 'NotebookClient.async_start_new_kernel' was never awaited
  return False
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

deps: 
```
Name: nbdev
Version: 1.2.2
---
Name: jupyter-client
Version: 7.1.2
---
Name: nbconvert
Version: 6.4.2
---
Name: ipython
Version: 7.32.0
```
The only solution is downgrading everything atm.

**Comment by josiahlaivins** [comment]
```python
# hide
from nbdev.cli import *
from nbdev.export import *
# from nbdev.export2html import *
make_readme()
notebook2script()
# notebook2html()
```

Seems like the solution is to run the html stuff outside of the notebook. It seems that if the notebook is running, for the new nbdev/client stuff you cant run notebook2html because its already in a notebook with an already running event loop. You can also use: notebook2html(n_workers=0)

I'm opting to just use watchmedo in a docker-compose file to run the command for now.
