### ISSUE TITLE
Cannot use documentation: links in sidebar points to .html file

### ISSUE THREAD

**Issue by jfthuong** [fastai/nbdev#559]
When generating the Doc (Windows, Python 3.9), the sidebar is pointing to html file (e.g. `https://thisisme.github.io/my_repo/utils.html`) instead of the name of folder like it should be (e.g. `https://thisisme.github.io/my_repo/utils` which contains a file **index.html**).

The following 2 files are responsible:

* docs/sidebar.json
* docs/_data/sidebars/home_sidebar.yaml  (auto-generated from that file)

**Comment by manuvazquez** [comment]
Did you get to solve this? I'm having the same problem

**Comment by jph00** [comment]
Should be fixed in v2
