### ISSUE TITLE
Allow for custom logos and favicons

### ISSUE THREAD

**Issue by YiweiMao** [fastai/nbdev#565]
Maybe I'm missing something however I can't seem to find how to do this. 
I don't have any FastAI logos in my repository docs folder (https://github.com/YiweiMao/coloured_spectra/tree/master/docs) but FastAI logos and favicons appear in the documentation site (https://yiweimao.github.io/coloured_spectra/). 

If I want to use nbdev and replace the FastAI logo and favicon with my own, is this possible? If so, how can this be done?

**Comment by YiweiMao** [comment]
Found this: https://forums.fast.ai/t/how-to-update-favicon-and-logo-for-nbdev/88880/2
TLDR: make files /docs/assets/images/favicon.ico and /docs/assets/images/company_logo.png
The directory /docs/assets is not created using nbdev so you have to create it yourself. 

Include this in the documentation formally?

**Comment by benoit-cty** [comment]
Yes, It's not easy to find, but it's in this documentation : https://github.com/fastai/nbdev-jekyll-theme

**Comment by muellerzr** [comment]
@jph00  or @hamelsmu looks like this can be closed :)
