### ISSUE TITLE
Questions not covered in the tutorial (and maybe not in the docs)

### ISSUE THREAD

**Issue by SumNeuron** [fastai/nbdev#569]
Hey,
trying to figure out how to use nbdev. I have another issue already posted. I've read the tutorials and gone through the docs, but since I can't get the commands to work I'm kind of stuck. Basically I am looking for:

- how to name / organize notebooks to have submodules e.g. instead of cards.ipynb maybe games/cards.ipynb and then `from games.cards import Card`
- what if I just want a notebook which is just additional examples? How do I name that / get it in the documentation at a specific place. I get that I can fill out the index.ipynb to be comprehensive, but what if I want like 3 different walk throughs / examples without having a massive file?
- there is a comment about how nbdev is meant to be root directory of the project (although that can change) but constantly requires an additional step? Can that be automated?

**Comment by muellerzr** [comment]
For the first, set `recursive` to `True` in your settings.ini. Then just keep the module exporting the same (ie `#default_exp games.cards`). 

For additional examples, you'd need to write a tutorial notebook for it. We can't link examples -> function definition and have it autopopulate on the doc

Can you explain more on 3? Not quite following

**Comment by dsm-72** [comment]
@muellerzr sorry for the delay, did not notice the comment. For the last one, it is basically a scoping thing. Suppose I want to make a python library and I also want to make a website to demonstrate it. Then I might have a mono repo `project` with a `django_app` subdirectory containing my Django site and `nbdev_package` subdirectory containing the nbdev stuff. However, I may just want to run the `nbdev` commands from the `project` root.

Alternatively, the nbdev template pulls notebooks (00_core.ipynb, 01_more.ipynb, etc) from the root of the project. If there are 20+ notebooks for this it may be nicer to have `notebooks/00_core.ipynb`. It is similar to the first question except I would just want to dump all the nbdev files under a specific directory.
