### ISSUE TITLE
nbdev_build_lib adds checkpoint files to library

### ISSUE THREAD

**Issue by githubpsyche** [fastai/nbdev#577]
I don't want `*-checkpoint.ipynb` showing up in the libraries I build, but these files are nevertheless indexed in `_nbdev.py` etc. This seems to be a bug in the recursive search setting for nbdev_build_lib. It should probably ignore files in directories named `.ipynb_checkpoints` by default. Or better -- exclude anything that my `.gitignore` file would ignore. Though that could be a more controversial move.

**Comment by jph00** [comment]
I haven't seen that problem - please check with the latest version and provide a repro if you still see the issue.
