### ISSUE TITLE
show_doc error in vscode notebook

### ISSUE THREAD

**Issue by danielmitchell** [fastai/nbdev#580]
vscode can run jupyter notebooks but running show_doc causes an error: `NameError: name 'Markdown' is not defined`.

This is related to [this issue](https://github.com/fastai/fastcore/issues/365) in fastcore where fastcore.utils.IN_NOTEBOOK returns False in vscode, even though in_notebook() returns True.

showdoc.py has a conditional import which doesn't run and causes the error.

```
if IN_NOTEBOOK:
    from IPython.display import Markdown,display
    from IPython.core import page
```

**Comment by jph00** [comment]
I think this should work now
