### ISSUE TITLE
Does nbdev work if my repo is not hosted on GitHub?

### ISSUE THREAD

**Issue by davidefiocco** [fastai/nbdev#59]
In one of the first steps of the README, the user is asked to create a (GitHub) repo from the template.

My code runs on a local git server (as my organization doesn't use GitHub atm).

Can I run/use nbdev anyway, or is GitHub a hard dependency? (in case it is, it might be helpful to state it early on in the README). Thanks!

**Comment by daviddemeij** [comment]
yes it should work, I guess only the workflow file in the `.github` directory won't run continuous integration. You can just clone the nbdev template (or use `nbdev_new`) and then add your own remote.

**Comment by sgugger** [comment]
Indeed. The only dependency on GitHub is to be able to use `nbdev_template` repo as a template, but you can just clone it with another git server and rename it.
