### ISSUE TITLE
Using notebook2script without config.ini

### ISSUE THREAD

**Issue by nicole-brewer** [fastai/nbdev#592]
## Summary

It would be nice to be able to use notebook2script without having to source config.ini for the destination of the python module ("lib_path").  

## Problem:

I've got a nbdev project set up with a config.ini file where I'm developing a library. 
```
nbs_path = nbs
lib_path = %(lib_name)s
```

In the same repository, I'm creating a module with utilities that is not a part of the main lib. I would also like to
develop these utilities in notebooks and  use `notebook2script` to convert a `utils_nbs` directory to a different module of py files called `utils`. 

As far as I understand, notebook2script does not allow for this because of [line 327 in create_mod_files](https://github.com/fastai/nbdev/blob/48cb9d2f765a79ea44480ed6df7af842ca02eb65/nbdev/export.py#L327) requires referencing config.ini for `nbs_path` and `lib_path`.

## Current Workaround:
Right now I am changing my configuration file every time I want to switch which module I'm working on.

## Possible Solution:

Ideally, it would be nice to have an optional parameter for notebook2script called say, lib_path, in order to specify a destination directory for the module. It seems to be that the `files` argument already suffices to specify a nbs_path that is different than the one specified in config.ini.

## Final Thoughts:

I'd be happy to attempt a PR if this is a desirable feature. I've been using nbdev for a couple years now and I think it's the best thing since sliced bread.

**Comment by nicole-brewer** [comment]
I would also like to express my desire that the notebook2script also work outside the scope of a nbdev project. In other words, it would be nice to convert a standalone notebook into a script. Because there isn't any dependence on modules, this feature could even be language agnostic. This feature would require [issue 536](https://github.com/fastai/nbdev/issues/536) be resolved. This is clearly a bigger ask, but hopefully at least worth flagging for the future.

**Comment by muellerzr** [comment]
@nicole-brewer this can actually be hacked super easily with the [nbprocess](https://github.com/fastai/nbprocess) library! 

To do so, try the following from inside Jupyter:

```python
!pip install git+https://github.com/fastai/nbprocess
from nbprocess.export import nb_export, ExportModuleProcessor
from fastcore.xtras import patch

@patch
def create_modules(self:ExportModuleProcessor):
    "Create module(s) from notebook"
    self.process()
    for mod,cells in self.modules.items():
        all_cells = self.in_all[mod]
        name = self.default_exp if mod=='#' else mod
        mm = self.mod_maker(dest=self.dest, name=name, nb_path=self.path, is_new=mod=='#')
        mm.make(cells, all_cells, lib_name=self.dest)
```
As this is the "hack" needed, followed by:
```python
nb_export(nb_name, "utils")
```

@jph00 let me know if you think we can put this in as a PR to nbprocess 😄

**Comment by nicole-brewer** [comment]
What a great accidental example of why patches are so useful: clean OOP-friendly hacks 😲

**Comment by jph00** [comment]
@nicole-brewer I'd be happy to take a PR that adds an optional command line flag for this purpose. @muellerzr I'd be happy to look at something similar for nbprocess

**Comment by jph00** [comment]
nbdev now supports this feature.

**Comment by nicole-brewer** [comment]
Excellent, thank you!
