### ISSUE TITLE
Union type produces unreadable docstring results using show_doc

### ISSUE THREAD

**Issue by seanyboi** [fastai/nbdev#603]
Hi there,

I have a class defined like so:

```python
def __init__(self, x:Union[List[str],str], y:str, z:str):
```

and it produces a docstring like so when using `shoc_doc(Class.__init__)`

```
LockdownDates.init(country:Union[List[str],str\], **start_date**:str, **end_date**:str`)
```

Any help would be appreciated thank you!

**Comment by jph00** [comment]
Thanks @seanyboi . @muellerzr is going to look at this shortly
