### ISSUE TITLE
Dependency to twine package is missing.

### ISSUE THREAD

**Issue by cpow-89** [fastai/nbdev#61]
Greetings,
I tried to add my project to pypi. I followed the instructions under "Adding your project to pypi" and ran into the following error:

```
twine upload --repository pypi dist/*
/bin/sh: 1: twine: not found
Makefile:23: recipe for target 'pypi' failed
make: *** [pypi] Error 127
```

I was able to fix the issue by running `pip install twine`. But I think it would be helpful to add twine to the nbdev requirements or at least but a note under "Adding your project to pypi" that this step might be needed for first-time users of pypi.

All the best
cpow-89

**Comment by sgugger** [comment]
Thanks for flagging this. I added a note in the doc, making it a dependency would be wrong since nbdv doesn't really depend on this, it's just need for packaging.
