### ISSUE TITLE
indirect dependencies from "install_requirement = 'jupyter'"

### ISSUE THREAD

**Issue by jhgoebbert** [fastai/nbdev#610]
Hello everyone,
the Jupyter metapackage 'jupyter' has the install_requirements
```
        'notebook',
        'qtconsole',
        'jupyter-console',
        'nbconvert',
        'ipykernel',
        'ipywidgets',
```
Does nbdev really needs all of them? If not, it would be a great idea to list them separately instead.
It could help to reduce the number of indirect dependencies.

**Comment by jph00** [comment]
nbdev2 will no longer require jupyter.
