### ISSUE TITLE
GitHub Used by behavior 

### ISSUE THREAD

**Issue by FedericoGarza** [fastai/nbdev#612]
Hi!

I've noticed that respositories developed using `nbdev` ([fastai](https://github.com/fastai/fastai), [statsforecast](https://github.com/Nixtla/statsforecast)) don't  show the `Used by` feature.
 
Could it be a problem with the `setup.py` that alters the dependency graph?

**Comment by jph00** [comment]
I'm not sure if this is fixable or not - I've put out a request for help, and if anyone figures out how to fix it, we'll add it! :)
