### ISSUE TITLE
nbdev does not run exported import cells

### ISSUE THREAD

**Issue by Robotatron** [fastai/nbdev#614]
Example - I have a notebook with my exports:

![image](https://user-images.githubusercontent.com/95919873/165129213-c9769c72-90d3-4cea-9d3c-70b5b18913fd.png)

In the directory where *.py is exported I have a file `__init__.py` with `from coco_utils.core import *`

I build the package and execute `from mypackage import *`

However, the exported cell with imports does not run:

![image](https://user-images.githubusercontent.com/95919873/165129541-8cee8ac4-5cd9-4fc3-a1c5-2103bd60c600.png)

**Comment by jph00** [comment]
It does run them. There must be some other reason you're not seeing it AFAICT.
