### ISSUE TITLE
Generate requirements.txt (for implementation in dockerfiles)

### ISSUE THREAD

**Issue by josiahls** [fastai/nbdev#617]
@muellerzr  @jph00 @hamelsmu 

This would eventually be a pr for nbdev if you all are on board. I've learned a lot on how to settings.ini plays with dockerfiles. Current I think that the fastai dockerfiles require you to duplicate the requirements in the settings.ini in the dockerfile. They need to do this because if you do a version bump in the settings.ini it breaks the cache early on.

Generating requirements.txt from the settings.ini could allow  us to have the best of both worlds:
- settings.ini stays the central place for all stuff.
- requirements txts manage the cache in dockerfiles better.

Below command will generate 3 requirements: main pip, dev, and regular requirements.

Below is a command in using for personal projects:
```python
@call_parse
def make_requirements(
    path:Path=None, # The path to a dir with the settings.ini, if none, cwd.
    project_file:str='settings.ini', # The file to load for reading the requirements
    out_path:Path=None # The output path (can be relative to `path`)
):
    logging.basicConfig()
    requirement_types = ['','dev_','pip_']
    path = ifnone(path, Path.cwd())/project_file

    if not path.exists(): raise OSError(f'File {path} does not exist')

    out_path = ifnone(out_path, Path('extra')) 
    out_path = out_path if out_path.is_absolute() else path.parent/out_path
    out_path.mkdir(parents=True, exist_ok=True)
    _li('Outputting to path: %s',out_path)
    config = Config(path.parent,path.name)
    
    for req in requirement_types:
        requirements = config[
        requirements = requirements.replace(' ','\
        Path(out_path/(req+'requirements.txt')).write_text(requirements)
```

The result is:
![image](https://user-images.githubusercontent.com/19930483/166117601-b9517085-696c-447b-a964-3b5e5222dd6d.png)

Practical use case is found at https://github.com/josiahls/fastrl/blob/main/fastrl.Dockerfile

Additional references:
https://github.com/fastai/docker-containers/blob/91a385ccc8d0688662b5adda77919cbb2e23a1d8/fastai-build/Dockerfile#L7
https://github.com/fastai/docker-containers/blob/master/fastai/tmp_scripts/script.sh

Which means that in the dockerfile I have:
```docker
# Install Primary Pip Reqs
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/pip_requirements.txt /home/$CONTAINER_USER/extra/pip_requirements.txt
RUN pip install -r extra/pip_requirements.txt
# Install Dev Reqs
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/dev_requirements.txt /home/$CONTAINER_USER/extra/dev_requirements.txt
ARG BUILD=dev
RUN /bin/bash -c "if [[ $BUILD == 'dev' ]] ; then echo \"Development Build\" && pip install -r extra/dev_requirements.txt ; fi"

COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/requirements.txt /home/$CONTAINER_USER/extra/requirements.txt
RUN pip install -r extra/requirements.txt
```

**Comment by josiahls** [comment]
I'll create a scenario comparing pure nbdev based docker image building vs requirements.txt based docker image building:

## Basic Project:

example_project
**settings.ini**
```ini
[DEFAULT]
lib_name = example_project
user = josiahls
branch = master
version = 0.0.43
description = example_project
requirements = torch fastai
pip_requirements = gym pyopengl pyglet tensorboard
conda_requirements = 
dev_requirements = ray metaflow jupyterlab nbdev ipywidgets moviepy pygifsicle aquirdturtle_collapsible_headings plotly
	xeus-python matplotlib_inline rich[jupyter] wheel twine fastdownload watchdog[watchmedo]
console_scripts = fastrl_make_requirements=fastrl.core:fastrl_make_requirements
nbs_path = nbs
...
```

## Scenario 1 Nbdev Setup
**example_project.Dockerfile**
```docker
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime # 1
# Add these since they are needed for installing the deps...
COPY . . # 2
# cache will break everytime anything minor changes in the project which means if one of the requirements is a different
# version of pytorch, you will need to re-download and install it. This hurts the developer if they build locally, and also the 
# user since they need to repull 1-2 gb of a docker image when any little change happens
RUN pip install -e . # 3
ARG BUILD=dev  # 4
RUN /bin/bash -c "if [[ $BUILD == 'dev' ]] ; then pip install -e .[dev] ; fi" # 5
```
This is a very poor use of the docker image.
- every little change will force a complete re-build of the image. God forbid you have a version of torch you're trying out. Any consumer of the image will also need to repull several gb of dockerimage

## Scenario 2 Requirements Setup
**example_project.Dockerfile**
```docker
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime # 1

# Install base / stable / large requirements
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/pip_requirements.txt /home/$CONTAINER_USER/extra/pip_requirements.txt
RUN pip install -r extra/pip_requirements.txt
# Install lighter / faster changing requirements...
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/requirements.txt /home/$CONTAINER_USER/extra/requirements.txt
RUN pip install -r extra/requirements.txt
# Install dev requirements
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP extra/dev_requirements.txt /home/$CONTAINER_USER/extra/dev_requirements.txt
ARG BUILD=dev
RUN /bin/bash -c "if [[ $BUILD == 'dev' ]] ; then echo \"Development Build\" && pip install -r extra/dev_requirements.txt ; fi"

COPY . . 
RUN pip install -e . 
```
In the scenario, **only** if the requirements change will this dockerfile reinstall them. Even then, if dev_requirements change, **only** dev_requirements will be reinstalled. If requirements change, **only** requirements will change.

**Comment by jph00** [comment]
@josiahls based on our chat I think this is fine to go ahead with. We're moving from nbdev v1 to v2 over the coming weeks, so feel free to add this to v2 once it's up if it would be helpful to you.
