### ISSUE TITLE
Jinjia2>=3.1.0

### ISSUE THREAD

**Issue by jhgoebbert** [fastai/nbdev#618]
nbdev has pinned Jinjia2 to <3.1.0 in this commit
https://github.com/fastai/nbdev/commit/ecc52c5fcd31f1b4d5e82bafe4a2026d05d4977a

I wonder if nbdev can handle Jinjia  3.1, too. It might be possible with
```
try:
    from jinja2 import pass_context
except ImportError:
    from jinja2 import contextfilter as pass_context
```
https://github.com/voila-dashboards/voila/pull/1127/files

**Comment by jph00** [comment]
Looks like it might have fixed itself. I'll try removing it and see how we go.
