### ISSUE TITLE
Upload to pypi / conda under different name?

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#623]
How can I configure an nbdev project with `<repo-name>` to be uploaded to pypi as `<prefix>-<repo-name>` so that pypi doesn't complain that `<repo-name>` is too similar to other packages (since pypi doesn't have scoped packages like npm).

**Comment by dsm-72** [comment]
@muellerzr any update?

**Comment by jph00** [comment]
You can use `lib_name` vs `lib_path`.

**Comment by dsm-72** [comment]
@jph00 to clarify `lib_name` would be what it is called on pypi and `lib_path` is the subfolder in the repo?

**Comment by dsm-72** [comment]
Follow up, how does that change imports?
