### ISSUE TITLE
Updating CONTRIBUTING.md links for nbdev

### ISSUE THREAD

**Issue by DeanLight** [fastai/nbdev#627]
Hey Core Team.

I noticed that the `CONTRIBUTING.md` file accidentally contains links that accidentally point to the fastai repo.

I would like to submit a documentation PR to correct this and wanted to ask 2 questions to help me do this.

1. Is there currently a list of features/ roadmap of stuff that will be added to nbdev in the foreseeable future? Is the v2 milestone still relevant?
2. Is there a `new_methods` convention in this repo and should we update the link to search for them in nbdev? I tried replacing this [link](https://github.com/fastai/fastai/search?q=%22new+methods%22&unscoped_q=%22new+methods%22) from the contrib file to point to the nbdev repo and there were no hits.

If you have any other changes you would like me to address in the contrib file for this PR, please let me know.

Thanks in advance

**Comment by jph00** [comment]
The move to v2 is happening right now. I don't understand q2, sorry, but feel free to do a PR and if there's an issue we can chat about it there.
