### ISSUE TITLE
Current package build is not what is recommended by PyPa

### ISSUE THREAD

**Issue by dkgaraujo** [fastai/nbdev#631]
In the current Makefile, `dist` calls 
```
python setup.py sdist bdist_wheel
```
to build the package. But this has been deprecated ([see here for useful additional info](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)) and PyPa [recommends](https://packaging.python.org/en/latest/guides/tool-recommendations/) using `build` for the source distribution and wheels.

If there is no opposition, I'll be opening a PR to adjust the Makefile accordingly, ie to replace the above-cited command with:
```
pip install build && python -m build .
```

**Comment by jph00** [comment]
Thanks for pointing that out. I've wondered about that before, but don't have a great solution. I'm also not convinced there's a problem - the current approach works.

I don't think pip installing every time make is called is a good solution. I also don't love bringing in a new dep for something that currently works without a dep...

**Comment by dkgaraujo** [comment]
Thank you for the feedback, @jph00. Good points.

BTW, I thought adding the "pip install" bit would be required because the command would be in the Makefile instead of the actual Python code, but you are right, it is not a good solution.
