### ISSUE TITLE
Not compatible with Vertex AI managed notebooks

### ISSUE THREAD

**Issue by gakuba** [fastai/nbdev#632]
When I try to run nbdev_build_docs on vertex AI managed notebooks I get: 
`converting: /home/jupyter/nbdev/nbdevplay/02_evaluate.ipynb
No such kernel named local-conda-root-xgboost`

This is caused by the fact that Vertex AI managed notebooks allows you to dynamically chose a kernel. a work around I managed to do to get the command running was to remove the kernel specs from the metadata of the notebook. see attached image
![00_data ipynb (13) - JupyterLab](https://user-images.githubusercontent.com/4388418/175271176-3c957e92-e761-4fe7-b2c1-29b45d64eaed.png)

**Comment by muellerzr** [comment]
@gakuba try running `nbdev_clean_nbs` first? That should clean the metdata
