### ISSUE TITLE
`nbdev_build_docs` gets stuck on converting the last notebook

### ISSUE THREAD

**Issue by deven-gqc** [fastai/nbdev#633]
Hello, I haven't faced this issue before but recently when I run the command `nbdev_build_docs` or `make_docs` it takes over 10 minutes to generate the docs. 

To see if I could replicate the issue, I created a new repo from the template.
![image](https://user-images.githubusercontent.com/86305049/175562156-fa368f80-86e7-4424-9d1c-b5b58fd6854b.png)

Contents on `index.ipynb`
![image](https://user-images.githubusercontent.com/86305049/175562270-d5ba72c8-e1dd-435d-93e1-b4f7f5fdf922.png)

Contents of `00_core.ipynb`
![image](https://user-images.githubusercontent.com/86305049/175562344-c81cb9a7-2a71-4cdd-9298-6c0d9b25f436.png)

I am not sure what is going wrong over here. Can anyone help me?

**Comment by jph00** [comment]
Please try forums.fast.ai for help with nbdev setup

**Comment by deven-gqc** [comment]
The issue was solved over here. 
https://forums.fast.ai/t/nbdev-build-docs-gets-stuck-on-converting-the-last-notebook/97223/13
