### ISSUE TITLE
GH action fails when running nbdev_diff_nbs but locally success

### ISSUE THREAD

**Issue by ezekini** [fastai/nbdev#634]
I am trying the tutorial, everything works as expected up to the point of pushing the initial changes. Github action `Check if there is no diff library/notebooks` fails. I ran `nbdev_diff_nbs` and `nbdev_test_nbs` locally, there are no differences between notebooks/.py and all tests pass. Any ideas on what might be happening?
The exact output of the failed action:
```
Run if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
  if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
!!! Detected difference between the notebooks and the library
Error: Process completed with exit code 1.
```

note: I noticed that the action installs nbdev==1.2.3 instead of the last release. Don't know if it's related

**Comment by jph00** [comment]
Please try forums.fast.ai for help with nbdev setup
