### ISSUE TITLE
Testing a particular notebook not working when run via pytest

### ISSUE THREAD

**Issue by egakuba2** [fastai/nbdev#637]
I want to test different functions but in a sequential way. so I created one function so that I can test notebooks following an order that I choose.

```
def test_example():
      nbdev_test_nbs(fname="02_train.ipynb")
      nbdev_test_nbs(fname="03_evaluate.ipynb")
  
```

the problem with this is that when I run `pytest` it is triggering all other notebooks as if the fname parameter is being ignored.

**Comment by jph00** [comment]
Please try forums.fast.ai for help with nbdev setup
