### ISSUE TITLE
nbdev_new not working for me

### ISSUE THREAD

**Issue by ChrisRichardMiles** [fastai/nbdev#640]
I'm using python 3.9.0 on wsl2

I create a fresh repo like this: 
`gh repo create repo_name`
Then I clone it, cd into the directory and run `nbdev_new`, but I get this error message: 
```
Traceback (most recent call last):
  File "/home/c/miniconda3/bin/nbdev_new", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_new')())
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/c/w/nbdev/nbdev/cli.py", line 102, in nbdev_new
    author = run('git config --get user.name').strip()
  File "/home/c/miniconda3/lib/python3.9/site-packages/fastcore/xtras.py", line 266, in run
    if res.returncode: raise IOError(stdout)
```

I have tried after `pip install nbdev`, `conda install -c fastai nbdev`, and `pip install -e nbdev` after cloning this repo. 
It is ok since I still make a new repo from the nbdev_template, but I have to go github.com. 
I am not inconvenienced, but I wanted to post this since it is nice to do it all from the command line.

**Comment by fastdaima** [comment]
Hi @ChrisRichardMiles , 
* After creating the repo, have you executed the `git remote add origin 'url'` command , before executing the nbdev_new command.
* I tested with **nbdev==1.2.10** , I was able to run nbdev_new successfully, here is list of commands I have executed in order.
`mkdir test && cd test`
`gh create-repo test -d 'description'`
`git init`
`git remote add origin 'remote origin url'`
`nbdev_new`

After executing it, these files are generated 
`00_core.ipynb    docker-compose.yml  index.ipynb  MANIFEST.in  settings.ini
CONTRIBUTING.md  docs                LICENSE      README.md    setup.py`

**Comment by ChrisRichardMiles** [comment]
@fastdaima 
Thank you for your help. For some reason the second command does not work on my system, but it is ok because I have found a solution that doesn't use nbdev_new at all. I just this: 
`gh repo create "repo_name" --private -p fastai/nbdev_template`
The -p flag if for the template you want to use.
