### ISSUE TITLE
Built-in support for class definitions across multiple cells

### ISSUE THREAD

**Issue by diego898** [fastai/nbdev#641]
Given the purpose and scope of this project, I'm wondering if it might be useful to support developing a class across multiple cells (maybe using a built-in decorator?)

That way, the in-class comments can be arbitrary markdown cells, and complicated classes and behaviors can be added "piecemeal". 

This feature was originally brought up in https://github.com/jupyter/notebook/issues/1243 where two solutions were proposed:

1. (ab)using python subclassing like:
```python
class Dog()
    def method1(self):

--cells--

class Dog(Dog):
    def method2(self):
```

2. using a purpose built package: https://github.com/alexhagen/jdc/ which was last updated in 2020.

Right now, option 2. seems good, but that might/might not work in the future, or with the many other features nbdev provides (documentation, for example).

This might be a feature of interest for this project, in which case it may "adopt" pieces of the `jdc` package (or not). 

If not, feel free to close this issue and the closed issue might be of interest to other nbdev users who have felt the same.

**Comment by jtmiclat** [comment]
Hello, you might want to check out https://github.com/fastai/fastcore, particularly the `patch` decorator. https://fastcore.fast.ai/basics.html#patch

The example you have would be written as  
```
class Dog()
    def method1(self):

--cells--
@patch
def method2(self: Dog):
   ... 
```

**Comment by diego898** [comment]
Thank you @jtmiclat that indeed is what I was suggesting. Note however, that as of right now, if you build a class like this in a notebook, there doesn't seem to be a way to "export" or "unify" the piece-made definition into a single class file (or cell).

**Comment by diego898** [comment]
For future reference even with the methods described above there is currently no way to view the class definition you’ve defined across cells. 

There is an outstanding issue for this here:

 https://github.com/ipython/ipython/issues/11249
