### ISSUE TITLE
Error when running either nbdev_build_lib or nbdev_build_docs

### ISSUE THREAD

**Issue by sheride** [fastai/nbdev#642]
When I attempt to run `nbdev_build_lib` or `nbdev_build_docs` on an `nbdev` library that has previously worked very smoothly ([see here](https://sheride.github.io/bcml4pheno/)), I find that I encounter the following error.

```
Traceback (most recent call last):
  File "/Users/sheridan/opt/anaconda3/envs/pheno/bin/nbdev_build_lib", line 10, in <module>
    sys.exit(nbdev_build_lib())
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/nbdev/export2html.py", line 477, in nbdev_build_lib
    write_tmpls()
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/nbdev/export2html.py", line 467, in write_tmpls
    cfg = Config()
TypeError: __init__() missing 2 required positional arguments: 'cfg_path' and 'cfg_name'
```

The only thing I can find online for this is to reinstall `nbdev`, which I have done a couple of times. I'm not sure this is relevant, but I initially reinstalled `nbdev` because I was encountering a different (seemingly common) problem wherein running `nbdev_build_lib` returned the following error:

```
converting: /Users/sheridan/Academic/bcml4pheno/bcml_model.ipynb
converting: /Users/sheridan/Academic/bcml4pheno/data_vis.ipynb
converting: /Users/sheridan/Academic/bcml4pheno/manual_opt.ipynb
converting: /Users/sheridan/Academic/bcml4pheno/full_example.ipynb
converting: /Users/sheridan/Academic/bcml4pheno/ttbarzp.ipynb
converting: /Users/sheridan/Academic/bcml4pheno/index.ipynb
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
'HTMLExporter' object has no attribute 'template_path'
Traceback (most recent call last):
  File "/Users/sheridan/opt/anaconda3/envs/pheno/bin/nbdev_build_docs", line 10, in <module>
    sys.exit(nbdev_build_docs())
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/nbdev/cli.py", line 221, in nbdev_build_docs
    notebook2html(fname=fname, force_all=force_all, n_workers=n_workers, pause=pause)
  File "/Users/sheridan/opt/anaconda3/envs/pheno/lib/python3.9/site-packages/nbdev/export2html.py", line 582, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: Conversion failed on the following:
bcml_model.ipynb
data_vis.ipynb
manual_opt.ipynb
ttbarzp.ipynb
full_example.ipynb
index.ipynb
```

**Comment by deven367** [comment]
You need to upgrade your `fastcore`. `pip install -U fastcore`.

**Comment by sheride** [comment]
Thanks for getting back to me @deven367: I'm running on `conda` so I think the appropriate command would be `conda update fastcore`, which I ran. It does indeed look like I needed a small `fastcore` update, but after that finished I am continuing to get the same error for `nbdev_build_docs`. Additionally, it's worth noting that I made a parallel thread on the `fastai` forum ([see here](https://forums.fast.ai/t/error-when-running-either-nbdev-build-lib-or-nbdev-build-docs/97353/2)) and there is at least one other user encountering a similar problem.

**Comment by sheride** [comment]
A solution appears to be uninstalling `nbdev` and `fastcore` in `conda` and reinstalling `nbdev` using `pip`, as suggested by Deven (see the discussion [here](https://forums.fast.ai/t/error-when-running-either-nbdev-build-lib-or-nbdev-build-docs/97353/8))
