### ISSUE TITLE
hot reload no longer works & the notebook filter is slow

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#646]
hot reloading no longer works for me and I must manually refresh the page when doing `quarto preview`

I don't know if it could be related, but It feels like it takes forever for `quarto render` or `quarto preview` to begin working.  

**When I'm not using the notebook filter, hot reload works great**.   Note this is specifically happening on our filter `nbprocess_filter` and doesn't happen with a minimal notebook filter, so I suspect the issue is on our side, and not quarto.

cc: @jph00

**Comment by jph00** [comment]
Seems to be OK now
