### ISSUE TITLE
Accomodate nbdev v1 users

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#648]
- [x] make sure on nbdev website there's a very clear indicator of how to upgrade, or how to keep using the old version, including the home page.
- [x] hide_input no longer works from nbdev v1, this has been replaced with `#|echo: false`
- [x] Throw an error message with clear instrutions when someone tries to use nbdev v2 on a v1 project. We anticipate many people it's will upgrade to nbdev2 and use it on their nbdev1 project

cc: @jph00

**Comment by warner-benjamin** [comment]
Per Hamel, adding more issues attempting to convert anbdev1 project to nbdev2.

- `nbdev_new` doesn't appear to respect the existing `nbs_path` and creates new notebooks in the root directory. It creates a `_quarto.yml` file in root and `nbs_path`. Unsure if both are needed.
- `nbdev_new` doesn't convert `tst_flags` from nbdev1's pipe format `slow|cuda` to nbdev2 format `slow cuda`. The nbdev1 format causes broken pool errors.

**Comment by jph00** [comment]
> Per Hamel, adding more issues attempting to convert a nbdev1 project to nbdev2.

We're not planning to support using `nbdev_new` to upgrade an existing project. Instead we will endeavor to improve `nbdev_migrate` where possible -- although it won't be entirely automatic.

**Comment by jph00** [comment]
Here's the basic steps I took to upgrade ghapi:

```
# export LIBNAME=...

git rm Makefile
nbdev_migrate_directives
nbdev_export
git add $LIBNAME/_modidx.py
rm -rf docs

shopt -s globstar

perl -pi -e 's/#\|\s*hide_input/#| echo: false/' **/*.ipynb
perl -pi -e 's/#\|\s*hide_output/#| output: false/' **/*.ipynb
perl -pi -e 's/#\|\s*skip/#| eval: false/' **/*.ipynb
perl -pi -e 's/from nbdev.export import notebook2script/from nbdev import nbdev_export/' **/*.ipynb
perl -pi -e 's/notebook2script/nbdev_export/' **/*.ipynb
perl -pi -e 's/#\|?\s*all_slow/#| nbflags skip_showdoc skip_exec/' *.ipynb

rm -f .gitconfig 
rm -f .git/hooks/post-merge

cat >>.gitignore <<EOF
_docs/
sidebar.yml
EOF

# change gh pages to gh-pages branch root
# move CNAME file

# change doc_path in settings.ini
# cp styles.css

nbdev_preview
```
