### ISSUE TITLE
Fastpages style blog page

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbdev#649]
My understanding is that nbprocess is going to be nbdev2, but that it will also replace fastpages.  This issue is relating to the fastpages/blogging style projects. 

Is there a built in way to create the main page of the blog that lists blog posts?  

For example:
+ Fastpages creates this page automatically from the notebooks front matter:  https://isaac-flath.github.io/fastblog/
+ Quarto default blog creates this page automatically from notebooks front matter:  https://isaac-flath.github.io/APL-Exploration/

I think something like this is important for a blog so that people can see an order list of posts, with dates and description of post content.

**Comment by hamelsmu** [comment]
# Notes

## Front Matter

Jekyll Front Matter | Quarto | Notes
-- | -- | --
toc: false | Same | There are more options in Quartohttps://quarto.org/docs/reference/formats/pdf.html#table-of-contents
branch: master | n/a | Will not support this initially
badges: true | n/a | Will not support this initially
comments: true | comments:  hypothesis:     theme: clean | https://quarto.org/docs/output-formats/html-basics.html#commenting
categories: [fastpages, jupyter] | Same | You need to turn categories on at the listing level---title: "myblog"listing:  # (additional metadata excluded for brevity)  categories: true---
image: images/some_folder/your_image.png | Same | https://quarto.org/docs/websites/website-listings.html#listing-fields
hide: false | draft: true | https://quarto.org/docs/websites/website-blog.html#drafts
search_exclude: true | ---title: "My Document"search: false--- | https://quarto.org/docs/websites/website-search.html#disabling-search
title | Same |  
description | Same |  
sticky_rank | n/a | Not supportedhttps://quarto.org/docs/websites/website-listings.html#sorting-items

Jekyll Front Matter	Quarto	Notes
toc: false	Same	"There are more options in Quarto

https://quarto.org/docs/reference/formats/pdf.html#table-of-contents"
branch: master	n/a	Will not support this initially
badges: true	n/a	Will not support this initially
comments: true	"comments:
  hypothesis: 
    theme: clean"	https://quarto.org/docs/output-formats/html-basics.html#commenting
categories: [fastpages, jupyter]	Same	"You need to turn categories on at the listing level

---
title: ""myblog""
listing:
  # (additional metadata excluded for brevity)
  categories: true
---"
image: images/some_folder/your_image.png	Same	https://quarto.org/docs/websites/website-listings.html#listing-fields
hide: false	draft: true	https://quarto.org/docs/websites/website-blog.html#drafts
search_exclude: true	"---
title: ""My Document""
search: false
---"	https://quarto.org/docs/websites/website-search.html#disabling-search
title	Same	
description	Same	
sticky_rank	n/a	"Not supported

[https://quarto.org/docs/websites/website-listings.html#sorting-item](https://quarto.org/docs/websites/website-listings.html#sorting-items)s"

## Site Level Options

**Comment by hamelsmu** [comment]
## Site Level Options

Jekyll site config | Quarto | Notes
-- | -- | --
title | website:    title: |  
description | website:    title:    description: |  
github_username |   |  
github_repo | website:  repo-url: https://github.com/fastai/nbdev |  
url | n/a | Don't need this
baseurl | n/a | Don't need this
email | n/a | Don't need this
twitter_username | website:  navbar:     right:      - icon: twitter        href: https://twitter.com/fastdotai        aria-label: Fast.ai Twitter | https://quarto.org/docs/websites/website-navigation.html#top-navigation
use_math |   | https://quarto.org/docs/output-formats/html-basics.html#latex-equations
google_analytics | website:  google-analytics: "UA-XXXXXXXX" | https://quarto.org/docs/websites/website-tools.html#google-analytics
show_image | n/a | https://quarto.org/docs/reference/formats/html.html#layout
show_tags | title-block-categories | https://quarto.org/docs/reference/formats/html.html#layout
pagination | website:  page-navigation: true | https://quarto.org/docs/websites/website-navigation.html#page-navigation
annotations | comments:  hypothesis:     theme: clean | https://quarto.org/docs/output-formats/html-basics.html#commenting
