### ISSUE TITLE
Move showdoc out of filters

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#650]
Execute showdoc should happen outside of filters so it can be filename aware, roughly speaking you will want to:

- Have a hidden file in docs so you know last modified time
- Run showdoc on all notebooks and update in place on disk
- Run quarto to generate the docs

Right now showdoc is inside `nbprocess_filter` but we should refactor it like this.  The reason is that the user may be running their notebooks in a way that needs the current directory that the notebook is in.

**Comment by jph00** [comment]
@hamelsmu I don't fully understand this issue. Can you provide a concrete example?

**Comment by jph00** [comment]
@hamelsmu I've changed my mind about this -- I hadn't thought it thru properly when we originally discussed this. Instead, I think that we should always chdir to the repo's nbs directory in the filter, and that nbs that need to access files should always assume they're running from that directory (and if they're not in that directory, they should cd to it as needed when run directly as a notebook).
