### ISSUE TITLE
Export a single module

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#652]
It'd be great if `nbprocess` could export a single module. My use-case would be to develop lightweight scripts in my day-to-day work e.g. [this notebook/script which updates fastai's union annotations to the Python 3.10 union operator](https://wasimlorgat.com/tils/update-fastai-union-annotations-using-ast/). cc @hamelsmu

**Comment by jph00** [comment]
This used to work in nbdev1. We should update the kaggle nb that demonstrates it when this is working again:
https://www.kaggle.com/code/jhoward/using-nbdev-export-in-a-kaggle-notebook
