### ISSUE TITLE
Add automation for setup with ghpai

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#655]
Current papercuts that can be addressed:

- [x] Syncing the description text with settings.ini
- [ ] #654 
- [x] Updating the description for pages
- [ ] Update the tutorial when we are done

We need to possibly add `ghapi` as a dependency.  cc: @jph00

**Comment by jph00** [comment]
@hamelsmu is this done? (there's already a separate issue for gh-pages)

**Comment by hamelsmu** [comment]
Yes this can be closed now
