### ISSUE TITLE
Broken README link (with fix included)

### ISSUE THREAD

**Issue by jbwhit** [fastai/nbdev#660]
In the https://github.com/fastai/nbdev#contributing section, there's a link to the code of conduct: https://github.com/fastai/nbdev/blob/master/CODE-OF-CONDUCT.md

This is the wrong link (it 404s) it simply should point to this (note `_` instead of `-`): https://github.com/fastai/nbdev/blob/master/CODE_OF_CONDUCT.md

**Comment by jph00** [comment]
Thanks fixed now.
