### ISSUE TITLE
Nbprocess interferes with quarto 

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbdev#662]
cc @jph00 

I am trying to use Quarto outside of nbprocess, on a single jupyter notebook file and it tried to call nbprocess.  This fails because I am not in an nbprocess project so there is no settings.ini file. Quarto render does work as expected when running it on a quarto project such as my apl blog, just not isolated files.  

I am not sure why quarto is trying to call nbprocess yet, but I believe that quarto CLI functionality shouldn't be effected by nbprocess.  Here are stack traces.

```bash
(base) isaacflath@Isaacs-MacBook-Pro testquarto % quarto render Untitled.ipynb
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/bin/nbprocess_filter", line 8, in <module>
    sys.exit(nbprocess_filter())
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/fastcore/script.py", line 116, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbprocess/cli.py", line 112, in nbprocess_filter
    filt = get_config().get('exporter', FilterDefaults)()
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbprocess/read.py", line 75, in get_config
    return Config(cfg_path, cfg_name=cfg_name)
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/fastcore/foundation.py", line 260, in __init__
    else: raise FileNotFoundError(f"Could not find {cfg_name}")
FileNotFoundError: Could not find settings.ini
```

I then uninstalled nbdev, nbrpocess, and quarto.  I reinstalled nbdev from git and reinstalled quarto.  It still is attempting to call nbprocess, though nbprocess is not installed.

```bash
(base) isaacflath@Isaacs-MacBook-Pro testquarto % quarto render Untitled.ipynb 
ERROR: Error executing 'nbprocess_filter': No such file or directory (os error 2)
```

Will report back if I am able to make any progress on cause, but I am running out of ideas.

**Comment by Isaac-Flath** [comment]
@jph00 I have a workaround for this issue, which is to add an empty `_quarto.yml` file to the directory.  If that file exists, even if there are no contents, then quarto runs as expected and does not try to call nbprocess.

**Comment by Isaac-Flath** [comment]
In this situation I do not want it calling nbdev or nbprocess.  I am hoping that base quarto assumes base quarto by default with no nbdev/nbprocess, unless in a nbdev directory.

**Comment by jph00** [comment]
OK sounds like you've got a solution so I'll close this
