### ISSUE TITLE
[BUG] Broken link `Setting up Search`

### ISSUE THREAD

**Issue by FedericoGarza** [fastai/nbdev#664]
Hi!

I'm trying to follow the instructions to [`Setting up Search`](https://nbdev.fast.ai/search.html), but the link [search-template.txt](https://github.com/fastai/nbdev/blob/master/docs/search-template.txt) is broken.

**Comment by jph00** [comment]
Thanks. It's here: 
https://github.com/fastai/nbdev1/blob/master/docs/search-template.txt
