### ISSUE TITLE
Vision utils docs missing

### ISSUE THREAD

**Issue by DanteOz** [fastai/nbdev#681]
**Describe the bug**
The documentation for exported cells from `09b_vision.utils.ipynb` is missing from https://docs.fast.ai/vision.utils.html. Previous [docs version](https://web.archive.org/web/20210615201248mp_/https://docs.fast.ai/vision.utils.html#resize_images).

**Comment by jph00** [comment]
I've moved this to the nbdev repo since that's probably the source issue.

**Comment by jph00** [comment]
Thanks for the report - rebuilding the fastai docs with that fix.
