### ISSUE TITLE
nbdev_preview cannot install quarto or find module

### ISSUE THREAD

**Issue by AndrewRook** [fastai/nbdev#685]
Hi! 👋 

I was following along in the nbdev tutorial and I ran into a couple of problems with `nbdev_preview` [at this point](https://nbdev.fast.ai/tutorial.html#preview-the-docs). First, the automatic quarto installation fails with an expired certificate error:

```bash
$ nbdev_preview 
Password:
...installing Quarto
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
```

I got around that by installing from Quarto's website. That fixes the SSL cert issue, but then it has trouble finding the test package I created:

```bash
$ nbdev_preview
Preparing to preview
Traceback (most recent call last):
  File "/[user_path]/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-c518b3e58883>", line 1, in <cell line: 1>
ModuleNotFoundError: No module named 'test_nbdev'
```

This is odd because that module exists and if I go into python manually (from the same directory as I'm calling `nbdev_preview` from, the root directory of the repo) I can import it:
```python
$ ls
00_core.ipynb	MANIFEST.in	_quarto.yml	settings.ini	sidebar.yml	test_nbdev
LICENSE		README.md	index.ipynb	setup.py	styles.css
$ python
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:09:13) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_nbdev
>>> 
```

Any ideas where I could have gone wrong? I [uploaded everything to Github](https://github.com/AndrewRook/test_nbdev/tree/38cd9db4559d35f1957397d01b607486c4b3b166) in case it helps troubleshoot. Thanks in advance!

**Comment by AndrewRook** [comment]
I'll add that everything seems to have published fine on the Github side — the site is rendered properly (although the docs say "You’ll see that your index.ipynb file has been converted to a readme automatically" and that doesn't appear to have happened).

**Comment by seeM** [comment]
Unfortunately I'm unable to reproduce the expired SSL certificate issue on macOS:
```sh
$ nbdev_install_quarto
Password:
...installing Quarto
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   105  100   105    0     0    890      0 --:--:-- --:--:-- --:--:--   954
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 69.9M  100 69.9M    0     0  2145k      0  0:00:33  0:00:33 --:--:-- 1003k
```
---
Currently, `nbdev` requires that your package is in Python's search path - current directory excluded. There are two ways to fix this:

1. Install your package in the current environment
2. Explicitly add the current directory to Python's search path, like so `PYTHONPATH=. nbdev_preview` (usually not recommended for security reasons)

**Details:** What's happening is that `nbdev_render` calls `quarto` which then calls `nbdev_filter` _as a console script_. Python console scripts don't include the current directory in the search path. I think for security reasons since it would allow another to inject arbitrary code into your console scripts

**Comment by AndrewRook** [comment]
> Unfortunately I'm unable to reproduce the expired SSL certificate issue on macOS:

Oh, interesting! I forgot to put this in my original comment (my bad, sorry), but I'm also on macOS, using `nbdev==2.0.4` installed via `conda create -n [ENV] -c fastai nbdev matplotlib pandas notebook`. Not sure if that helps narrow it down. (It may be that my macOS version is pretty old at this point, or it could be that the SSL cert expired but then got renewed right after I tried.)

> Currently, nbdev requires that your package is in Python's search path - current directory excluded

Ah, ok. The docs frame doing an editable install via `nbdev_install` as optional, so I had skipped it.

Thanks for your help! 

Any thoughts on how to get `index.ipynb` converted to the README? (I recognize that's a separate issue, happy to open up a different issue for that problem if that would make it easier to track.)

**Comment by jph00** [comment]
> Any thoughts on how to get `index.ipynb` converted to the README? (I recognize that's a separate issue, happy to open up a different issue for that problem if that would make it easier to track.)

`nbdev_docs` creates that. However in big repos that can be a bit slow, so I've just added `nbdev_readme` to do only that bit. You'll need to `pip install -e .` again to get the updated console scripts.

I'll update the tutorial to fix/clarify those details you came across.

**Comment by jph00** [comment]
OK tutorial is updated now - hopefully it's more clear! The video version might be worth checking out BTW.

**Comment by AndrewRook** [comment]
Thanks @jph00! running `nbdev_install` fixed the preview issue.
