### ISSUE TITLE
Regression: reintroduce [source] link

### ISSUE THREAD

**Issue by KBodolai** [fastai/nbdev#692]
In nbdev1, when generating the docs it created a [source] link that opened the source code for the specific function or class in GitHub, but I see that's not there new.

![image](https://user-images.githubusercontent.com/69843715/181878353-2afb921d-55ab-4758-b783-3b331d9496bd.png)

I'd be happy to work on bringing it back if you think it's a good idea, and someone can point me in the right direction!

Thanks,
Kristian.

**Comment by jph00** [comment]
We're already working on adding it back, don't worry! But I see we don't have an issue for it, so we'll track it here.

**Comment by KBodolai** [comment]
great, let me know if there's anything I can help with :)
