### ISSUE TITLE
Multiple translations in the same Notebook

### ISSUE THREAD

**Issue by sgaseretto** [fastai/nbdev#70]
Is there a way to add multiple markdown translations and using something like a tab button to switch to that translation, instead of having to duplicate a notebook per language, making it harder to maintain the source code? When talking about translations I'm refering to handmade ones, not autogenerated by something like Google Translate

**Comment by sgugger** [comment]
Interesting point. I don't think there is such a feature in jupyter, and we didn't develop anything to support this. I guess we should continue this discussion on the [forum](https://forums.fast.ai/c/fastai-users/nbdev) as we keep discussion for new features there and the issues for known bugs only.
Thanks!
