### ISSUE TITLE
nbdev command not working in windows anaconda

### ISSUE THREAD

**Issue by unna97** [fastai/nbdev#700]
Details:
- created a new env and activated it using anaconda powershell
- In powershell, when command executed it opens a file
- In anaconda as well jupyter notebook it doesn't recognise the command but when trying to install it shows packages already installed

**Comment by seeM** [comment]
@unna97 could you please share the command being run and the full error message?

**Comment by jph00** [comment]
Ah yes sorry the nbdev commands don't work in powershell. You need to use WSL. I'll update the docs to mention this.
