### ISSUE TITLE
Migration tutorial link in readme doesn't work

### ISSUE THREAD

**Issue by johnowhitaker** [fastai/nbdev#701]
The readme (https://github.com/fastai/nbdev#readme) begins:
NB: This is nbdev v2, a major upgrade of nbdev. Whilst the differences to nbdev1 aren’t huge, it does require some changes. The old version docs are at [nbdev1.fast.ai](https://nbdev1.fast.ai/). You can use version-pinning in settings.ini (i.e 'nbdev<2') to stop nbdev from upgrading. To upgrade, follow the [migration tutorial](https://github.com/fastai/nbdev/blob/master/migrating.html).

https://github.com/fastai/nbdev/blob/master/migrating.html gives a 404 page

It should perhaps link to https://nbdev.fast.ai/migrate.html instead?

**Comment by jph00** [comment]
Thanks for letting us know. The issue occured because the README is auto-generated from the web home-page. I've fixed it to avoid the relative link now.
