### ISSUE TITLE
`show_doc` ends the details column at any `|` character

### ISSUE THREAD

**Issue by MichaelJFishmanBA** [fastai/nbdev#712]
### Example

```python
def make_prob_str(
    a: str, # Event in P(a | b)
    b: str # Condition in P(a | b)
):
    """Returns a string representation of a probability distribution that conditions on `b` with event `a`"""
    return f"P({a} | {b})"


show_doc(make_prob_str)
```

<img width="604" alt="image" src="https://user-images.githubusercontent.com/104097004/182243505-a6d2b23e-76df-4901-a4b8-0100ac182d17.png">

A workaround is to escape the pipe `\|`. I'd rather not do this, as it makes the comment harder to read in the code cell.

**Comment by MichaelJFishmanBA** [comment]
I'm guessing this has to do with how `|` is used as a special character in eg `#|export`.

**Comment by seeM** [comment]
Thanks @MichaelJFishmanBA for a thoughtful issue write-up 😄 this is fixed in current `master` and will be included in the next release
