### ISSUE TITLE
Built docs don't render code-generated latex

### ISSUE THREAD

**Issue by MichaelJFishmanBA** [fastai/nbdev#722]
### Example

```python
display(Latex("$$\mu(x)^2$$"))
```

In my notebook in VSCode, this gives

<img width="517" alt="image" src="https://user-images.githubusercontent.com/104097004/182377540-5493f580-e0ad-4887-ac95-e5648c2feec6.png">

In my locally previewed docs, this gives

<img width="373" alt="image" src="https://user-images.githubusercontent.com/104097004/182377618-d933c74b-c105-457f-8f92-463eecec477c.png">

**Comment by hamelsmu** [comment]
Markdown latex works, but the Jupyter display thing doesn't.   minimal example https://github.com/hamelsmu/quarto-latex/tree/main

**Comment by hamelsmu** [comment]
@jph00 do you want to share this [minimal repro](https://github.com/hamelsmu/quarto-latex/tree/main) I created with JJ?

**Comment by jph00** [comment]
I've passed that along to @jjallaire

**Comment by jjallaire** [comment]
This will work as expected if you instead do:

```python
display(Markdown("$$\mu(x)^2$$"))
```

Currently we don't emit raw LaTeX into HTML documents (even if we did Pandoc would actually ignore it during rendering). I could see an argument though that if we detected the `$$` delimiters that we could make a special case (perhaps that's what VS Code is doing?)

**Comment by MichaelJFishmanBA** [comment]
@jjallaire That fixed it for me, thanks!

**Comment by hamelsmu** [comment]
Thanks, @jjallaire
