### ISSUE TITLE
Using spaCy model in nbdev notebook

### ISSUE THREAD

**Issue by pvanhuisstede** [fastai/nbdev#736]
Not sure this is really a bug or that I am trying to do something weird. In my Jupyter notebook under nbdev I use spaCy and it's model 'en_core_web_sm' in 2 cells. In the first cell where I set it up I have to call the model and a need to export the cell because it is used in the cell below.

When I run nbdev_prepare it returns success. But when I run nbdev_docs I get the following error: ERROR: YAMLException: bad indentation of a sequence entry (sidebar.yml, 7:24)
6:       - README.md
7:               - section: en_core_web_sm-3.2.0
                          ~
8:                 contents:

I dropped the spaCy model in a data subdir of the repo and call that one, but perhaps there is a more elegant way to accomplish the same from a Jupyter notebook cell?

**Comment by jph00** [comment]
Please use the forums or discord for help, and provide a notebook or repo that folks can use to reproduce your issue.
