### ISSUE TITLE
Conda installer issue

### ISSUE THREAD

**Issue by Vernboy** [fastai/nbdev#741]
After following the instructions to conda install nbdev, I was getting an error when trying to run `nbdev_new`:
```
Traceback (most recent call last):
  File "/Users/andrew.chaffin/opt/anaconda3/envs/Django_Learning/bin/nbdev_new", line 5, in <module>
    from nbdev.cli import nbdev_new
ModuleNotFoundError: No module named 'nbdev'
```
After I pip installed nbdev the issue went away

**Comment by jph00** [comment]
Might have been a problem with your env - I just tried it in a fresh env and it worked for me.
