### ISSUE TITLE
Feature request: delete module when a nb is deleted

### ISSUE THREAD

**Issue by deven367** [fastai/nbdev#744]
Hello,

I was refactoring a lot of code for one of the libraries that I had written (in nbdev). Soon, I ended up deleting multiple notebooks, but their exported modules were still present in the package. Would it be possible to have a mechanism that, if a notebook was deleted, it's corresponding exported module (if it exists), also get's deleted? 

Thanks! ps. love the new update!

**Comment by jph00** [comment]
There isn't a way to do this that's safe, since we have no way to know whether the user wants to keep the py module or not. (e.g I often delete a notebook but want to keep the .py)
