### ISSUE TITLE
Accelerate `quarto preview`

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#748]
Possible avenues for investigation:

- Is quarto running notebook filters more times than we need (once each)?
- Is the Jupyter kernel being reused across notebooks?
- Can we use a faster execution engine: `execnb` instead of Jupyter?

**Comment by jph00** [comment]
@seeM now that preview is cached by latest quarto I think we can close this?

**Comment by seeM** [comment]
Agreed
