### ISSUE TITLE
Jupyter hooks break in environments without `nbdev` installed

### ISSUE THREAD

**Issue by calmdown13** [fastai/nbdev#760]
Running `nbdev_install_hooks` installs jupyter hooks at a user level (in the `~/.jupyter` dir). This means that when I run jupyter from another project those hooks will attempt to run. This is a bit problematic as it means that I need `nbdev` installed on every project, otherwise an error is raised when start a notebook server:
```
ModuleNotFoundError: No module named 'nbdev'
```
Is there a way to configure jupyter at a project level?

PS: loving nbdev, it feels very productive!

**Comment by jph00** [comment]
Ah interesting... They don't actually run outside of nbdev projects (they check for an nbdev settings.ini) -- but I guess even that check is requiring nbdev!

I'm not sure of a way around this, other than uninstalling the hooks. But I'll leave it for @seeM to take a look since he added the save hooks.

**Comment by seeM** [comment]
@calmdown13 ah I overlooked this. You can remove the bits that set `ContentsManager.pre_save_hook` from your `~/.jupyter/jupyter_notebook_config.json`, and add the following to `~/.jupyter/jupyter_notebook_config.py` (or `jupyter_server_config.py` for Lab):

```python
def nbdev_clean_jupyter(**kwargs):
    try: from nbdev.clean import clean_jupyter
    except ModuleNotFoundError: return
    clean_jupyter(**kwargs)

c.ContentsManager.pre_save_hook = nbdev_clean_jupyter
```

We'll update `nbdev_install_hooks` to use this approach too.

**Comment by seeM** [comment]
@calmdown13 `nbdev_install_hooks` is fixed in https://github.com/fastai/nbdev/commit/5742d525b869266b96043a04fdece396f516191e. Note that you'll have to manually update (or delete) the corresponding .json files if you ran before the fix

**Comment by calmdown13** [comment]
Awesome, thanks for the quick fix!
