### ISSUE TITLE
NameError: name 'urlsend' is not defined

### ISSUE THREAD

**Issue by j-k** [fastai/nbdev#766]
In Windows 10 after a fresh install with pip and following the instrucions to get started this message appears:

```
NameError: name 'urlsend' is not defined
```

**Comment by j-k** [comment]
Here are some more information:

```
  File "C:\Program Files\Python310\lib\site-packages\ghapi\core.py", line 112, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
NameError: name 'urlsend' is not defined
```

As can be seen I use Python 3.10. Do you expect any problems with that? Furthermore, the `nbdev_new` command seems to indirectly call something called `ghapi`. Assumingly that is Github API? I want to use nbdev just on my PC with no Github or so. Is that possible?

**Comment by kk1694** [comment]
I had the same issue; as a quick fix downgraded to 2.0.4, and that avoided the issue.

**Comment by jph00** [comment]
It's not supported on windows -- but the urlsend issue is fixed with the latest fastcore

**Comment by j-k** [comment]
Thanks!
