### ISSUE TITLE
Update All Python Scripts to nbs similar to `nbdev_update_lib` in v1

### ISSUE THREAD

**Issue by BirkhoffG** [fastai/nbdev#769]
I am wondering why `nbdev_update` in v2 works differently in v1. In v1, `nbdev_update_lib` will update all modified python scripts, which is very handy. 

However, in v2, to update changes made in the python module, we need to 
1. `cd python_module`
2. `nbdev_update python_file.py`

This is a cumbersome process. Why not just keep the v1 design by just typing the `nbdev_update` in the parent directory?

**Comment by BirkhoffG** [comment]
Also, the document is not very clear in v2. 

If you are in the parent directory, then `nbdev_update python_module/file.py` will not work if your notebooks are in the directory (e.g., in `nbs` directory). You need to move to the python module first, and update the module.

I don't know if this is intended or just a bug. Anyway, I cannot find clear documentation on `nbdev_update`, so it would be great if you could document this.

**Comment by jph00** [comment]
> I don't know if this is intended or just a bug.

It's a bug!
