### ISSUE TITLE
`nbdev_update` creates a new cell, instead of updating the original code

### ISSUE THREAD

**Issue by BirkhoffG** [fastai/nbdev#775]
`nbdev_update` does not work as intended. It will create a new code cell, instead of updating the original code.

My use case:

- python_module
    - a.py
    - b.py
    - ...
- nbs
    - a.ipynb
    - b.ipynb
    - ...
 
If I make changes in `a.py`, and run `nbdev_update`, it will create a new code cell in `a.ipynb`, rather than updating code in this notebook.

version: 2.1.1

**Comment by hamelsmu** [comment]
Thanks for reporting this.  I'm getting a different error: the code gets updated into the same cell, but it becomes a markdown cell without any directives.  

@BirkhoffG do you mind sharing a repo or minimal example

**Comment by BirkhoffG** [comment]
Hi @hamelsmu, here is my repo: 
https://github.com/BirkhoffG/counternet_jax

To reproduce the error: 
1. make some changes in `CounterNetTrainingModule` in `cfnet/training_module.py`.  
2. `cd cfnet`
3. `nbdev_update training_module.py`

**Comment by hamelsmu** [comment]
@BirkhoffG I your project is a nbdev v1 repo.  Have you tried migrating this project to nbdev v2 yet?  Here is a migration guide: https://nbdev.fast.ai/migrating.html

Can you please try that and let us know if that helps?

**Comment by BirkhoffG** [comment]
Yes, at the time I reported the bug, I was using the v2 `nbdev`. I manually downgrade to v1 for now as this bug persists.

The `snyc` module in v2 seems to have some problems (e.g., #769), so I downgrade to v1 for now.

**Comment by BirkhoffG** [comment]
> @BirkhoffG I believe your project is a nbdev v1 repo. Have you tried migrating this project to nbdev v2 yet? Here is a migration guide: https://nbdev.fast.ai/migrating.html
> 
> Can you please try that and let us know if that helps?


> Yes, at the time I reported the bug, I was using the v2 `nbdev`. I manually downgrade to v1 for now as this bug persists.
> 
> The `snyc` module in v2 seems to have some problems (e.g., #769), so I downgrade to v1 for now.

To replicate the issue reported, go to the `refactor` branch, which is using `nbdev` v2.
