### ISSUE TITLE
Make `nbdev_export` work outside nbdev repos

### ISSUE THREAD

**Issue by seeM** [fastai/nbdev#799]

**Comment by gautam-e** [comment]
When I use `nbdev_export` to export a notebook, I get the error:
 ```InterpolationMissingOptionError: Bad value substitution: option 'doc_host' in section 'DEFAULT' contains an interpolation key 'user' which is not a valid option name. Raw value: 'https://%(user)s.github.io'```

Is this the issue that's being considered here?

**Comment by seeM** [comment]
Yes it is. The workaround for now is to ensure you have a minimal settings.ini file in your repo

**Comment by jph00** [comment]
@seeM any chance you could jot down some more details about how you see this working, and what the results should be, in the issue description?

**Comment by seeM** [comment]
The intention was to have a way to use nbdev’s export functionality from the command line outside of nbdev repos. `nb_export` from the command line. Maybe in `nbdev_export` via an arg like `fname`, or maybe as a separate command

It might also be the case that `nbdev_export` does that with a few minor tweaks (e.g. to default values of `lib_path` or requiring args to be passed via the command line if settings.ini doesn’t exist and failing explicitly if they’re not provided)

**Comment by kevinsimper** [comment]
It would be really cool, I thought I was making a mistake until I read this blogpost 
https://nbdev.fast.ai/blog/posts/2022-11-07-spaces/

and here from the link inside the blogpost https://gist.github.com/hamelsmu/35be07d242f3f19063c3a3839127dc67

that calling it directly is a better approach
```
from nbdev.export import nb_export
nb_export('app.ipynb', lib_path='.', name='app')
```

it would be cool if you could do `nbdev_export app.ipynb app`

**Comment by jph00** [comment]
@hamelsmu since you're in this part of the codebase now maybe you could look at this? I agree it would be super handy! :D

**Comment by hamelsmu** [comment]
What about using `nb_export` as documented [here](https://nbdev.fast.ai/tutorials/modular_nbdev.html#export-code-to-modules-nb_export).  It seems like that solves the user's problem?

**Comment by jph00** [comment]
That's already mentioned above. Calling it from Python works, but it's much more convenient to have a CLI.

**Comment by hamelsmu** [comment]
I am confused about the requirements here.  

> nbdev_export app.ipynb app

1. Do we want to allow people to export a notebook to a specific module?  
2. Do we need to generate an `__init__` file also in the dest "library path"?
3. Do we still need to generate `_modidx.py`
4. Do we want to convert an entire directory of notebooks into python scripts?

Re: YAGNI, I would like to understand concretely what problem this solves.  One thing that resonates with me is to convert a single notebook into a python script.  I am not sure we should go further than that based upon what I understand.  

Either way, additional color would be helpful.
