### ISSUE TITLE
`nbdev_preview` Mermaid doesn't work

### ISSUE THREAD

**Issue by benoit-cty** [fastai/nbdev#804]
I was exited by https://quarto.org/docs/authoring/diagrams.html

Graphviz plot work with NBDev, but not Mermaid plot.

## How to reproduce

copy-paste the sample from Quarto in a fresh nbdev v2 project:
```
'''{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
'''
```
(replace quote by back-quote)

Run `nbdev_preview`

## Expected result
The page display the plot.

## Actual result
The page display the code of the plot.

There is an error in the browser console:
```
Uncaught ReferenceError: mermaid is not defined
    <anonymous> http://localhost:3000/site_libs/quarto-diagram/mermaid-init.js:21
```

But I could see the library `http://localhost:3000/site_libs/quarto-diagram/mermaid.min.js` is loaded.

## Versions used
nbdev: 2.1.1
Quarto 1.0.37

**Comment by hamelsmu** [comment]
Thanks for reporting this.  I've tested this and it works with the current version of Quarto.  Can you try upgrading?
