### ISSUE TITLE
Usage question: how do you handle paths to files?

### ISSUE THREAD

**Issue by SultanOrazbayev** [fastai/nbdev#805]
Apologies if this is not the right place to ask, but I have a usage question: my work involves both developing a specialised library and analysis of some dataset in one repo.

A recurring issue I have is how to define paths in a way that allows easy referencing from within both the scripts and notebooks (allowing for the fact that files might be located on different drives/remote locations).

**Comment by SultanOrazbayev** [comment]
And more broadly, what is an efficient way to go about doing both data science and development work with `nbdev`?

**Comment by seeM** [comment]
Sorry, I don't quite understand your questions. If you could give some concrete examples or use-cases I could probably give you better answers, but here's an attempt in any case :)

1. I'd try to use absolute paths where possible. And I might use `nbdev.read.get_config().config_path` to find the root of my repository, then construct paths from there. That would work in any sub-directory of my repo.
2. By "data science work" I assume you mean notebooks that don't export modules? We have a few of those, for example, https://github.com/fastai/nbdev/blob/master/nbs/git_friendly_jupyter.ipynb renders https://nbdev.fast.ai/git_friendly_jupyter.html. You could also customise the sidebar to have one section for your exported "Library", and another section for your "Analyses".

**Comment by seeM** [comment]
I'm going to close this for now, hope my answer was helpful!

**Comment by SultanOrazbayev** [comment]
Thanks, @seeM! Yes, the answers are helpful, but I will need more time to figure out what parts of my current workflow can benefit from `nbdev`.
