### ISSUE TITLE
I think `add_jekyll_notes` is not flexible?

### ISSUE THREAD

**Issue by deep-diver** [fastai/nbdev#81]
While looking around `fastpages` project, I have felt `add_jekyll_notes` is not flexible. (I might be wrong)

```python
def add_jekyll_notes(cell):
    "Convert block quotes to jekyll notes in `cell`"
    _styles = ['note', 'warning', 'tip', 'important']
    def _inner(m):
        title,text = m.groups()
        if title.lower() not in _styles: return f"> {m.groups()[0]}: {m.groups()[1]}"
        return '{% include '+title.lower()+".html content=\'"+_to_html(text)+"\' %}"
    if cell['cell_type'] == 'markdown':
        cell['source'] = _re_block_notes.sub(_inner, cell['source'])
    return cell
```

Above is `add_jekyll_notes` function, and `_styles` are defined and assigned with static values.
When I want to add more styles  like embedded twitter post or something, I need to define my own function. However, the only thing that has to change is `_styles` while the remaining codes are the same.

Below is `add_embedded_links` function from `fastpages` project.

```python
def add_embedded_links(cell):
    "Convert block quotes to embedded links in `cell`"
    _styles = ['youtube', 'twitter']
    def _inner(m):
        title,text = m.groups()
        if title.lower() not in _styles: return f"> {m.groups()[0]}: {m.groups()[1]}"
        return '{% include '+title.lower()+".html content=\'`"+_to_html(text)+"`\' %}"
    if cell['cell_type'] == 'markdown':
        cell['source'] = _re_block_notes.sub(_inner, cell['source'])
    return cell
```

What do you think about separating `_styles` out as an parameters or property?
In that way, other projects relying on `nbdev` could be extended easier while hiding some internal complexity.

**Comment by sgugger** [comment]
We could make that an argument in Config, which means anyone could set it to what they want in their `settings.ini`.
Or we could consider that anything like > title: quote is to be embedded that way.

In any case we are on a book deadline for now, so won't work on this before the week after next I think.

**Comment by deep-diver** [comment]
@sgugger Maybe I could contribute on this?

**Comment by hamelsmu** [comment]
@deep-diver this is a great idea.  I like the `settings.ini` approach, in case someone wants to legitimately put `>` in their markdown for another reason

**Comment by sgugger** [comment]
Added support for this, using a field called `jekyll_styles` in the settings.ini.
Also updated the [template](https://github.com/fastai/nbdev_template) to show how to use it.

**Comment by hamelsmu** [comment]
@deep-diver please note that this doesn't fix the problem of `youtube` and `twitter` because I need to wrap those in code blocks to prevent nbconvert from placing link tags around those automatically.  

Its hard to see but I enclose the content in backticks to "escape the html" which is a special case and why I monkey patched it here.  

https://github.com/fastai/fastpages/blob/master/_action_files/nb2post.py#L23

**Comment by hamelsmu** [comment]
@sgugger can you upload a new release of this to pypi so I can integrate these changes in fastpages?  For stability reasons, I'm going off what's uploaded to pip instead of referring to master.  

P.S. _Let me know if you need help completely automating the pip release process via Actions_

**Comment by sgugger** [comment]
Release done
