### ISSUE TITLE
Weird error message when running nbdev_docs or nbdev_preview

### ISSUE THREAD

**Issue by joaopcnogueira** [fastai/nbdev#810]
Even when I have the variable defined on my notebook and nbdev_prepare running successfully, when I tried to run nbdev_docs or nbdev_preview, I got the following error:

![CleanShot 2022-08-08 at 21 35 29](https://user-images.githubusercontent.com/17098391/183538211-6bebed9e-1fe7-43a4-829e-1a58dedbd43a.png)

Any tips on how to solve this? I've tried to use `#|eval: false` and that worked. But it doesn't seem to be the root cause of the problem.

Here is the notebook link: https://github.com/joaopcnogueira/mletrics/blob/main/nbs/index.ipynb

**Comment by joaopcnogueira** [comment]
I have found a solution, but I didn't understand why it worked. 

I have put the import `from mletrics.classification import ks` on one of the firsts notebooks cells and it worked.

Any clues on why does it behave like this?

**Comment by joaopcnogueira** [comment]
After a little bit more of investigation, it seems (I am not sure) that having an import statement somewhere between the code and not together with all other impor statement at the beginning of jupyter notebooks some how makes `CaptureShell` from `execnb` think that is a new enterely code and that maybe is the reason it gives me back that `NameError`, even though the `y_test` is well defined on previous cell.

**Comment by benoit-cty** [comment]
Hello, I've gone through the same problem : https://forums.fast.ai/t/migrating-from-nbdev1-to-nbdev2/97858/40?u=benoit_c

I have to move all import statement.

It is a good development practice but nbdev v1 do not behave like that.

**Comment by joaopcnogueira** [comment]
I have read you problem description on nbdev foruns and your statetement _"After some test it seems that nbdev only execute cells with import keyword."_ gave me an idea to test if it was `nbdev` or only `nbdev_preview`. 

It turns out that if we do `nbdev_prepare` or any other command that is not `nbdev_preview` or `nbdev_docs`, nbdev is not going to give you any errors despite the location of import statements. But if you try to run `nbdev_docs` or `nbdev_preview` you'll have to move the import statements to its only jupyter notebooks cells, because `nbdev_preview` and `nbdev_docs` **only executes jupyter notebook cells that contains import statement**. I verified that moving all the import statements to their own notebook cells and introducing some typo errors at others parts of the code, and even with these typo errors `nbdev_preview` and `nbdev_docs` works. 

So, I think that is the root cause: `nbdev_preview` and `nbdev_docs` only executes cells that has import statements. They do not run all the others cells that does not contains import statements. That's precisely why I received an error like `NameError: name 'y_test' is not defined`, because previous cells with `y_test` definition were not executed.

**Comment by joaopcnogueira** [comment]
If you need any help to add this to the documentation, I'll be glad to help.

**Comment by hamelsmu** [comment]
Thanks so much for your kind offer.  I think this a frequent enough confusion that we should add an automated warning message

**Comment by jph00** [comment]
Tracking it here https://github.com/fastai/nbdev/issues/714
