### ISSUE TITLE
`nbdev_preview` freezes with no output.

### ISSUE THREAD

**Issue by jkasimotto** [fastai/nbdev#816]
![image](https://user-images.githubusercontent.com/67080621/183761121-dc6b72aa-57d4-45d3-9f92-ed465488cf23.png)

- The output is stuck like this and no local webserver opens up at localhost:3000. 
- All cells run in the notebook. My imported modules are: `fastai`, `nbdev` and `json`. 
- Running on WSL2 Ubuntu 20.04.

**Comment by hamelsmu** [comment]
Can you share a minimal example we can use to reproduce the issue, with code we can run?

**Comment by benoit-cty** [comment]
Maybe if you have many notebooks like me it could take few minutes to complete.

**Comment by jph00** [comment]
closing due to no response or repro

**Comment by jkasimotto** [comment]
Hi @hamelsmu, @benoit-cty and @jph00,
Thank you for taking the time to help me and I apologise for taking four days to respond. Here is a minimal example that causes the error [nbdev-tutorial.zip](https://github.com/fastai/nbdev/files/9334259/nbdev-tutorial.zip). All I've done is added `from fastai.vision.all import *` to the core notebook created by `nbdev_new`.

**Comment by jph00** [comment]
Thanks @jkasimotto ! No need to apologise - I assumed you'd gone on to other things so figured I'd close it until/unless we heard back, so all good now. I'm looking at your repo now.

**Comment by jph00** [comment]
Seems to be working OK. First I tried to preview without installing, and got an error as expected:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/346999/184558765-fb0bbcc9-6604-4967-ab1a-c0bcf0477f0b.png">

Then I installed and tried again, and it worked fine:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/346999/184558781-679ea99c-598e-4a5b-969e-cd201c9febec.png">

Can you please ensure you've upgraded to the latest fastcore, execnb, and nbdev, and try again?

**Comment by jkasimotto** [comment]
Thank you Jeremy! Upgrading as you suggested and waiting a few minutes as Benoit suggested fixed the issue. :)
