### ISSUE TITLE
nbdev_clean not working

### ISSUE THREAD

**Issue by kk1694** [fastai/nbdev#823]
When I run `nbdev_clean --disp`, I get the following error messages (and the notebooks are not cleaned):

```
/home/krisztian/miniconda3/envs/noki/lib/python3.8/site-packages/nbdev/clean.py:110: UserWarning: Failed to clean notebook
  warn(f'{warn_msg}')
/home/krisztian/miniconda3/envs/noki/lib/python3.8/site-packages/nbdev/clean.py:111: UserWarning: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
  warn(e)
/home/krisztian/miniconda3/envs/noki/lib/python3.8/site-packages/nbdev/clean.py:111: UserWarning: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
  warn(e)
```

I'm using version 2.1.3 (latest on pip).  Whether git hooks are installed or not make no difference.

Anyone else encounter this?

**Comment by kk1694** [comment]
I was wrong, the notebooks are actually cleaned (but still getting the warnings)

**Comment by hamelsmu** [comment]
This seems like it could be a legitimate issue (erroneous warnings) do you want to reopen it and maybe change the title?

**Comment by kk1694** [comment]
I'll investigate a bit to make the issue more useful. It seems like some of the notebook magic commands that are throwing off `nbdev_clean`, but I'm not sure yet.
