### ISSUE TITLE
exporting cell to module different than default one doesn't work

### ISSUE THREAD

**Issue by Jaume-JCI** [fastai/nbdev#834]
I followed the nbdev_cards tutorial and created a new notebook called 02_additions.ipynb, which has the following content:

```
#| default_exp additions

# Additions

> API details.

#|export deck
class Addition:
    def __init__ (self, n):
        self.addition = []
    def add (self, x):
        self.addition += [x]
```

In nbdev1, the class `Addition` would be added to the module `deck.py`. However, this doesn't seem to work in nbdev2?

I also tried adding a new class `Other` that is exported to the default module `additions`. In that case, a module `additions.py` is created with class `Other`,  but class `Addition` is not written in `deck.py`. This would be the code:

```
#| default_exp additions

# Additions

> API details.

#|export
class Other:
    def __init__ (self, n):
        self.other = []
    def add (self, x):
        self.other += [x]

#|export deck
class Addition:
    def __init__ (self, n):
        self.addition = []
    def add (self, x):
        self.addition += [x]
```

**Comment by seeM** [comment]
IIUC this isn't yet supported in v2. It's being tracked in https://github.com/fastai/nbdev/issues/742

**Comment by Jaume-JCI** [comment]
Oups, I had a look at the other issues but missed it, sorry about that. Thanks for the prompt response :-)

**Comment by seeM** [comment]
My pleasure :) I’ll close this and keep the other issue updated
