### ISSUE TITLE
Include filename in `nbdev_export` warning when nbdev1 syntax is used

### ISSUE THREAD

**Issue by geg00** [fastai/nbdev#835]
```sh
(base) gerardogarcia@Gerardos-MacBook-Pro kdone % nbdev_export      
/Users/gerardogarcia/mambaforge/lib/python3.9/site-packages/nbdev/export.py:53: UserWarning: Could not find `#|default_exp` cell. Note nbdev2 no longer supports nbdev1 syntax. Run `nbdev_migrate` to upgrade.
See https://nbdev.fast.ai/getting_started.html for more information.
  warn("Could not find `#|default_exp` cell. Note nbdev2 no longer supports nbdev1 syntax. Run `nbdev_migrate` to upgrade.\n"
```

The issue is that every page has the `#|default_exp` directive and I cannot find the reason this is failing
I would like to know which page is the one without the directive.

Here is the repository
https://github.com/geg00/kdone

**Comment by seeM** [comment]
@geg00 it looks like your `index.ipynb` has an `#|export` but no `#|default_exp`. I'll rename this issue and leave it open so we can clarify the warning message
