### ISSUE TITLE
source link to methods or classes for locally hosted website

### ISSUE THREAD

**Issue by rtmatx** [fastai/nbdev#84]
Hi,

Thanks for the amazing repo. I am able to get it up and running in a day with all the content transferred from my existing repo. 

I have a private repo which I am hosting locally instead of Github Pages. I followed the documentation available in the repo for local hosting

But the documentation website(locally hosted) doesn't have correct links to the methods and classes used in the notebook. They try to link to github website. Is there any way to make the source links point to the current repo instead of github location

Let me know if my question is not clear. I will go more in detail

Thanks

**Comment by sgugger** [comment]
You can specify `doc_host` in your settings.ini file to point to the doc website of your choice, and you can customize `git_url` if what annoys you is wrong links to the source code.

Let me know if this is not what you were looking for (but in this case please a bit a bit more precise ;) ).
