### ISSUE TITLE
`nbdev_clean` is very slow with notebook with big output

### ISSUE THREAD

**Issue by benoit-cty** [fastai/nbdev#843]
On my project `nbdev_clean` took 7 minutes. That's too much.

My guess is that it is due to [clean_cell_output](https://github.com/fastai/nbdev/blob/master/nbdev/clean.py#L50) that is reading all line output.

In my project I use Plotly that build huge outputs as they contains JS + data. See [this one](https://git.leximpact.dev/leximpact/leximpact-prepare-data/-/blob/memo-pepa/notebooks/memos/memo_pepa_suite.ipynb) (5MB) for exemple .

Is this part of `clean_cell_output` mandatory ?

**Comment by jph00** [comment]
You can set `clean_ids=false` in your settings.ini to disable it.

**Comment by benoit-cty** [comment]
Thanks, took less than 2 seconds now :1st_place_medal:
