### ISSUE TITLE
`nbdev_docs` and `nbdev_preview` don't use same path for docs

### ISSUE THREAD

**Issue by benoit-cty** [fastai/nbdev#844]
When using a config like this:
```
nbs_path = nbs
doc_path = _docs
```

`nbdev_docs` will build docs in `_docs` but `nbdev_preview` will delete  `_docs` and build docs in  `nbs/_docs`.

Is this a bug or a feature ?

**Comment by jph00** [comment]
The fact that nbdev_preview will delete `_docs` is a bug. Will be fixed in next version.

The reason that `nbdev_docs` moves the rendered docs into the repo root is to make it easier to use them directly in gh pages, if you want to deploy that way.
