### ISSUE TITLE
migrating a nb from v1 containing `#all_slow`

### ISSUE THREAD

**Issue by deven367** [fastai/nbdev#853]
I have a nb which I only run in colab, hence it has a flag of `# all_colab` in its first cell. From the migrating instructions, I modified the perl command accordingly to replace the flag. 
```perl
perl -pi -e 's/#\|?\s*all_colab/#| nbflags skip_exec/' **/*.ipynb
```
Yet, when I run `nbdev_prepare`, I see a message which tries to execute a cell. 

![image](https://user-images.githubusercontent.com/31466137/184509495-dc195fb8-56ea-474c-821d-d7263de3d710.png)

In #814, @jph00 said that `# nbflags skip_exec` was replaced with `skip_exec:true` in a raw cell. Do the instructions in the [Migrating from v1](https://nbdev.fast.ai/migrating.html#update-directive-names) nb need to change?

**Comment by jph00** [comment]
Yes they do need to change! Many thanks for catching this. Will fix now.
