### ISSUE TITLE
Document all of the directives

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#867]
It would be nice to have a documentation page with all of the directives.  @dleen has expressed interest in doing this.

**Comment by hamelsmu** [comment]
A technical overview of some things.

- The way some directives are implemented in nbdev are as notebook "processors".  Processors act on cells via [NBProcessor](https://nbdev.fast.ai/process.html#nbprocessor)
- The thing you want to know about processors, is that there is a bit of clever meta programming where if we name processors with an underscore suffix, let's say `def hide_() ....` that corresponds with the directive `#|hide` .
- One place where there are some directives with this style are in [processors.py](https://nbdev.fast.ai/processors.html)
- The default processors are defined in [FilterDefaults](https://github.com/fastai/nbdev/blob/master/nbdev/cli.py#L90-L94)

For example here are some cell processors:
1. [#|hide](https://nbdev.fast.ai/processors.html#hide_) this hides both cell input and output
2. [#|filter_stream](https://nbdev.fast.ai/processors.html#filter_stream_)

Other directives:
1. [#|hide_line](https://nbdev.fast.ai/processors.html#hide_line) You might want to study the test carefully to understand how it works, but you can hide specific lines of code from being rendered in the documents.

There is a set of processors that do not generate docs but instead export code, which is encapsulated into [ExportModuleProc](https://github.com/fastai/nbdev/blob/master/nbdev/export.py#L19).  The directives here are `#|{exporti, export, exports, default_exp}` You can see that `exports` is currently an alias for `export`

## Quarto Directives 

Our goal is to not introduce new directives relative to [what Quarto offers](https://quarto.org/docs/reference/cells/cells-jupyter.html) where possible.  Therefore, we deprecated nbdev v1 directives where quarto ones may do the same. Note there are more directives in Quarto than what are on that page, as you can specify project-level options in cells sometimes and vice versa.  Some ones that come to mind:

- `#|eval: true` this will also toggle nbdev_test off or on per cell
- `#|echo: false` will exclude cell input. this replaced `#|hide_input`
- `#|output: false` will exclude cell output. this replace `#|hide_output`


### Front Matter
The following is nbdev specific front matter (not exactly directives, but it is likely that people are going to look for them in the same place)

```
---
skip_showdoc: true #skips show doc from running 
skip_exec: true #skips any cells from running in tests
---
```

One suggestion is to scan all notebooks for `#|...` to see if you are documenting all the ones we are using and feel free to ask questions.

I hope this overview helps a bit to get you oriented a bit more

**Comment by dleen** [comment]
Yeah that explanation was awesome, really helped. I haven't used the front matter directives so I don't want to dive into that just yet... but otherwise should be ready for a proper review now. You can see the rendered docs from the PR here: https://dleen.github.io/nbdev/directives.html

> One suggestion is to scan all notebooks for #|... to see if you are documenting all the ones we are using and feel free to ask questions.

Yeah this is what I did to compile the list.

Aside: I think I found two more issues when documenting all this stuff: https://github.com/fastai/nbdev/issues/888 and https://github.com/fastai/nbdev/issues/886.
