### ISSUE TITLE
Extra markdown in notebook title/heading doesn't render

### ISSUE THREAD

**Issue by dleen** [fastai/nbdev#886]
If you have a title/heading cell (don't know what to call it) e.g.

```
# Foo

> The subheading 

Here is some more markdown.

* Bullet point
```

Then only the title and quote are actually rendered. Everything after the `>` isn't shown. You have to split it into two cells

**Comment by dleen** [comment]
Now that I think about it, could be related to: https://github.com/fastai/nbdev/issues/873

**Comment by jph00** [comment]
Yes this is expected behavior - I better document it! The title/description cell is just for creating frontmatter.
