### ISSUE TITLE
import issue with package seaborn

### ISSUE THREAD

**Issue by loganylchen** [fastai/nbdev#887]
Hi there,

I have encountered an issue that if i imported seaborn in my codes, then the nbdev_test will fail with this Exception:

'NoneType' object has no attribute 'comm_manager'.

Do you have any ideas about this?

**Comment by jph00** [comment]
That should be fixed with the latest version - can you please update to the latest fastcore, execnb, and nbdev, and check again? If you still have the problem, feel free to reopen this.
