### ISSUE TITLE
Quarto directive `#| output: asis` not working

### ISSUE THREAD

**Issue by dleen** [fastai/nbdev#888]
The directive `#| output: asis` is supposed to display raw markdown but if you do something like:

```
#|output: asis
print("# Heading")
```

in the output you will actually see a titled size "Heading" instead of some raw markdown of `# Heading`.

**Comment by jph00** [comment]
This is the expected behavior from quarto. `asis` means that the output is treated directly as part of the qmd file. So it'll be treated as markdown. Without the `asis`, the output of the print will appear wrapped in a code block.
