### ISSUE TITLE
nbdev_export fails to solve fastai/workflows/nbdev-ci@master error

### ISSUE THREAD

**Issue by SantiagoSanchezF** [fastai/nbdev#896]
After pushing my commit to GitHub (previous nbdev_prepare =Succesful) I keep getting "Error: Notebooks and library are not in sync.  Please run nbdev_export." in the CI workflow.

It seems to be a metadata conflict. But I'm new to nbdev and don't know where to start. nbdev_clean and nbdev_test are both successful.

The repo:
https://github.com/SantiagoSanchezF/trapiche

**Comment by chrisagblake** [comment]
I have the same issue. I run nbdev_prepare or nbdev_clean, nbdev_test, nbdev_export all of which run with no issues that I can see but I get the same error.

**Comment by jph00** [comment]
> I then updated my version of nbdev (2.1.7 -> 2.2.2) and this seemed to fix it.

Yup that'll be it.

**Comment by SantiagoSanchezF** [comment]
That worked. Many thanks
