### ISSUE TITLE
Deprecate `#|hide` in favor of `#|include`?

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#898]
Quarto has a directive called `#| include` which does the same thing as `#| hide` https://quarto.org/docs/reference/cells/cells-jupyter.html#code-output

@jph00 should we deprecate `#|hide` ?

Thanks to @Isaac-Flath for [finding this](https://github.com/fastai/nbdev/pull/868#issuecomment-1219662268) 🎉

**Comment by jph00** [comment]
I'm not sure. I can see it's a bit weird having two ways to do the same thing. OTOH I use #|hide so frequently, it's nice to have it be so short.

**Comment by dleen** [comment]
I find the Quarto name rather confusing? `#| include` is how you _exclude_ code or results from being _included_ in the output?

**Comment by hamelsmu** [comment]
I like having `#| hide` now that I have reflected on it for a bit.  `#| include: false` is very verbose for me, it is ok that we have a shorter alias, I think?

**Comment by jph00** [comment]
OK think we're all on the same page then.
