### ISSUE TITLE
Tutorial: Edit 00_core.ipynb section doesn't seem current

### ISSUE THREAD

**Issue by decherd** [fastai/nbdev#899]
I'm working through the tutorial again today and noticed that for the section on first editing the 00_core.ipynb file that is shows:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/20451688/185464692-ce5932d4-7448-484d-8fdd-2b63562d3766.png">

but when I went into the file I see this:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/20451688/185464805-e1f22ac4-2c92-4521-b9e6-8db49fa725a1.png">

I don't remember it looking like this the other day when I ran through it. I know this isn't a big deal but it was enough to throw me off being new and following along.

**Comment by jph00** [comment]
Many thanks for letting us know - I've reverted that change to the template, so they match again now.
