### ISSUE TITLE
`nbdev_prepare` wants to reformat README in this repo

### ISSUE THREAD

**Issue by dleen** [fastai/nbdev#914]
When I am working on the `nbdev` repo (on OSX, Python 3.9.13, Quarto: 1.0.38 - just updated it) after running prepare it always changes the README file. I'll open a PR so you can see the diff. Not sure if this is an issue between quarto versions where running it on one machine has different output than another. Also it'll let us know what the CI does in this situation. But either way this is an annoying situation for users if differences between versions of something results in format changes

**Comment by dleen** [comment]
CI ran fine, although now that I've checked I guess it doesn't do a git status check before and after to see if the README is dirty or not.

Maybe someone can check out my PR, generate the README and see if it gets reverted back?

**Comment by seeM** [comment]
@dleen we've been running the latest Quarto pre-releases internally. I think that's what our CI uses too. Try installing that and see if this still affects you? Link: https://quarto.org/docs/download/prerelease.html. Reason being that they've made tons of improvements, particularly around performance (e.g. `quarto preview` uses a cache and its much faster).

If I run `nbdev_readme` locally on latest `nbdev` master it doesn't change `README.md`.

It is definitely annoying - sorry about that! But I imagine Quarto won't be changing these sorts of things too often.

**Comment by dleen** [comment]
Yep, that solved it
