### ISSUE TITLE
In the `nbdev1_migration` tutorial, `Final steps` section, running `nbdev_preview` first and `nbdev_prepare` second doesn't work

### ISSUE THREAD

**Issue by Jaume-JCI** [fastai/nbdev#933]
I tried to follow the tutorial steps for migrating my repo. In my case, I had to run first `nbdev_prepare` first and `nbdev_preview` second, in order to have the preview after the new docs are built. If I run first `nbdev_preview`, it doesn't succeed.

**Comment by hamelsmu** [comment]
What are the errors that you get?  Can you please share those?

**Comment by jph00** [comment]
You're quite right - the package needs to be exported before the docs can be previewed. I'll update the tutorial with the correct workflow.
