### ISSUE TITLE
Wrong source link when using @patch

### ISSUE THREAD

**Issue by thigm85** [fastai/nbdev#939]
PR #692 reintroduced source links on the documentation, which is great. But it seems to fail when using @patch to add methods to a class. 

Example: The source link of [PassageData.save](https://thigm85.github.io/learntorank/passage.html#passagedata.save) links to https://github.com/thigm85/learntorank/blob/main/learntorank/passage.py#LNone instead of https://github.com/thigm85/learntorank/blob/main/learntorank/passage.py#L125.

**Comment by jph00** [comment]
Many thanks for the clear issue. Should be sorted in master now.
