### ISSUE TITLE
Image URLs are getting treated as files

### ISSUE THREAD

**Issue by drscotthawley** [fastai/nbdev#94]
Following up from fastpages issue https://github.com/fastai/fastpages/issues/58.

The error happens precisely in nbdev/export2html.py, in `copy_images()`, line 143:

```
 shutil.copy(Path(fname).parent/src, Path(dest)/src)
```
At this point, src is still a URL.  
Example, I added a print statement just before this line for one of my image urls (see https://github.com/fastai/fastpages/issues/58)

Output was:
```
calling shutil.copy, fname =  /home/shawley/devblog2/_notebooks/2019-12-21-PCA-From-Scratch.ipynb , src =  https://i.imgur.com/vKiH8As.png
```

This copy command tries to treat `src` like it's a filename, so it strips out extra slashes, and... yea things fail. 

The other checks elsewhere in the file, e.g. in `adapt_img_path()` don't even get run before the code exits with an error.

**Comment by drscotthawley** [comment]
Here's a fix, to be added right before the `os.makedirs()` line, (line 142), something like:

```
        if (src.startswith('http://') or src.startswith('https://')): return
```
Doing this solved my errors with external image URLs.  

Now...embedded objects (e.g. plots from plot.ly) are also being treated as they were files too.  These extremely long strings then produce "filename too long" errors.    Ideally, I'd imagine one would want to simply leave these things alone and 'pass them through', since they are already HTML.

**Comment by drscotthawley** [comment]
Ok, fixed the embedded object problem too:
```
        if (src.startswith('http://') or src.startswith('https://') or src.startswith('data:image/')): return
```
...So now the build will complete without errors, and the plot.ly interactive plots work in the generated .html file, BUT... 

but actually the external images aren't there in the final html file!

So, my 'fix' return statement only seems to strip out the external images entirely.

**Comment by sgugger** [comment]
I think there were a few more things to add, but I added tests and all seems to pass now.

**Comment by drscotthawley** [comment]
Oh great!  That fixes the external image problem. Thanks! 

Now, could you also add a 
```
        if src.startswith('data:image/'): return

```
...to the line immediately before the `os.makedirs()` line in `copy_images()`?

Doing this will allow imbedded object-images such as interactive plots from plot.ly to work *perfectly*.  :-)

**Comment by sgugger** [comment]
I added that. Can you make one last test on your side before we make a release?

**Comment by drscotthawley** [comment]
Thanks. Gladly.  Um...I will need to read up on your methodologies for doing tests the way you like.  My naive method would be to add an entire new .ipynb file in the repo to test against, but I'm guessing that would be too 'bulky' for fastai style.

**Comment by sgugger** [comment]
Oh no, I was just saying: test is on fastpage with your own notebooks to make sure all works okay, not add some tests to nbdev. :)

**Comment by drscotthawley** [comment]
Oh, ok!  Great.
I see that your version has "return cell" for that new line, whereas my version just has "return".  

In running these on [my test notebook file](https://github.com/drscotthawley/devblog2/blob/master/_notebooks/2019-12-21-PCA-From-Scratch.ipynb),Your version produces errors that halt the code (see below), whereas mine runs to completion but ...on closer inspection...produces [output HTML which is slightly mangled](https://hedges.belmont.edu/~shawley/2019-12-21-PCA-From-Scratch.html) -- the data:image parts load, but in the resulting HTML it has "paragraph symbols" (¶) at the right side of each markdown heading.
 
Output from `export2html.notebook2html` with the nbdev currently in the official repo:
```
sequence item 1: expected str instance, NotebookNode found
Traceback (most recent call last):
  File "_action_files/nb2post.py", line 37, in <module>
    export2html.notebook2html(fname='_notebooks/*.ipynb', dest='_posts/', template_file='_action_files/fastpages.tpl')
  File "/home/shawley/nbdev/nbdev/export2html.py", line 432, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: Conversion failed on the following:
2019-12-21-PCA-From-Scratch.ipynb

```

**Comment by sgugger** [comment]
I thought your line was weird but mine was worse ;). Tried something else to unify the approaches, let me know if it works better.

**Comment by drscotthawley** [comment]
I *think* it's fine now, thanks.  But to be sure, would you mind taking a look the HTML output for the `nbdev/nbs/tutorial.ipynb` page that I just created using your newest `export2html` code, to make sure it looks like you want it to?
Posting it here: https://hedges.belmont.edu/~shawley/2020-02-18-nbdev-tutorial.html

 It also has the "paragraph symbols", and I'm not sure if they're supposed to be there.

**Comment by drscotthawley** [comment]
...wait, none of the inline math is rendering now, such as $x$ or $f(x)$.  
Full-line math is rendering ok.

**Comment by drscotthawley** [comment]
As per https://github.com/fastai/fastpages/issues/71,  HTML "<img src" is getting translated into Liquid "{% img" by nbdev.  This breaks embedded image objects because Liquid can't handle the long strings.  
Might prefer for nbdev to leave "<img src" as is, and not translate it to Liquid.

**Comment by sgugger** [comment]
No we won't go back to '<img src' since it doesn't display properly normal images with good resolution (examples: screenshots in the index of nbdev.fast.ai). We can add a hack for embedded images instead.
