### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#944]
See also #916

**Comment by hamelsmu** [comment]
## Test: GitHub Enterprise Cloud (30-day Trial) ✅ 

1. Create a new account 30-day trial for GitHub Enterprise Cloud, called `fastai-labs`

> <img width="1093" alt="image" src="https://user-images.githubusercontent.com/1483922/188490714-0de835d5-36d0-4950-98a6-af5ba111fffb.png">

2. Create this repo [fastai-labs/nbdev_test](https://github.com/fastai-labs/nbdev_test)
3. Cloned the repo, ran `nbdev_new`
4. Everything was successful, including the [serving of the docs](https://fastai-labs.github.io/nbdev_test/)

**Comment by hamelsmu** [comment]
## Test: GitHub Enterprise Server ❓ 

While [I successfully tested GitHub Enterprise Cloud](https://github.com/fastai/nbdev/issues/944#issuecomment-1237294666), It appears that GitHub Enterprise Server requires talking to the sales team, and I don't see a path to testing there.  See [these docs](https://docs.github.com/en/enterprise-server@3.6/get-started/onboarding/getting-started-with-github-enterprise-server)

I contacted @lostintangent to see if he might be able to help with GHEnterprise Testing for partners, but otherwise, I am not sure how we would test.

cc: @jph00 @seeM

**Comment by lgonzalezsa** [comment]
Not ideal being man-in-the-middle, but I do have access to GitHub Enterprise Server, if I can help let me know.

**Comment by hamelsmu** [comment]
@lgonzalezsa I see you have already provided lots of useful information in #916.  Is there any possibility I could be added to your GHES group?  (I know this is may not be possible, but I thought I should ask).  

Its hard to debug / test otherwhise so trying to find a way :)

**Comment by lgonzalezsa** [comment]
Would be awesome but not possible unless you became employee, which also would be awesome.

**Comment by hamelsmu** [comment]
LOL :) ok let me think about this a bit more I might come back to you with questions

**Comment by seeM** [comment]
Closing, since there are no longer any known issues with GitHub Enterprise Server provided you set `GH_HOST` and `GITHUB_TOKEN`.
