### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AndrewBoney** [fastai/nbdev#949]
Link in Readme.md https://github.com/fastai/nbdev/blob/master/01_Tutorials/01_tutorial.ipynb is broken

**Comment by AndrewBoney** [comment]
Should be https://github.com/fastai/nbdev/blob/master/nbs/01_Tutorials/01_tutorial.ipynb

**Comment by seeM** [comment]
Thank you! Fixed in https://github.com/seeM/nbdev/commit/3416d0eb386ca5d391e2c3da740c666ae99cc303
