### ISSUE TITLE
Have troubleshooting section

### ISSUE THREAD

**Issue by Jaume-JCI** [fastai/nbdev#954]
May I suggest a troubleshooting section / notebook, with, among other, content:

## Troubleshooting

- Problems visualizing the docs in `github`.

> If you created your docs in a branch different than master or main (e.g., if you're just testing nbdev2 in one of the branches while the main branch is still in nbdev1 format), make sure you add the name of the branch to .github/workflows/deploy.yml

- Problems using recursive mode

> If you used `nbdev_new`, make sure you indicated --recursive True as follows:

```bash
nbdev_new --recursive True <other options>
```

If this is done directly in `settings.ini` after running `nbdev_new` , it won't succeed. 

(...) And more things that we may be adding ?

Just something I am finding good to document myself. It may be that some of this is already said somewhere in the documentation, apologies if that's the case.

**Comment by jph00** [comment]
> If this is done directly in `settings.ini` after running `nbdev_new` , it won't succeed.

If this is a general problem I'd rather fix it than document it! Can you tell me steps to reproduce this problem, and what exactly occurs? (e.g. is there an exception? something doesn't work the way you expect?) Do you have a repo or branch I could look at showing this issue?

I'm not sure the first one you mention is that common. We do want to add common issues to the FAQ, in general.

**Comment by Jaume-JCI** [comment]
I've been trying to reproduce this problem after pulling from master, but I am finding another issue that doesn't allow me to reproduce the first one. I describe this second issue here first. The steps to reproduce them (including repo to clone from) are:

```bash
git clone git@github.com:Jaume-JCI/nbdev_cards.git -b nbdev_new_issue
cd nbdev_cards
yes | conda create -n good_env python pip
conda activate good_env
pip install -e ~/path_to_nbdev2/
nbdev_new --recursive True --nbs_path nbs --lib_name nbdev_cards --description "nbdev cards" --user my_user --author my_author --author_email my_email --repo nbdev_cards
```
Where I replaced `my_user`, `my_author` and `my_email` with my personal details. 

If I run the above commands, I get the following error:

```
/anaconda/envs/good_env/lib/python3.10/site-packages/ghapi/core.py:99: UserWarning: Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated
  else: warn('Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated')
settings.ini created.
Traceback (most recent call last):
  File "/anaconda/envs/good_env/bin/nbdev_new", line 33, in <module>
    sys.exit(load_entry_point('nbdev', 'console_scripts', 'nbdev_new')())
  File "/anaconda/envs/good_env/lib/python3.10/site-packages/fastcore/script.py", line 117, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/workspace/nbdev/cli.py", line 102, in nbdev_new
    cfg = get_config()
  File "/home/workspace/nbdev/config.py", line 199, in get_config
    cfg = Config(cfg_file.parent, cfg_file.name, extra_files=extra_files, types=_types)
TypeError: Config.__init__() got an unexpected keyword argument 'types'
```

**Comment by Jaume-JCI** [comment]
I can also comment on the steps that reproduced the first issue before the second one appeared. They are these ones:

```bash
git clone git@github.com:Jaume-JCI/nbdev_cards.git -b nbdev_new_issue
cd nbdev_cards
yes | conda create -n good_env python pip
conda activate good_env
pip install -e ~/path_to_nbdev2/
nbdev_new --nbs_path nbs --lib_name nbdev_cards --description "nbdev cards" --user my_user --author my_author --author_email my_email --repo nbdev_cards
sed -i 's/recursive = False/recursive = True/' settings.ini
nbdev_export
pip install -e .
nbdev_prepare
nbdev_preview --port 3012
```
Note that when running `nbdev_new` we don't indicate `--recursive True`, and we do that later by editing `settings.ini`, which in the commands above is achieved by running:

```bash
sed -i 's/recursive = False/recursive = True/' settings.ini
```

When I run the above commands, I am not able to see the docs rendered. I am only able if I indicate `--recursive True` when running `nbdev_new`. I will try to reproduce this on my machine if I can get past the second issue that I mentioned above.

**Comment by Jaume-JCI** [comment]
I tried to reproduce the issue but wasn't able with the newest code. I found another issue, but it was just due to the fact that I hadn't pulled the latest commit from fastcore. After I solved this, I am not able to reproduce the aforementioned problem. I am closing the whole issue if that's fine. Apologies for this.

**Comment by hamelsmu** [comment]
Thank you for trying!
