### ISSUE TITLE
Error executing 'nbdev_filter': Broken pipe

### ISSUE THREAD

**Issue by filipj8** [fastai/nbdev#956]
The latest nbdev version has a regression and test & deploy CIs fail with the error `ERROR: Error executing 'nbdev_filter': Broken pipe (os error 32)`

During doc building (action: `quarto-ghp`, name: `Install Dependencies`) it fails when setting up quarto:
```
Preparing to unpack quarto-1.1.75-linux-amd64.deb ...
Unpacking quarto (1.1.75) ...
Setting up quarto (1.1.75) ...
ERROR: Error executing 'nbdev_filter': Broken pipe (os error 32)
Error: Process completed with exit code 1.
```

During testing (action: `nbdev-ci`, name: `Test with nbdev`), it fails after pip installing `.`:
```
Successfully installed devpackage-0.5.0
ERROR: Error executing 'nbdev_filter': Broken pipe (os error 32)
Quarto is not installed. We will download and install it for you.
Installing or upgrading quarto -- this requires root access.
Error: Process completed with exit code 1.
```

Interim fix:
Fork & pin nbdev to `v2.2.6` in `quarto-ghp` and `nbdev-ci` in https://github.com/fastai/workflows

**Comment by jph00** [comment]
That's not enough info for us to debug your issue, unfortunately. Could you please provide a reproducible example and details on your OS/python versions etc?

**Comment by jph00** [comment]
Closing due to no response.

**Comment by abdksyed** [comment]
Having a similar issue.
When I pushed to github, the github action is failing

```
...
...
Quarto is not installed. We will download and install it for you.
Installing or upgrading quarto -- this requires root access.
Error: Process completed with exit code 1.
```

Link for action : https://github.com/abdksyed/PlakshaTLP/runs/8291443626?check_suite_focus=true

**Comment by jph00** [comment]
@abdksyed your action shows the error: `ModuleNotFoundError: No module named 'numpy'`

**Comment by abdksyed** [comment]
Yeah, I saw it later. Thanks a lot for your answer.
