### ISSUE TITLE
Best way to export captions from markdown in nbdev?

### ISSUE THREAD

**Issue by hamelsmu** [fastai/nbdev#96]
the fastai blog has captions

![image](https://user-images.githubusercontent.com/1483922/75045894-edc2d980-5478-11ea-9d4c-aa936905b89f.png)

Would love to add this to fastpages, not completely sure how to inject captions.

I took a look at https://github.com/fastai/nbdev/blob/2eb60a5634d2296bc6b67fcd671ca0d584e22e35/nbs/index.ipynb, and it looks like this is done via HTML in a notebook like this?

`<img alt="Exporting from nbdev" width="700" caption="An example of a function defined in one cell (marked with the export flag) and explained, along with a visual example, in the following cells" src="images/export_example.png" />`

What is the best path for me to convert markdown in a similar way (as you can have descriptions in markdown as well)?  Such as `![Some descritpion](images/image.png)`

 I can help add this to nbdev but wanted to check here first.  Happy to post on forums instead if that is more appropriate.  Thank you 🙇

**Comment by sgugger** [comment]
Normally the text in some description is just for alt, but we could make it a caption too. This would require converting the `![alt](src)` to the html syntax automatically (since it's the only way I know to have caption). I don't think it hurts anything, so I'd say why not. I don't have the bandwidth to implement this right now, but maybe next week.

**Comment by hamelsmu** [comment]
@sgugger I found out that this is already supported by nbdev!!!!  The title automatically gets converted to a caption!!!

For example

```md
![](https://www.fast.ai/images/fastai_paper/show_batch.png "Credit: https://www.fast.ai/2020/02/13/fastai-A-Layered-API-for-Deep-Learning/")
```

Results in

![image](https://user-images.githubusercontent.com/1483922/75064923-b2d29d00-549c-11ea-839e-9f34621a99cf.png)

I have updated my docs to reflect this.

**Comment by sgugger** [comment]
Oh that's cool! Does it work ok with nbdev? I haven't anticipated that in the commands that deal with images, so want to make sure nbdev doesn't destroy anything in the process.

**Comment by hamelsmu** [comment]
It works great for me, I have encountered no problems - not sure if it is nbdev or nbconvert, but I think the behavior is really good as it is.  This way people can have seperate alt and caption text if they like
