### ISSUE TITLE
nb_export() removes imported library names if they match the directory name of the export path

### ISSUE THREAD

**Issue by tpdickson** [fastai/nbdev#968]
If you run `nb_export()` with a `lib_path` set to a path where the final directory matches any of the top-level import statements in the target notebook, those top-level imported library names will be removed in the exported `.py` file.

For example, if you have `from fastai.vision.all import *` within a code cell marked with `#|export` and you run `nb_export('/path/to/my/notebook.ipynb', '/some/export/path/fastai/`), the resulting `.py` file will contain the line

`from .vision.all import *`

when it should contain the line

`from fastai.vision.all import *`

I also tried it with other libraries in case `fastai` was a special case. The same issue occurred. Note that this only occurs when the _output path_ has the final directory match. The input path the `.ipynb` file is in seems to not matter.

---

Is this an issue with simply how python resolves imports, where the export processor thinks the import is from the local source rather than from an external module?

**Comment by jph00** [comment]
Yes if you are in a folder called `fastai`, then that's going to cause problems importing stuff from the `fastai` namespace. So best off using a different folder name.
