### ISSUE TITLE
unable to follow tutorial (Windows asks me which application it should use to open file)

### ISSUE THREAD

**Issue by vincenzooo** [fastai/nbdev#972]
Hello,
I am trying to follow the tutorial at [https://nbdev.fast.ai/01_Tutorials/01_tutorial.html] on Windows with conda. 
I am in a kupyter terminal in the browser.
Every time I try to run a command, like  `nbdev_install_quarto` or ``nbdev_new``, I get the Windows popup asking "How do you want to open this file?"..
I have tried to open with a text editor and it appears to be a .py file, however I don't know if it is appropriate to select a Python interpreter and which one.

I don't know if this is the reason why I am unable to follow the tutorial (I fail anyway as I am not able to add files to git repository)

**Comment by pabloms92** [comment]
Hi,
try:
`conda remove nbdev`

`pip install -U nbdev`
Somehow conda installs a file without extension and pip installs them as *.exe*

**Comment by vincenzooo** [comment]
Wow, thanks for the super fast reply, but now I get the error:

nbdev_install_quarto : The term 'nbdev_install_quarto' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nbdev_install_quarto
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nbdev_install_quarto:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jph00** [comment]
Windows is not supported - please use WSL.

**Comment by vincenzooo** [comment]
Thanks, I had missed it!
I have tried using WSL and it is still failing, should I open a new issue or post here?

**Comment by jph00** [comment]
New issue please
