### ISSUE TITLE
Best practices for notebook development

### ISSUE THREAD

**Issue by jph00** [fastai/nbdev#980]
E.g. don't put everything into docstrings. Use markdown cells in notebooks. Show examples of exceptions. Use tests to show expected behavior. Use pictures, plots, etc...

Useful notes in this comment from @seeM : https://github.com/fastai/nbdev/issues/964#issuecomment-1233781136 

There are also open questions for nbdev-style docs, like whether we could/should have a parameter table for object attributes, raises, and "see also" blocks ([this page from numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray) demonstrates a few of these).

**Comment by seeM** [comment]
Closed by #1011
