### ISSUE TITLE
_preview crash on `show_doc(inaccessible_module)`

### ISSUE THREAD

**Issue by jerzydziewierz** [fastai/nbdev#982]
### Environment:
* in a new notebook, add this:
```python 
---

#|export

from nbdev.showdoc import *

---

show_doc(inaccessible_module)

```

### Expected result

A helpful error message is displayed in the user-accessible output, and the rest of the document is rendered as normal.

### Observed result 

The preview server crashes with `ERROR: 500 (Internal Error):` 

### Other background information

Some intermediate code may import modules or functions that are accessible in certain environments and inaccessible in others.

**Comment by seeM** [comment]
Thanks for the clear write-up! :) @jph00 just finished a big rewrite of `nbdev_preview` which might be related to your issue. See [the forum post here](https://forums.fast.ai/t/new-parallel-docs-renderer/98779?u=seem) (in general, we recommend searching/posting on the forum rather than GitHub issues)

This is what I see from the preview server with the latest master version of nbdev (and execnb and fastcore), which I think is helpful:

```
Traceback (most recent call last):
  File "/Users/seem/.pyenv/versions/3.9.13/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-634808208b77>", line 3, in <cell line: 3>
    show_doc(inaccessible_module)
NameError: name 'inaccessible_module' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/seem/code/nbdev/nbdev/serve.py", line 112, in _f
    try: serve_drv.main(res)
  File "/Users/seem/code/nbdev/nbdev/serve_drv.py", line 20, in main
    if src.suffix=='.ipynb': exec_nb(src, dst, x)
  File "/Users/seem/code/nbdev/nbdev/serve_drv.py", line 14, in exec_nb
    cb()(nb)
  File "/Users/seem/code/nbdev/nbdev/processors.py", line 312, in __call__
    def __call__(self, nb): return self.nb_proc(nb).process()
  File "/Users/seem/code/nbdev/nbdev/process.py", line 122, in process
    for proc in self.procs: self._proc(proc)
  File "/Users/seem/code/nbdev/nbdev/process.py", line 115, in _proc
    for cell in self.nb.cells: self._process_cell(proc, cell)
  File "/Users/seem/code/nbdev/nbdev/process.py", line 106, in _process_cell
    if callable(proc) and not _is_direc(proc): cell = opt_set(cell, proc(cell))
  File "/Users/seem/code/nbdev/nbdev/processors.py", line 292, in __call__
    raise Exception(f"Error{' in notebook: '+title if title else ''} in cell {cell.idx_} :\n{cell.source}") from self.k.exc[1]
Exception: Error in cell 2 :
#|output: asis
#| echo: false
show_doc(inaccessible_module)
```

**Comment by jph00** [comment]
Regarding the "expected output":

> A helpful error message is displayed in the user-accessible output, and the rest of the document is rendered as normal.

AFAICT from what @seeM showed, we're already doing the former. The latter bit we generally don't aim for - the assumption is that if you've got errors in your notebook, it's likely to cause stuff after that to fail too. If we just keep plowing on, then you'll see miles of stack traces, and have to go find the first one to find the real problem.

**Comment by seeM** [comment]
Closing, we can reopen if necessary
