### ISSUE TITLE
Unicode/Syntax Error during execution of `nbdev_prepare`

### ISSUE THREAD

**Issue by githubpsyche** [fastai/nbdev#983]
When I run nbdev_prepare on Windows 11 using git bash or powershell, I get an error that looks like:

```
WARNING:root:SyntaxError in C:\Users\gunnj\compmemlearn\notebooks\datasets\Murdock1962.ipynb:
===========================================================================

While Executing:
←[1;36m  Input ←[1;32mIn [1]←[1;36m←[0m
←[1;33m    import sys; sys.path.insert(0, 'C:\Users\gunnj\compmemlearn\notebooks\datasets')←[0m
←[1;37m                                                                                   ^←[0m
←[1;31mSyntaxError←[0m←[1;31m:←[0m (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape


WARNING:root:SyntaxError in C:\Users\gunnj\compmemlearn\notebooks\analyses\Serial_Position_Effect.ipynb:
===========================================================================

While Executing:
←[1;36m  Input ←[1;32mIn [1]←[1;36m←[0m
←[1;33m    import sys; sys.path.insert(0, 'C:\Users\gunnj\compmemlearn\notebooks\analyses')←[0m
←[1;37m                                                                                   ^←[0m
←[1;31mSyntaxError←[0m←[1;31m:←[0m (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape



nbdev Tests Failed On The Following Notebooks:
==================================================
        Serial_Position_Effect.ipynb
        Murdock1962.ipynb
```

The `import sys` stuff is not part of my codebase, and switching the notebooks in my directory don't change the error. This seems to correspond to an issue discussed every so often on stackoverflow, including: 
https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file

> Here, `\U` in `"C:\Users...` starts an eight-character Unicode escape, such as `\U00014321`. In your code, the escape is followed by the character 's', which is invalid.

My intuition is that this is a problem with how paths are handled by the `nbdev_prepare` command, perhaps something specific to Windows. But if that were true, I'd expect this bug to have been caught sooner, so maybe I'm mistaken.

**Comment by githubpsyche** [comment]
`nbdev_prepare`  bundles the following commands:

[nbdev_export](https://nbdev.fast.ai/09_API/doclinks.html#nbdev_export): Builds the .py modules from Jupyter notebooks
[nbdev_test](https://nbdev.fast.ai/09_API/test.html#nbdev_test): Tests your notebooks
[nbdev_clean](https://nbdev.fast.ai/09_API/clean.html#nbdev_clean): Cleans your notebooks to get rid of extreanous output for Github
[nbdev_readme](https://nbdev.fast.ai/09_API/quarto.html#nbdev_readme): Updates README.md from your index notebook.

So I'm checking which of these produces the error.

`nbdev_export` is fine.
`nbdev_test` is the proximate cause of the issue that i posted
`nbdev_clean` returns 
```
C:\Users\gunnj\AppData\Local\Programs\Python\Python310\lib\site-packages\nbdev\clean.py:110: UserWarning: Failed to clean notebook
  warn(f'{warn_msg}')
C:\Users\gunnj\AppData\Local\Programs\Python\Python310\lib\site-packages\nbdev\clean.py:111: UserWarning: clean_ids
  warn(e)
C:\Users\gunnj\AppData\Local\Programs\Python\Python310\lib\site-packages\nbdev\clean.py:111: UserWarning: clean_ids
  warn(e)
```

`nbdev_readme` works fine.

**Comment by githubpsyche** [comment]
Further confirmed that this error arises even in a directory freshly generated with `nbdev_new`:

```
WARNING:root:SyntaxError in C:\Users\gunnj\nbdev_template\index.ipynb:
===========================================================================

While Executing:
←[1;36m  Input ←[1;32mIn [1]←[1;36m←[0m
←[1;33m    import sys; sys.path.insert(0, 'C:\Users\gunnj\nbdev_template')←[0m
←[1;37m                                                                  ^←[0m
←[1;31mSyntaxError←[0m←[1;31m:←[0m (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape


WARNING:root:SyntaxError in C:\Users\gunnj\nbdev_template\00_core.ipynb:
===========================================================================

While Executing:
←[1;36m  Input ←[1;32mIn [1]←[1;36m←[0m
←[1;33m    import sys; sys.path.insert(0, 'C:\Users\gunnj\nbdev_template')←[0m
←[1;37m                                                                  ^←[0m
←[1;31mSyntaxError←[0m←[1;31m:←[0m (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by jph00** [comment]
That's fixed in execnb master branch.
