### ISSUE TITLE
`nbdev_preview` stuck in perpetual Quatro install cycle

### ISSUE THREAD

**Issue by jakubLangr** [fastai/nbdev#985]
When I run `nbdev_preview` I get `Quarto` installation as follows:
```
Quarto is not installed. We will download and install it for you.
Installing or upgrading quarto -- this requires root access.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0    355      0 --:--:-- --:--:-- --:--:--   355
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 70.4M  100 70.4M    0     0  10.5M      0  0:00:06  0:00:06 --:--:-- 12.9M
installer: Package name is Quarto
installer: Upgrading at base path /
installer: The upgrade was successful.
...
sh: quarto: command not found
```
This happens repeatedly. I think the installation script is broken. I tried looking into this, but given that Quatro itself is not a very common/well documented library, it was pretty difficult.

I tried:
* brew installing 
* installing from Quatro's website
* linking quatro manually.

None of these seemed to help.

I'm on an M1 and use `zsh`

**Comment by jph00** [comment]
We can't help with quarto installation problems unfortunately - I'd suggest taking your question over to the quarto discussions: https://github.com/quarto-dev/quarto-cli/discussions
