### ISSUE TITLE
Windows having problem with clean notebook

### ISSUE THREAD

**Issue by jvanelteren** [fastai/nbdev#986]
I think it should be possible to run nbdev on Windows without WSL. I got nbdev1 working a year ago and had lot's of fun with it. Decided to migrate with clean nbdev 2. I installed everything with pip install through cmd and the nbdev commands seemed to work fine. 

However when committing to github the workflow failed: 
```
Check we are starting with clean git checkout
Trying to strip out notebooks
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbdev/clean.py:110: UserWarning: Failed to clean notebook
  warn(f'{warn_msg}')
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbdev/clean.py:111: UserWarning: clean_ids
  warn(e)
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbdev/clean.py:111: UserWarning: clean_ids
  warn(e)
Check that strip out was unnecessary
Error: Notebooks and library are not in sync.  Please run nbdev_export.
```

I did note the nbdev_clean command gives a similar output. nbdev_export seems to work.
Any ideas? Example (nothing much changed to default install: [link](https://github.com/jvanelteren/testnbdev))

**Comment by jph00** [comment]
The diff is shown in the actions output - there appear to be two locations that need an `as_posix` added to normalize path separators. https://github.com/jvanelteren/testnbdev/runs/8178832482?check_suite_focus=true#step:2:261

Feel free to put in a PR for this if you're interested.
