### ISSUE TITLE
An automated security update nokogiri

### ISSUE THREAD

**Issue by JiaxiangBU** [fastai/nbdev#99]
Hi, I use 'nbdev' to build a Python package. Today I receive an alert from GitHub.
Here is the alert public address https://github.com/JiaxiangBU/pyks/network/alert/Gemfile.lock/nokogiri/open
It suggests I should run `gem "nokogiri", ">= 1.10.8"` to update 'nokogiri'. I don't use 'Ruby' before.
How could I fix this?

In the `Gemfile.lock` file, it sets https://github.com/JiaxiangBU/pyks/blob/525f1632201da914654f4f3d7378160c96b8a518/Gemfile.lock#L75

Here is the package address hosted at GitHub: https://github.com/JiaxiangBU/pyks

**Comment by sgugger** [comment]
You should receive an automatic PR with this from GitHub, just merge it and you should be good to go.

**Comment by michaelaye** [comment]
This automated PR currently fails all checks:

![image](https://user-images.githubusercontent.com/69774/104532660-fb6fd900-55cd-11eb-90e7-830dce372665.png)
