### ISSUE TITLE
warnings while using `nbdev_clean`

### ISSUE THREAD

**Issue by deven367** [fastai/nbdev#990]
Hello,

I created a fresh repo with `nbdev_new` and when I run the `nbdev_clean` command, I get these user warnings. I'm not sure, why I get them. This was done on a fresh install of WSL2 on windows 10, setup with `fastsetup`. 

with a python version: 3.10.6
nbdev version: 2.2.10
fastcore: 1.5.24
execnb: 0.1.3

```(base) deven@Ideapad-310:~/project/papers$ nbdev_clean
/home/deven/mambaforge/lib/python3.10/site-packages/nbdev/clean.py:110: UserWarning: Failed to clean notebook
  warn(f'{warn_msg}')
/home/deven/mambaforge/lib/python3.10/site-packages/nbdev/clean.py:111: UserWarning: clean_ids
  warn(e)
/home/deven/mambaforge/lib/python3.10/site-packages/nbdev/clean.py:111: UserWarning: clean_ids
  warn(e)
```

**Comment by hamelsmu** [comment]
@deven367 any chance you can share a minimal example that we can use to reproduce the issue?

**Comment by deven367** [comment]
Sure, here is the [repo ](https://github.com/deven367/papers)

**Comment by hamelsmu** [comment]
@deven367 what if you try upgrading all the tools

```
echo fastcore ghapi execnb nbdev | xargs -n1 -I {} pip install -Uq git+https://github.com/fastai/{}.git
```

**Comment by hamelsmu** [comment]
@deven367 Actually I believe the best way to solve this is to set 

`clean_ids = True` in `settings.ini`

**Comment by deven367** [comment]
> `clean_ids = True` in `settings.ini` for the time being, until we cut a new release

This fixes the issue I'm having. Thanks @hamelsmu

**Comment by hamelsmu** [comment]
Great!
