### ISSUE TITLE
nbdev_test sometimes fails with uninformative message

### ISSUE THREAD

**Issue by thigm85** [fastai/nbdev#993]
In some cases, the failure output of `nbdev_test` shows precisely the error message of the notebook cell causing the failure. However, this is not always the case, as the example below demonstrates:

* Output from `nbdev_test` on my terminal.: 
![output_from_nbdev_test](https://user-images.githubusercontent.com/2162939/188708717-42e18c03-aa6d-4011-96ab-c5d1d5f96dd5.png)

* The Same message appears on [repo CI](https://github.com/thigm85/learntorank/runs/8208493763?check_suite_focus=true) as shown below:
![output_from_nbdev_test_ci](https://user-images.githubusercontent.com/2162939/188710079-a6b612b1-41da-49b1-82c1-a41010687c15.png)

* Actual error causing `nbdev_test` to fail obtained when running the notebook:
![actual_error_in_notebook](https://user-images.githubusercontent.com/2162939/188708730-001bf5ef-ef74-4473-adb7-0ad235307fcb.png)

**Comment by jph00** [comment]
We use `warn` to display test failure messages. Do you have any logging set up? And if so, is it configured to show warnings? If you've got logging set up and it's not configured to show warnings, you won't see these errors.

**Comment by seeM** [comment]
@thigm85 this should be fixed in latest master by https://github.com/fastai/nbdev/pull/1006. Please let me know if it doesn't

**Comment by thigm85** [comment]
> We use `warn` to display test failure messages. Do you have any logging set up? And if so, is it configured to show warnings? If you've got logging set up and it's not configured to show warnings, you won't see these errors.

There was no logging setup on my side.
